/* valaccodecontrolflowmodule.c generated by valac, the Vala compiler
 * generated from valaccodecontrolflowmodule.vala, do not modify */

/* valaccodecontrolflowmodule.vala
 *
 * Copyright (C) 2006-2011  Jürg Billeter
 * Copyright (C) 2006-2008  Raffaele Sandrini
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.

 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.

 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 * Author:
 * 	Jürg Billeter <j@bitron.ch>
 *	Raffaele Sandrini <raffaele@sandrini.ch>
 */

#include <glib.h>
#include <glib-object.h>
#include <vala.h>
#include <valaccode.h>
#include <valagee.h>
#include <stdlib.h>
#include <string.h>


#define VALA_TYPE_CCODE_BASE_MODULE (vala_ccode_base_module_get_type ())
#define VALA_CCODE_BASE_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_BASE_MODULE, ValaCCodeBaseModule))
#define VALA_CCODE_BASE_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_BASE_MODULE, ValaCCodeBaseModuleClass))
#define VALA_IS_CCODE_BASE_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_BASE_MODULE))
#define VALA_IS_CCODE_BASE_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_BASE_MODULE))
#define VALA_CCODE_BASE_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_BASE_MODULE, ValaCCodeBaseModuleClass))

typedef struct _ValaCCodeBaseModule ValaCCodeBaseModule;
typedef struct _ValaCCodeBaseModuleClass ValaCCodeBaseModuleClass;
typedef struct _ValaCCodeBaseModulePrivate ValaCCodeBaseModulePrivate;

#define VALA_CCODE_BASE_MODULE_TYPE_EMIT_CONTEXT (vala_ccode_base_module_emit_context_get_type ())
#define VALA_CCODE_BASE_MODULE_EMIT_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_CCODE_BASE_MODULE_TYPE_EMIT_CONTEXT, ValaCCodeBaseModuleEmitContext))
#define VALA_CCODE_BASE_MODULE_EMIT_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_CCODE_BASE_MODULE_TYPE_EMIT_CONTEXT, ValaCCodeBaseModuleEmitContextClass))
#define VALA_CCODE_BASE_MODULE_IS_EMIT_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_CCODE_BASE_MODULE_TYPE_EMIT_CONTEXT))
#define VALA_CCODE_BASE_MODULE_IS_EMIT_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_CCODE_BASE_MODULE_TYPE_EMIT_CONTEXT))
#define VALA_CCODE_BASE_MODULE_EMIT_CONTEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_CCODE_BASE_MODULE_TYPE_EMIT_CONTEXT, ValaCCodeBaseModuleEmitContextClass))

typedef struct _ValaCCodeBaseModuleEmitContext ValaCCodeBaseModuleEmitContext;
typedef struct _ValaCCodeBaseModuleEmitContextClass ValaCCodeBaseModuleEmitContextClass;

#define VALA_TYPE_CCODE_STRUCT_MODULE (vala_ccode_struct_module_get_type ())
#define VALA_CCODE_STRUCT_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_STRUCT_MODULE, ValaCCodeStructModule))
#define VALA_CCODE_STRUCT_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_STRUCT_MODULE, ValaCCodeStructModuleClass))
#define VALA_IS_CCODE_STRUCT_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_STRUCT_MODULE))
#define VALA_IS_CCODE_STRUCT_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_STRUCT_MODULE))
#define VALA_CCODE_STRUCT_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_STRUCT_MODULE, ValaCCodeStructModuleClass))

typedef struct _ValaCCodeStructModule ValaCCodeStructModule;
typedef struct _ValaCCodeStructModuleClass ValaCCodeStructModuleClass;
typedef struct _ValaCCodeStructModulePrivate ValaCCodeStructModulePrivate;

#define VALA_TYPE_CCODE_METHOD_MODULE (vala_ccode_method_module_get_type ())
#define VALA_CCODE_METHOD_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_METHOD_MODULE, ValaCCodeMethodModule))
#define VALA_CCODE_METHOD_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_METHOD_MODULE, ValaCCodeMethodModuleClass))
#define VALA_IS_CCODE_METHOD_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_METHOD_MODULE))
#define VALA_IS_CCODE_METHOD_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_METHOD_MODULE))
#define VALA_CCODE_METHOD_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_METHOD_MODULE, ValaCCodeMethodModuleClass))

typedef struct _ValaCCodeMethodModule ValaCCodeMethodModule;
typedef struct _ValaCCodeMethodModuleClass ValaCCodeMethodModuleClass;
typedef struct _ValaCCodeMethodModulePrivate ValaCCodeMethodModulePrivate;

#define VALA_TYPE_CCODE_CONTROL_FLOW_MODULE (vala_ccode_control_flow_module_get_type ())
#define VALA_CCODE_CONTROL_FLOW_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_CONTROL_FLOW_MODULE, ValaCCodeControlFlowModule))
#define VALA_CCODE_CONTROL_FLOW_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_CONTROL_FLOW_MODULE, ValaCCodeControlFlowModuleClass))
#define VALA_IS_CCODE_CONTROL_FLOW_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_CONTROL_FLOW_MODULE))
#define VALA_IS_CCODE_CONTROL_FLOW_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_CONTROL_FLOW_MODULE))
#define VALA_CCODE_CONTROL_FLOW_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_CONTROL_FLOW_MODULE, ValaCCodeControlFlowModuleClass))

typedef struct _ValaCCodeControlFlowModule ValaCCodeControlFlowModule;
typedef struct _ValaCCodeControlFlowModuleClass ValaCCodeControlFlowModuleClass;
typedef struct _ValaCCodeControlFlowModulePrivate ValaCCodeControlFlowModulePrivate;
#define _vala_ccode_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_ccode_node_unref (var), NULL)))
#define _vala_target_value_unref0(var) ((var == NULL) ? NULL : (var = (vala_target_value_unref (var), NULL)))
#define _vala_code_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_node_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _vala_iterable_unref0(var) ((var == NULL) ? NULL : (var = (vala_iterable_unref (var), NULL)))

#define VALA_TYPE_GLIB_VALUE (vala_glib_value_get_type ())
#define VALA_GLIB_VALUE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_GLIB_VALUE, ValaGLibValue))
#define VALA_GLIB_VALUE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_GLIB_VALUE, ValaGLibValueClass))
#define VALA_IS_GLIB_VALUE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_GLIB_VALUE))
#define VALA_IS_GLIB_VALUE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_GLIB_VALUE))
#define VALA_GLIB_VALUE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_GLIB_VALUE, ValaGLibValueClass))

typedef struct _ValaGLibValue ValaGLibValue;
typedef struct _ValaGLibValueClass ValaGLibValueClass;

struct _ValaCCodeBaseModule {
	ValaCodeGenerator parent_instance;
	ValaCCodeBaseModulePrivate * priv;
	ValaSymbol* root_symbol;
	ValaCCodeBaseModuleEmitContext* emit_context;
	ValaCCodeLineDirective* current_line;
	ValaCCodeFile* header_file;
	ValaCCodeFile* internal_header_file;
	ValaCCodeFile* cfile;
	ValaCCodeBaseModuleEmitContext* class_init_context;
	ValaCCodeBaseModuleEmitContext* base_init_context;
	ValaCCodeBaseModuleEmitContext* class_finalize_context;
	ValaCCodeBaseModuleEmitContext* base_finalize_context;
	ValaCCodeBaseModuleEmitContext* instance_init_context;
	ValaCCodeBaseModuleEmitContext* instance_finalize_context;
	ValaCCodeStruct* param_spec_struct;
	ValaCCodeStruct* closure_struct;
	ValaCCodeEnum* prop_enum;
	ValaSet* user_marshal_set;
	ValaSet* predefined_marshal_set;
	gint next_regex_id;
	gint next_coroutine_state;
	ValaDataType* void_type;
	ValaDataType* bool_type;
	ValaDataType* char_type;
	ValaDataType* uchar_type;
	ValaDataType* unichar_type;
	ValaDataType* short_type;
	ValaDataType* ushort_type;
	ValaDataType* int_type;
	ValaDataType* uint_type;
	ValaDataType* long_type;
	ValaDataType* ulong_type;
	ValaDataType* int8_type;
	ValaDataType* uint8_type;
	ValaDataType* int16_type;
	ValaDataType* uint16_type;
	ValaDataType* int32_type;
	ValaDataType* uint32_type;
	ValaDataType* int64_type;
	ValaDataType* uint64_type;
	ValaDataType* string_type;
	ValaDataType* regex_type;
	ValaDataType* float_type;
	ValaDataType* double_type;
	ValaTypeSymbol* gtype_type;
	ValaTypeSymbol* gobject_type;
	ValaErrorType* gerror_type;
	ValaClass* glist_type;
	ValaClass* gslist_type;
	ValaClass* gnode_type;
	ValaClass* gqueue_type;
	ValaClass* gvaluearray_type;
	ValaTypeSymbol* gstringbuilder_type;
	ValaTypeSymbol* garray_type;
	ValaTypeSymbol* gbytearray_type;
	ValaTypeSymbol* gptrarray_type;
	ValaTypeSymbol* gthreadpool_type;
	ValaDataType* gdestroynotify_type;
	ValaDataType* gquark_type;
	ValaStruct* gvalue_type;
	ValaClass* gvariant_type;
	ValaStruct* mutex_type;
	ValaStruct* gmutex_type;
	ValaStruct* grecmutex_type;
	ValaStruct* grwlock_type;
	ValaStruct* gcond_type;
	ValaClass* gsource_type;
	ValaTypeSymbol* type_module_type;
	ValaTypeSymbol* dbus_proxy_type;
	gboolean in_plugin;
	gchar* module_init_param_name;
	gboolean gvaluecollector_h_needed;
	gboolean requires_assert;
	gboolean requires_array_free;
	gboolean requires_array_move;
	gboolean requires_array_length;
	gboolean requires_clear_mutex;
	ValaSet* wrappers;
};

struct _ValaCCodeBaseModuleClass {
	ValaCodeGeneratorClass parent_class;
	void (*append_vala_array_free) (ValaCCodeBaseModule* self);
	void (*append_vala_array_move) (ValaCCodeBaseModule* self);
	void (*append_vala_array_length) (ValaCCodeBaseModule* self);
	gboolean (*generate_enum_declaration) (ValaCCodeBaseModule* self, ValaEnum* en, ValaCCodeFile* decl_space);
	void (*generate_class_struct_declaration) (ValaCCodeBaseModule* self, ValaClass* cl, ValaCCodeFile* decl_space);
	void (*generate_struct_declaration) (ValaCCodeBaseModule* self, ValaStruct* st, ValaCCodeFile* decl_space);
	void (*generate_delegate_declaration) (ValaCCodeBaseModule* self, ValaDelegate* d, ValaCCodeFile* decl_space);
	void (*generate_cparameters) (ValaCCodeBaseModule* self, ValaMethod* m, ValaCCodeFile* decl_space, ValaMap* cparam_map, ValaCCodeFunction* func, ValaCCodeFunctionDeclarator* vdeclarator, ValaMap* carg_map, ValaCCodeFunctionCall* vcall, gint direction);
	ValaCCodeExpression* (*get_dup_func_expression) (ValaCCodeBaseModule* self, ValaDataType* type, ValaSourceReference* source_reference, gboolean is_chainup);
	gchar* (*append_struct_array_free) (ValaCCodeBaseModule* self, ValaStruct* st);
	ValaCCodeExpression* (*destroy_value) (ValaCCodeBaseModule* self, ValaTargetValue* value, gboolean is_macro_definition);
	void (*append_scope_free) (ValaCCodeBaseModule* self, ValaSymbol* sym, ValaCodeNode* stop_at);
	ValaTargetValue* (*get_local_cvalue) (ValaCCodeBaseModule* self, ValaLocalVariable* local);
	ValaTargetValue* (*get_parameter_cvalue) (ValaCCodeBaseModule* self, ValaParameter* param);
	ValaTargetValue* (*get_field_cvalue) (ValaCCodeBaseModule* self, ValaField* field, ValaTargetValue* instance);
	ValaTargetValue* (*load_variable) (ValaCCodeBaseModule* self, ValaVariable* variable, ValaTargetValue* value);
	ValaTargetValue* (*load_this_parameter) (ValaCCodeBaseModule* self, ValaTypeSymbol* sym);
	void (*store_value) (ValaCCodeBaseModule* self, ValaTargetValue* lvalue, ValaTargetValue* value);
	gchar* (*get_delegate_target_cname) (ValaCCodeBaseModule* self, const gchar* delegate_cname);
	ValaCCodeExpression* (*get_delegate_target_cexpression) (ValaCCodeBaseModule* self, ValaExpression* delegate_expr, ValaCCodeExpression** delegate_target_destroy_notify);
	ValaCCodeExpression* (*get_delegate_target_cvalue) (ValaCCodeBaseModule* self, ValaTargetValue* value);
	ValaCCodeExpression* (*get_delegate_target_destroy_notify_cvalue) (ValaCCodeBaseModule* self, ValaTargetValue* value);
	gchar* (*get_delegate_target_destroy_notify_cname) (ValaCCodeBaseModule* self, const gchar* delegate_cname);
	ValaTargetValue* (*copy_value) (ValaCCodeBaseModule* self, ValaTargetValue* value, ValaCodeNode* node);
	void (*generate_class_declaration) (ValaCCodeBaseModule* self, ValaClass* cl, ValaCCodeFile* decl_space);
	void (*generate_interface_declaration) (ValaCCodeBaseModule* self, ValaInterface* iface, ValaCCodeFile* decl_space);
	void (*generate_method_declaration) (ValaCCodeBaseModule* self, ValaMethod* m, ValaCCodeFile* decl_space);
	void (*generate_error_domain_declaration) (ValaCCodeBaseModule* self, ValaErrorDomain* edomain, ValaCCodeFile* decl_space);
	ValaCCodeExpression* (*deserialize_expression) (ValaCCodeBaseModule* self, ValaDataType* type, ValaCCodeExpression* variant_expr, ValaCCodeExpression* expr, ValaCCodeExpression* error_expr, gboolean* may_fail);
	ValaCCodeExpression* (*serialize_expression) (ValaCCodeBaseModule* self, ValaDataType* type, ValaCCodeExpression* expr);
	ValaCCodeExpression* (*get_implicit_cast_expression) (ValaCCodeBaseModule* self, ValaCCodeExpression* source_cexpr, ValaDataType* expression_type, ValaDataType* target_type, ValaCodeNode* node);
	void (*create_type_check_statement) (ValaCCodeBaseModule* self, ValaCodeNode* method_node, ValaDataType* ret_type, ValaTypeSymbol* t, gboolean non_null, const gchar* var_name);
	gboolean (*is_gobject_property) (ValaCCodeBaseModule* self, ValaProperty* prop);
	void (*generate_dynamic_method_wrapper) (ValaCCodeBaseModule* self, ValaDynamicMethod* method);
	gboolean (*method_has_wrapper) (ValaCCodeBaseModule* self, ValaMethod* method);
	ValaCCodeFunctionCall* (*get_param_spec) (ValaCCodeBaseModule* self, ValaProperty* prop);
	ValaCCodeFunctionCall* (*get_signal_creation) (ValaCCodeBaseModule* self, ValaSignal* sig, ValaTypeSymbol* type);
	void (*register_dbus_info) (ValaCCodeBaseModule* self, ValaCCodeBlock* block, ValaObjectTypeSymbol* bindable);
	gchar* (*get_dynamic_property_getter_cname) (ValaCCodeBaseModule* self, ValaDynamicProperty* node);
	gchar* (*get_dynamic_property_setter_cname) (ValaCCodeBaseModule* self, ValaDynamicProperty* node);
	gchar* (*get_dynamic_signal_cname) (ValaCCodeBaseModule* self, ValaDynamicSignal* node);
	gchar* (*get_dynamic_signal_connect_wrapper_name) (ValaCCodeBaseModule* self, ValaDynamicSignal* node);
	gchar* (*get_dynamic_signal_connect_after_wrapper_name) (ValaCCodeBaseModule* self, ValaDynamicSignal* node);
	gchar* (*get_dynamic_signal_disconnect_wrapper_name) (ValaCCodeBaseModule* self, ValaDynamicSignal* node);
	gchar* (*get_array_length_cname) (ValaCCodeBaseModule* self, const gchar* array_cname, gint dim);
	gchar* (*get_parameter_array_length_cname) (ValaCCodeBaseModule* self, ValaParameter* param, gint dim);
	ValaCCodeExpression* (*get_array_length_cexpression) (ValaCCodeBaseModule* self, ValaExpression* array_expr, gint dim);
	ValaCCodeExpression* (*get_array_length_cvalue) (ValaCCodeBaseModule* self, ValaTargetValue* value, gint dim);
	gchar* (*get_array_size_cname) (ValaCCodeBaseModule* self, const gchar* array_cname);
	void (*add_simple_check) (ValaCCodeBaseModule* self, ValaCodeNode* node, gboolean always_fails);
	gchar* (*generate_ready_function) (ValaCCodeBaseModule* self, ValaMethod* m);
};

struct _ValaCCodeStructModule {
	ValaCCodeBaseModule parent_instance;
	ValaCCodeStructModulePrivate * priv;
};

struct _ValaCCodeStructModuleClass {
	ValaCCodeBaseModuleClass parent_class;
};

struct _ValaCCodeMethodModule {
	ValaCCodeStructModule parent_instance;
	ValaCCodeMethodModulePrivate * priv;
};

struct _ValaCCodeMethodModuleClass {
	ValaCCodeStructModuleClass parent_class;
	void (*generate_method_result_declaration) (ValaCCodeMethodModule* self, ValaMethod* m, ValaCCodeFile* decl_space, ValaCCodeFunction* cfunc, ValaMap* cparam_map, ValaMap* carg_map);
	ValaCCodeParameter* (*generate_parameter) (ValaCCodeMethodModule* self, ValaParameter* param, ValaCCodeFile* decl_space, ValaMap* cparam_map, ValaMap* carg_map);
};

struct _ValaCCodeControlFlowModule {
	ValaCCodeMethodModule parent_instance;
	ValaCCodeControlFlowModulePrivate * priv;
};

struct _ValaCCodeControlFlowModuleClass {
	ValaCCodeMethodModuleClass parent_class;
};


static gpointer vala_ccode_control_flow_module_parent_class = NULL;

GType vala_ccode_base_module_get_type (void) G_GNUC_CONST;
gpointer vala_ccode_base_module_emit_context_ref (gpointer instance);
void vala_ccode_base_module_emit_context_unref (gpointer instance);
GParamSpec* vala_ccode_base_module_param_spec_emit_context (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void vala_ccode_base_module_value_set_emit_context (GValue* value, gpointer v_object);
void vala_ccode_base_module_value_take_emit_context (GValue* value, gpointer v_object);
gpointer vala_ccode_base_module_value_get_emit_context (const GValue* value);
GType vala_ccode_base_module_emit_context_get_type (void) G_GNUC_CONST;
GType vala_ccode_struct_module_get_type (void) G_GNUC_CONST;
GType vala_ccode_method_module_get_type (void) G_GNUC_CONST;
GType vala_ccode_control_flow_module_get_type (void) G_GNUC_CONST;
enum  {
	VALA_CCODE_CONTROL_FLOW_MODULE_DUMMY_PROPERTY
};
static void vala_ccode_control_flow_module_real_visit_if_statement (ValaCodeVisitor* base, ValaIfStatement* stmt);
ValaCCodeFunction* vala_ccode_base_module_get_ccode (ValaCCodeBaseModule* self);
ValaCCodeExpression* vala_ccode_base_module_get_cvalue (ValaCCodeBaseModule* self, ValaExpression* expr);
static void vala_ccode_control_flow_module_visit_string_switch_statement (ValaCCodeControlFlowModule* self, ValaSwitchStatement* stmt);
ValaTargetValue* vala_ccode_base_module_create_temp_value (ValaCCodeBaseModule* self, ValaDataType* type, gboolean init, ValaCodeNode* node_reference, gboolean* value_owned);
ValaCCodeExpression* vala_ccode_base_module_get_cvalue_ (ValaCCodeBaseModule* self, ValaTargetValue* value);
gint vala_ccode_base_module_get_next_temp_var_id (ValaCCodeBaseModule* self);
void vala_ccode_base_module_set_next_temp_var_id (ValaCCodeBaseModule* self, gint value);
gboolean vala_ccode_base_module_is_constant_ccode_expression (ValaCCodeBaseModule* self, ValaCCodeExpression* cexpr);
gchar* vala_ccode_base_module_get_ccode_name (ValaCodeNode* node);
static void vala_ccode_control_flow_module_real_visit_switch_statement (ValaCodeVisitor* base, ValaSwitchStatement* stmt);
static void vala_ccode_control_flow_module_real_visit_switch_label (ValaCodeVisitor* base, ValaSwitchLabel* label);
static void vala_ccode_control_flow_module_real_visit_loop (ValaCodeVisitor* base, ValaLoop* stmt);
static void vala_ccode_control_flow_module_real_visit_foreach_statement (ValaCodeVisitor* base, ValaForeachStatement* stmt);
ValaCCodeExpression* vala_ccode_base_module_get_variable_cexpression (ValaCCodeBaseModule* self, const gchar* name);
gchar* vala_ccode_base_module_get_local_cname (ValaCCodeBaseModule* self, ValaLocalVariable* local);
void vala_ccode_base_module_add_simple_check (ValaCCodeBaseModule* self, ValaCodeNode* node, gboolean always_fails);
ValaCCodeExpression* vala_ccode_base_module_get_array_length_cexpression (ValaCCodeBaseModule* self, ValaExpression* array_expr, gint dim);
gchar* vala_ccode_base_module_get_array_length_cname (ValaCCodeBaseModule* self, const gchar* array_cname, gint dim);
ValaTargetValue* vala_ccode_base_module_transform_value (ValaCCodeBaseModule* self, ValaTargetValue* value, ValaDataType* target_type, ValaCodeNode* node);
ValaGLibValue* vala_glib_value_new (ValaDataType* value_type, ValaCCodeExpression* cvalue, gboolean lvalue);
ValaGLibValue* vala_glib_value_construct (GType object_type, ValaDataType* value_type, ValaCCodeExpression* cvalue, gboolean lvalue);
GType vala_glib_value_get_type (void) G_GNUC_CONST;
ValaCCodeExpression* vala_ccode_base_module_convert_from_generic_pointer (ValaCCodeBaseModule* self, ValaCCodeExpression* cexpr, ValaDataType* actual_type);
gchar* vala_ccode_base_module_get_variable_cname (ValaCCodeBaseModule* self, const gchar* name);
ValaTargetValue* vala_ccode_base_module_copy_value (ValaCCodeBaseModule* self, ValaTargetValue* value, ValaCodeNode* node);
gboolean vala_ccode_base_module_requires_destroy (ValaCCodeBaseModule* self, ValaDataType* type);
ValaCCodeExpression* vala_ccode_base_module_destroy_local (ValaCCodeBaseModule* self, ValaLocalVariable* local);
static void vala_ccode_control_flow_module_real_visit_break_statement (ValaCodeVisitor* base, ValaBreakStatement* stmt);
void vala_ccode_base_module_append_local_free (ValaCCodeBaseModule* self, ValaSymbol* sym, gboolean stop_at_loop, ValaCodeNode* stop_at);
ValaSymbol* vala_ccode_base_module_get_current_symbol (ValaCCodeBaseModule* self);
static void vala_ccode_control_flow_module_real_visit_continue_statement (ValaCodeVisitor* base, ValaContinueStatement* stmt);
ValaCCodeControlFlowModule* vala_ccode_control_flow_module_construct (GType object_type);
ValaCCodeMethodModule* vala_ccode_method_module_construct (GType object_type);


static void vala_ccode_control_flow_module_real_visit_if_statement (ValaCodeVisitor* base, ValaIfStatement* stmt) {
	ValaCCodeControlFlowModule * self;
	ValaCCodeFunction* _tmp0_;
	ValaCCodeFunction* _tmp1_;
	ValaIfStatement* _tmp2_;
	ValaExpression* _tmp3_;
	ValaExpression* _tmp4_;
	ValaCCodeExpression* _tmp5_ = NULL;
	ValaCCodeExpression* _tmp6_;
	ValaIfStatement* _tmp7_;
	ValaBlock* _tmp8_;
	ValaBlock* _tmp9_;
	ValaIfStatement* _tmp10_;
	ValaBlock* _tmp11_;
	ValaBlock* _tmp12_;
	ValaCCodeFunction* _tmp18_;
	ValaCCodeFunction* _tmp19_;
	self = (ValaCCodeControlFlowModule*) base;
	g_return_if_fail (stmt != NULL);
	_tmp0_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = stmt;
	_tmp3_ = vala_if_statement_get_condition (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = vala_ccode_base_module_get_cvalue ((ValaCCodeBaseModule*) self, _tmp4_);
	_tmp6_ = _tmp5_;
	vala_ccode_function_open_if (_tmp1_, _tmp6_);
	_vala_ccode_node_unref0 (_tmp6_);
	_tmp7_ = stmt;
	_tmp8_ = vala_if_statement_get_true_statement (_tmp7_);
	_tmp9_ = _tmp8_;
	vala_code_node_emit ((ValaCodeNode*) _tmp9_, (ValaCodeGenerator*) self);
	_tmp10_ = stmt;
	_tmp11_ = vala_if_statement_get_false_statement (_tmp10_);
	_tmp12_ = _tmp11_;
	if (_tmp12_ != NULL) {
		ValaCCodeFunction* _tmp13_;
		ValaCCodeFunction* _tmp14_;
		ValaIfStatement* _tmp15_;
		ValaBlock* _tmp16_;
		ValaBlock* _tmp17_;
		_tmp13_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp14_ = _tmp13_;
		vala_ccode_function_add_else (_tmp14_);
		_tmp15_ = stmt;
		_tmp16_ = vala_if_statement_get_false_statement (_tmp15_);
		_tmp17_ = _tmp16_;
		vala_code_node_emit ((ValaCodeNode*) _tmp17_, (ValaCodeGenerator*) self);
	}
	_tmp18_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp19_ = _tmp18_;
	vala_ccode_function_close (_tmp19_);
}


static gpointer _vala_code_node_ref0 (gpointer self) {
	return self ? vala_code_node_ref (self) : NULL;
}


static gpointer _vala_ccode_node_ref0 (gpointer self) {
	return self ? vala_ccode_node_ref (self) : NULL;
}


static void vala_ccode_control_flow_module_visit_string_switch_statement (ValaCCodeControlFlowModule* self, ValaSwitchStatement* stmt) {
	ValaSwitchStatement* _tmp0_;
	ValaExpression* _tmp1_;
	ValaExpression* _tmp2_;
	ValaDataType* _tmp3_;
	ValaDataType* _tmp4_;
	ValaSwitchStatement* _tmp5_;
	ValaTargetValue* _tmp6_ = NULL;
	ValaTargetValue* temp_value;
	ValaTargetValue* _tmp7_;
	ValaCCodeExpression* _tmp8_ = NULL;
	ValaCCodeExpression* ctemp;
	ValaCCodeExpression* _tmp9_;
	ValaSwitchStatement* _tmp10_;
	ValaExpression* _tmp11_;
	ValaExpression* _tmp12_;
	ValaCCodeExpression* _tmp13_ = NULL;
	ValaCCodeExpression* _tmp14_;
	ValaCCodeAssignment* _tmp15_;
	ValaCCodeAssignment* _tmp16_;
	ValaCCodeAssignment* cinit;
	ValaCCodeConstant* _tmp17_;
	ValaCCodeConstant* czero;
	ValaCCodeIdentifier* _tmp18_;
	ValaCCodeIdentifier* _tmp19_;
	ValaCCodeFunctionCall* _tmp20_;
	ValaCCodeFunctionCall* _tmp21_;
	ValaCCodeFunctionCall* free_call;
	ValaCCodeFunctionCall* _tmp22_;
	ValaCCodeExpression* _tmp23_;
	ValaCCodeConstant* _tmp24_;
	ValaCCodeConstant* _tmp25_;
	ValaCCodeExpression* _tmp26_;
	ValaCCodeBinaryExpression* _tmp27_;
	ValaCCodeBinaryExpression* _tmp28_;
	ValaCCodeBinaryExpression* cisnull;
	ValaCCodeIdentifier* _tmp29_;
	ValaCCodeIdentifier* _tmp30_;
	ValaCCodeFunctionCall* _tmp31_;
	ValaCCodeFunctionCall* _tmp32_;
	ValaCCodeFunctionCall* cquark;
	ValaCCodeFunctionCall* _tmp33_;
	ValaCCodeExpression* _tmp34_;
	ValaCCodeBinaryExpression* _tmp35_;
	ValaCCodeConstant* _tmp36_;
	ValaCCodeConstant* _tmp37_;
	ValaCCodeFunctionCall* _tmp38_;
	ValaCCodeConditionalExpression* _tmp39_;
	ValaCCodeConditionalExpression* _tmp40_;
	ValaCCodeConditionalExpression* ccond;
	gint _tmp41_;
	gint _tmp42_;
	gint label_temp_id;
	ValaDataType* _tmp43_;
	ValaSwitchStatement* _tmp44_;
	ValaTargetValue* _tmp45_ = NULL;
	gint label_count;
	ValaCCodeFunction* _tmp91_;
	ValaCCodeFunction* _tmp92_;
	ValaCCodeAssignment* _tmp93_;
	ValaTargetValue* _tmp94_;
	ValaCCodeExpression* _tmp95_ = NULL;
	ValaCCodeExpression* _tmp96_;
	ValaCCodeConditionalExpression* _tmp97_;
	ValaCCodeAssignment* _tmp98_;
	ValaCCodeFunction* _tmp99_;
	ValaCCodeFunction* _tmp100_;
	ValaCCodeAssignment* _tmp101_;
	ValaSwitchStatement* _tmp102_;
	ValaExpression* _tmp103_;
	ValaExpression* _tmp104_;
	ValaDataType* _tmp105_;
	ValaDataType* _tmp106_;
	gboolean _tmp107_;
	gboolean _tmp108_;
	ValaSwitchSection* default_section;
	gint n;
	ValaSwitchSection* _tmp203_;
	gint _tmp216_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (stmt != NULL);
	_tmp0_ = stmt;
	_tmp1_ = vala_switch_statement_get_expression (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = vala_expression_get_value_type (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = stmt;
	_tmp6_ = vala_ccode_base_module_create_temp_value ((ValaCCodeBaseModule*) self, _tmp4_, FALSE, (ValaCodeNode*) _tmp5_, NULL);
	temp_value = _tmp6_;
	_tmp7_ = temp_value;
	_tmp8_ = vala_ccode_base_module_get_cvalue_ ((ValaCCodeBaseModule*) self, _tmp7_);
	ctemp = _tmp8_;
	_tmp9_ = ctemp;
	_tmp10_ = stmt;
	_tmp11_ = vala_switch_statement_get_expression (_tmp10_);
	_tmp12_ = _tmp11_;
	_tmp13_ = vala_ccode_base_module_get_cvalue ((ValaCCodeBaseModule*) self, _tmp12_);
	_tmp14_ = _tmp13_;
	_tmp15_ = vala_ccode_assignment_new (_tmp9_, _tmp14_, VALA_CCODE_ASSIGNMENT_OPERATOR_SIMPLE);
	_tmp16_ = _tmp15_;
	_vala_ccode_node_unref0 (_tmp14_);
	cinit = _tmp16_;
	_tmp17_ = vala_ccode_constant_new ("0");
	czero = _tmp17_;
	_tmp18_ = vala_ccode_identifier_new ("g_free");
	_tmp19_ = _tmp18_;
	_tmp20_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp19_);
	_tmp21_ = _tmp20_;
	_vala_ccode_node_unref0 (_tmp19_);
	free_call = _tmp21_;
	_tmp22_ = free_call;
	_tmp23_ = ctemp;
	vala_ccode_function_call_add_argument (_tmp22_, _tmp23_);
	_tmp24_ = vala_ccode_constant_new ("NULL");
	_tmp25_ = _tmp24_;
	_tmp26_ = ctemp;
	_tmp27_ = vala_ccode_binary_expression_new (VALA_CCODE_BINARY_OPERATOR_EQUALITY, (ValaCCodeExpression*) _tmp25_, _tmp26_);
	_tmp28_ = _tmp27_;
	_vala_ccode_node_unref0 (_tmp25_);
	cisnull = _tmp28_;
	_tmp29_ = vala_ccode_identifier_new ("g_quark_from_string");
	_tmp30_ = _tmp29_;
	_tmp31_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp30_);
	_tmp32_ = _tmp31_;
	_vala_ccode_node_unref0 (_tmp30_);
	cquark = _tmp32_;
	_tmp33_ = cquark;
	_tmp34_ = ctemp;
	vala_ccode_function_call_add_argument (_tmp33_, _tmp34_);
	_tmp35_ = cisnull;
	_tmp36_ = vala_ccode_constant_new ("0");
	_tmp37_ = _tmp36_;
	_tmp38_ = cquark;
	_tmp39_ = vala_ccode_conditional_expression_new ((ValaCCodeExpression*) _tmp35_, (ValaCCodeExpression*) _tmp37_, (ValaCCodeExpression*) _tmp38_);
	_tmp40_ = _tmp39_;
	_vala_ccode_node_unref0 (_tmp37_);
	ccond = _tmp40_;
	_tmp41_ = vala_ccode_base_module_get_next_temp_var_id ((ValaCCodeBaseModule*) self);
	_tmp42_ = _tmp41_;
	vala_ccode_base_module_set_next_temp_var_id ((ValaCCodeBaseModule*) self, _tmp42_ + 1);
	label_temp_id = _tmp42_;
	_tmp43_ = ((ValaCCodeBaseModule*) self)->gquark_type;
	_tmp44_ = stmt;
	_tmp45_ = vala_ccode_base_module_create_temp_value ((ValaCCodeBaseModule*) self, _tmp43_, TRUE, (ValaCodeNode*) _tmp44_, NULL);
	_vala_target_value_unref0 (temp_value);
	temp_value = _tmp45_;
	label_count = 0;
	{
		ValaSwitchStatement* _tmp46_;
		ValaList* _tmp47_ = NULL;
		ValaList* _section_list;
		ValaList* _tmp48_;
		gint _tmp49_;
		gint _tmp50_;
		gint _section_size;
		gint _section_index;
		_tmp46_ = stmt;
		_tmp47_ = vala_switch_statement_get_sections (_tmp46_);
		_section_list = _tmp47_;
		_tmp48_ = _section_list;
		_tmp49_ = vala_collection_get_size ((ValaCollection*) _tmp48_);
		_tmp50_ = _tmp49_;
		_section_size = _tmp50_;
		_section_index = -1;
		while (TRUE) {
			gint _tmp51_;
			gint _tmp52_;
			gint _tmp53_;
			ValaList* _tmp54_;
			gint _tmp55_;
			gpointer _tmp56_ = NULL;
			ValaSwitchSection* section;
			ValaSwitchSection* _tmp57_;
			gboolean _tmp58_ = FALSE;
			_tmp51_ = _section_index;
			_section_index = _tmp51_ + 1;
			_tmp52_ = _section_index;
			_tmp53_ = _section_size;
			if (!(_tmp52_ < _tmp53_)) {
				break;
			}
			_tmp54_ = _section_list;
			_tmp55_ = _section_index;
			_tmp56_ = vala_list_get (_tmp54_, _tmp55_);
			section = (ValaSwitchSection*) _tmp56_;
			_tmp57_ = section;
			_tmp58_ = vala_switch_section_has_default_label (_tmp57_);
			if (_tmp58_) {
				_vala_code_node_unref0 (section);
				continue;
			}
			{
				ValaSwitchSection* _tmp59_;
				ValaList* _tmp60_ = NULL;
				ValaList* _label_list;
				ValaList* _tmp61_;
				gint _tmp62_;
				gint _tmp63_;
				gint _label_size;
				gint _label_index;
				_tmp59_ = section;
				_tmp60_ = vala_switch_section_get_labels (_tmp59_);
				_label_list = _tmp60_;
				_tmp61_ = _label_list;
				_tmp62_ = vala_collection_get_size ((ValaCollection*) _tmp61_);
				_tmp63_ = _tmp62_;
				_label_size = _tmp63_;
				_label_index = -1;
				while (TRUE) {
					gint _tmp64_;
					gint _tmp65_;
					gint _tmp66_;
					ValaList* _tmp67_;
					gint _tmp68_;
					gpointer _tmp69_ = NULL;
					ValaSwitchLabel* label;
					ValaSwitchLabel* _tmp70_;
					ValaExpression* _tmp71_;
					ValaExpression* _tmp72_;
					ValaSwitchLabel* _tmp73_;
					ValaExpression* _tmp74_;
					ValaExpression* _tmp75_;
					ValaCCodeExpression* _tmp76_ = NULL;
					ValaCCodeExpression* cexpr;
					ValaCCodeExpression* _tmp77_;
					gboolean _tmp78_ = FALSE;
					_tmp64_ = _label_index;
					_label_index = _tmp64_ + 1;
					_tmp65_ = _label_index;
					_tmp66_ = _label_size;
					if (!(_tmp65_ < _tmp66_)) {
						break;
					}
					_tmp67_ = _label_list;
					_tmp68_ = _label_index;
					_tmp69_ = vala_list_get (_tmp67_, _tmp68_);
					label = (ValaSwitchLabel*) _tmp69_;
					_tmp70_ = label;
					_tmp71_ = vala_switch_label_get_expression (_tmp70_);
					_tmp72_ = _tmp71_;
					vala_code_node_emit ((ValaCodeNode*) _tmp72_, (ValaCodeGenerator*) self);
					_tmp73_ = label;
					_tmp74_ = vala_switch_label_get_expression (_tmp73_);
					_tmp75_ = _tmp74_;
					_tmp76_ = vala_ccode_base_module_get_cvalue ((ValaCCodeBaseModule*) self, _tmp75_);
					cexpr = _tmp76_;
					_tmp77_ = cexpr;
					_tmp78_ = vala_ccode_base_module_is_constant_ccode_expression ((ValaCCodeBaseModule*) self, _tmp77_);
					if (_tmp78_) {
						gint _tmp79_;
						gint _tmp80_;
						gchar* _tmp81_ = NULL;
						gchar* cname;
						ValaCCodeFunction* _tmp82_;
						ValaCCodeFunction* _tmp83_;
						ValaDataType* _tmp84_;
						gchar* _tmp85_ = NULL;
						gchar* _tmp86_;
						const gchar* _tmp87_;
						ValaCCodeConstant* _tmp88_;
						ValaCCodeVariableDeclarator* _tmp89_;
						ValaCCodeVariableDeclarator* _tmp90_;
						_tmp79_ = label_temp_id;
						_tmp80_ = label_count;
						label_count = _tmp80_ + 1;
						_tmp81_ = g_strdup_printf ("_tmp%d_label%d", _tmp79_, _tmp80_);
						cname = _tmp81_;
						_tmp82_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
						_tmp83_ = _tmp82_;
						_tmp84_ = ((ValaCCodeBaseModule*) self)->gquark_type;
						_tmp85_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp84_);
						_tmp86_ = _tmp85_;
						_tmp87_ = cname;
						_tmp88_ = czero;
						_tmp89_ = vala_ccode_variable_declarator_new (_tmp87_, (ValaCCodeExpression*) _tmp88_, NULL);
						_tmp90_ = _tmp89_;
						vala_ccode_function_add_declaration (_tmp83_, _tmp86_, (ValaCCodeDeclarator*) _tmp90_, VALA_CCODE_MODIFIERS_STATIC);
						_vala_ccode_node_unref0 (_tmp90_);
						_g_free0 (_tmp86_);
						_g_free0 (cname);
					}
					_vala_ccode_node_unref0 (cexpr);
					_vala_code_node_unref0 (label);
				}
				_vala_iterable_unref0 (_label_list);
			}
			_vala_code_node_unref0 (section);
		}
		_vala_iterable_unref0 (_section_list);
	}
	_tmp91_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp92_ = _tmp91_;
	_tmp93_ = cinit;
	vala_ccode_function_add_expression (_tmp92_, (ValaCCodeExpression*) _tmp93_);
	_tmp94_ = temp_value;
	_tmp95_ = vala_ccode_base_module_get_cvalue_ ((ValaCCodeBaseModule*) self, _tmp94_);
	_vala_ccode_node_unref0 (ctemp);
	ctemp = _tmp95_;
	_tmp96_ = ctemp;
	_tmp97_ = ccond;
	_tmp98_ = vala_ccode_assignment_new (_tmp96_, (ValaCCodeExpression*) _tmp97_, VALA_CCODE_ASSIGNMENT_OPERATOR_SIMPLE);
	_vala_ccode_node_unref0 (cinit);
	cinit = _tmp98_;
	_tmp99_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp100_ = _tmp99_;
	_tmp101_ = cinit;
	vala_ccode_function_add_expression (_tmp100_, (ValaCCodeExpression*) _tmp101_);
	_tmp102_ = stmt;
	_tmp103_ = vala_switch_statement_get_expression (_tmp102_);
	_tmp104_ = _tmp103_;
	_tmp105_ = vala_expression_get_value_type (_tmp104_);
	_tmp106_ = _tmp105_;
	_tmp107_ = vala_data_type_get_value_owned (_tmp106_);
	_tmp108_ = _tmp107_;
	if (_tmp108_) {
		ValaCCodeFunction* _tmp109_;
		ValaCCodeFunction* _tmp110_;
		ValaCCodeFunctionCall* _tmp111_;
		_tmp109_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp110_ = _tmp109_;
		_tmp111_ = free_call;
		vala_ccode_function_add_expression (_tmp110_, (ValaCCodeExpression*) _tmp111_);
	}
	default_section = NULL;
	label_count = 0;
	n = 0;
	{
		ValaSwitchStatement* _tmp112_;
		ValaList* _tmp113_ = NULL;
		ValaList* _section_list;
		ValaList* _tmp114_;
		gint _tmp115_;
		gint _tmp116_;
		gint _section_size;
		gint _section_index;
		_tmp112_ = stmt;
		_tmp113_ = vala_switch_statement_get_sections (_tmp112_);
		_section_list = _tmp113_;
		_tmp114_ = _section_list;
		_tmp115_ = vala_collection_get_size ((ValaCollection*) _tmp114_);
		_tmp116_ = _tmp115_;
		_section_size = _tmp116_;
		_section_index = -1;
		while (TRUE) {
			gint _tmp117_;
			gint _tmp118_;
			gint _tmp119_;
			ValaList* _tmp120_;
			gint _tmp121_;
			gpointer _tmp122_ = NULL;
			ValaSwitchSection* section;
			ValaSwitchSection* _tmp123_;
			gboolean _tmp124_ = FALSE;
			ValaCCodeBinaryExpression* cor;
			gint _tmp186_;
			ValaCCodeFunction* _tmp193_;
			ValaCCodeFunction* _tmp194_;
			ValaCCodeConstant* _tmp195_;
			ValaCCodeConstant* _tmp196_;
			ValaCCodeFunction* _tmp197_;
			ValaCCodeFunction* _tmp198_;
			ValaSwitchSection* _tmp199_;
			ValaCCodeFunction* _tmp200_;
			ValaCCodeFunction* _tmp201_;
			gint _tmp202_;
			_tmp117_ = _section_index;
			_section_index = _tmp117_ + 1;
			_tmp118_ = _section_index;
			_tmp119_ = _section_size;
			if (!(_tmp118_ < _tmp119_)) {
				break;
			}
			_tmp120_ = _section_list;
			_tmp121_ = _section_index;
			_tmp122_ = vala_list_get (_tmp120_, _tmp121_);
			section = (ValaSwitchSection*) _tmp122_;
			_tmp123_ = section;
			_tmp124_ = vala_switch_section_has_default_label (_tmp123_);
			if (_tmp124_) {
				ValaSwitchSection* _tmp125_;
				ValaSwitchSection* _tmp126_;
				_tmp125_ = section;
				_tmp126_ = _vala_code_node_ref0 (_tmp125_);
				_vala_code_node_unref0 (default_section);
				default_section = _tmp126_;
				_vala_code_node_unref0 (section);
				continue;
			}
			cor = NULL;
			{
				ValaSwitchSection* _tmp127_;
				ValaList* _tmp128_ = NULL;
				ValaList* _label_list;
				ValaList* _tmp129_;
				gint _tmp130_;
				gint _tmp131_;
				gint _label_size;
				gint _label_index;
				_tmp127_ = section;
				_tmp128_ = vala_switch_section_get_labels (_tmp127_);
				_label_list = _tmp128_;
				_tmp129_ = _label_list;
				_tmp130_ = vala_collection_get_size ((ValaCollection*) _tmp129_);
				_tmp131_ = _tmp130_;
				_label_size = _tmp131_;
				_label_index = -1;
				while (TRUE) {
					gint _tmp132_;
					gint _tmp133_;
					gint _tmp134_;
					ValaList* _tmp135_;
					gint _tmp136_;
					gpointer _tmp137_ = NULL;
					ValaSwitchLabel* label;
					ValaSwitchLabel* _tmp138_;
					ValaExpression* _tmp139_;
					ValaExpression* _tmp140_;
					ValaSwitchLabel* _tmp141_;
					ValaExpression* _tmp142_;
					ValaExpression* _tmp143_;
					ValaCCodeExpression* _tmp144_ = NULL;
					ValaCCodeExpression* cexpr;
					ValaCCodeExpression* _tmp145_;
					gboolean _tmp146_ = FALSE;
					ValaCCodeExpression* _tmp177_;
					ValaCCodeExpression* _tmp178_;
					ValaCCodeBinaryExpression* _tmp179_;
					ValaCCodeBinaryExpression* ccmp;
					ValaCCodeBinaryExpression* _tmp180_;
					_tmp132_ = _label_index;
					_label_index = _tmp132_ + 1;
					_tmp133_ = _label_index;
					_tmp134_ = _label_size;
					if (!(_tmp133_ < _tmp134_)) {
						break;
					}
					_tmp135_ = _label_list;
					_tmp136_ = _label_index;
					_tmp137_ = vala_list_get (_tmp135_, _tmp136_);
					label = (ValaSwitchLabel*) _tmp137_;
					_tmp138_ = label;
					_tmp139_ = vala_switch_label_get_expression (_tmp138_);
					_tmp140_ = _tmp139_;
					vala_code_node_emit ((ValaCodeNode*) _tmp140_, (ValaCodeGenerator*) self);
					_tmp141_ = label;
					_tmp142_ = vala_switch_label_get_expression (_tmp141_);
					_tmp143_ = _tmp142_;
					_tmp144_ = vala_ccode_base_module_get_cvalue ((ValaCCodeBaseModule*) self, _tmp143_);
					cexpr = _tmp144_;
					_tmp145_ = cexpr;
					_tmp146_ = vala_ccode_base_module_is_constant_ccode_expression ((ValaCCodeBaseModule*) self, _tmp145_);
					if (_tmp146_) {
						gint _tmp147_;
						gint _tmp148_;
						gchar* _tmp149_ = NULL;
						gchar* _tmp150_;
						ValaCCodeIdentifier* _tmp151_;
						ValaCCodeIdentifier* _tmp152_;
						ValaCCodeIdentifier* cname;
						ValaCCodeConstant* _tmp153_;
						ValaCCodeIdentifier* _tmp154_;
						ValaCCodeBinaryExpression* _tmp155_;
						ValaCCodeBinaryExpression* ccondition;
						ValaCCodeIdentifier* _tmp156_;
						ValaCCodeIdentifier* _tmp157_;
						ValaCCodeFunctionCall* _tmp158_;
						ValaCCodeFunctionCall* _tmp159_;
						ValaCCodeFunctionCall* ccall;
						ValaCCodeIdentifier* _tmp160_;
						ValaCCodeFunctionCall* _tmp161_;
						ValaCCodeAssignment* _tmp162_;
						ValaCCodeFunctionCall* _tmp163_;
						ValaCCodeExpression* _tmp164_;
						ValaCCodeBinaryExpression* _tmp165_;
						ValaCCodeIdentifier* _tmp166_;
						ValaCCodeAssignment* _tmp167_;
						ValaCCodeConditionalExpression* _tmp168_;
						_tmp147_ = label_temp_id;
						_tmp148_ = label_count;
						label_count = _tmp148_ + 1;
						_tmp149_ = g_strdup_printf ("_tmp%d_label%d", _tmp147_, _tmp148_);
						_tmp150_ = _tmp149_;
						_tmp151_ = vala_ccode_identifier_new (_tmp150_);
						_tmp152_ = _tmp151_;
						_g_free0 (_tmp150_);
						cname = _tmp152_;
						_tmp153_ = czero;
						_tmp154_ = cname;
						_tmp155_ = vala_ccode_binary_expression_new (VALA_CCODE_BINARY_OPERATOR_INEQUALITY, (ValaCCodeExpression*) _tmp153_, (ValaCCodeExpression*) _tmp154_);
						ccondition = _tmp155_;
						_tmp156_ = vala_ccode_identifier_new ("g_quark_from_static_string");
						_tmp157_ = _tmp156_;
						_tmp158_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp157_);
						_tmp159_ = _tmp158_;
						_vala_ccode_node_unref0 (_tmp157_);
						ccall = _tmp159_;
						_tmp160_ = cname;
						_tmp161_ = ccall;
						_tmp162_ = vala_ccode_assignment_new ((ValaCCodeExpression*) _tmp160_, (ValaCCodeExpression*) _tmp161_, VALA_CCODE_ASSIGNMENT_OPERATOR_SIMPLE);
						_vala_ccode_node_unref0 (cinit);
						cinit = _tmp162_;
						_tmp163_ = ccall;
						_tmp164_ = cexpr;
						vala_ccode_function_call_add_argument (_tmp163_, _tmp164_);
						_tmp165_ = ccondition;
						_tmp166_ = cname;
						_tmp167_ = cinit;
						_tmp168_ = vala_ccode_conditional_expression_new ((ValaCCodeExpression*) _tmp165_, (ValaCCodeExpression*) _tmp166_, (ValaCCodeExpression*) _tmp167_);
						_vala_ccode_node_unref0 (cexpr);
						cexpr = (ValaCCodeExpression*) _tmp168_;
						_vala_ccode_node_unref0 (ccall);
						_vala_ccode_node_unref0 (ccondition);
						_vala_ccode_node_unref0 (cname);
					} else {
						ValaCCodeIdentifier* _tmp169_;
						ValaCCodeIdentifier* _tmp170_;
						ValaCCodeFunctionCall* _tmp171_;
						ValaCCodeFunctionCall* _tmp172_;
						ValaCCodeFunctionCall* ccall;
						ValaCCodeFunctionCall* _tmp173_;
						ValaCCodeExpression* _tmp174_;
						ValaCCodeFunctionCall* _tmp175_;
						ValaCCodeExpression* _tmp176_;
						_tmp169_ = vala_ccode_identifier_new ("g_quark_from_string");
						_tmp170_ = _tmp169_;
						_tmp171_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp170_);
						_tmp172_ = _tmp171_;
						_vala_ccode_node_unref0 (_tmp170_);
						ccall = _tmp172_;
						_tmp173_ = ccall;
						_tmp174_ = cexpr;
						vala_ccode_function_call_add_argument (_tmp173_, _tmp174_);
						_tmp175_ = ccall;
						_tmp176_ = _vala_ccode_node_ref0 ((ValaCCodeExpression*) _tmp175_);
						_vala_ccode_node_unref0 (cexpr);
						cexpr = _tmp176_;
						_vala_ccode_node_unref0 (ccall);
					}
					_tmp177_ = ctemp;
					_tmp178_ = cexpr;
					_tmp179_ = vala_ccode_binary_expression_new (VALA_CCODE_BINARY_OPERATOR_EQUALITY, _tmp177_, _tmp178_);
					ccmp = _tmp179_;
					_tmp180_ = cor;
					if (_tmp180_ == NULL) {
						ValaCCodeBinaryExpression* _tmp181_;
						ValaCCodeBinaryExpression* _tmp182_;
						_tmp181_ = ccmp;
						_tmp182_ = _vala_ccode_node_ref0 (_tmp181_);
						_vala_ccode_node_unref0 (cor);
						cor = _tmp182_;
					} else {
						ValaCCodeBinaryExpression* _tmp183_;
						ValaCCodeBinaryExpression* _tmp184_;
						ValaCCodeBinaryExpression* _tmp185_;
						_tmp183_ = cor;
						_tmp184_ = ccmp;
						_tmp185_ = vala_ccode_binary_expression_new (VALA_CCODE_BINARY_OPERATOR_OR, (ValaCCodeExpression*) _tmp183_, (ValaCCodeExpression*) _tmp184_);
						_vala_ccode_node_unref0 (cor);
						cor = _tmp185_;
					}
					_vala_ccode_node_unref0 (ccmp);
					_vala_ccode_node_unref0 (cexpr);
					_vala_code_node_unref0 (label);
				}
				_vala_iterable_unref0 (_label_list);
			}
			_tmp186_ = n;
			if (_tmp186_ > 0) {
				ValaCCodeFunction* _tmp187_;
				ValaCCodeFunction* _tmp188_;
				ValaCCodeBinaryExpression* _tmp189_;
				_tmp187_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
				_tmp188_ = _tmp187_;
				_tmp189_ = cor;
				vala_ccode_function_else_if (_tmp188_, (ValaCCodeExpression*) _tmp189_);
			} else {
				ValaCCodeFunction* _tmp190_;
				ValaCCodeFunction* _tmp191_;
				ValaCCodeBinaryExpression* _tmp192_;
				_tmp190_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
				_tmp191_ = _tmp190_;
				_tmp192_ = cor;
				vala_ccode_function_open_if (_tmp191_, (ValaCCodeExpression*) _tmp192_);
			}
			_tmp193_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
			_tmp194_ = _tmp193_;
			_tmp195_ = vala_ccode_constant_new ("0");
			_tmp196_ = _tmp195_;
			vala_ccode_function_open_switch (_tmp194_, (ValaCCodeExpression*) _tmp196_);
			_vala_ccode_node_unref0 (_tmp196_);
			_tmp197_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
			_tmp198_ = _tmp197_;
			vala_ccode_function_add_default (_tmp198_);
			_tmp199_ = section;
			vala_code_node_emit ((ValaCodeNode*) _tmp199_, (ValaCodeGenerator*) self);
			_tmp200_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
			_tmp201_ = _tmp200_;
			vala_ccode_function_close (_tmp201_);
			_tmp202_ = n;
			n = _tmp202_ + 1;
			_vala_ccode_node_unref0 (cor);
			_vala_code_node_unref0 (section);
		}
		_vala_iterable_unref0 (_section_list);
	}
	_tmp203_ = default_section;
	if (_tmp203_ != NULL) {
		gint _tmp204_;
		ValaCCodeFunction* _tmp207_;
		ValaCCodeFunction* _tmp208_;
		ValaCCodeConstant* _tmp209_;
		ValaCCodeConstant* _tmp210_;
		ValaCCodeFunction* _tmp211_;
		ValaCCodeFunction* _tmp212_;
		ValaSwitchSection* _tmp213_;
		ValaCCodeFunction* _tmp214_;
		ValaCCodeFunction* _tmp215_;
		_tmp204_ = n;
		if (_tmp204_ > 0) {
			ValaCCodeFunction* _tmp205_;
			ValaCCodeFunction* _tmp206_;
			_tmp205_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
			_tmp206_ = _tmp205_;
			vala_ccode_function_add_else (_tmp206_);
		}
		_tmp207_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp208_ = _tmp207_;
		_tmp209_ = vala_ccode_constant_new ("0");
		_tmp210_ = _tmp209_;
		vala_ccode_function_open_switch (_tmp208_, (ValaCCodeExpression*) _tmp210_);
		_vala_ccode_node_unref0 (_tmp210_);
		_tmp211_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp212_ = _tmp211_;
		vala_ccode_function_add_default (_tmp212_);
		_tmp213_ = default_section;
		vala_code_node_emit ((ValaCodeNode*) _tmp213_, (ValaCodeGenerator*) self);
		_tmp214_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp215_ = _tmp214_;
		vala_ccode_function_close (_tmp215_);
	}
	_tmp216_ = n;
	if (_tmp216_ > 0) {
		ValaCCodeFunction* _tmp217_;
		ValaCCodeFunction* _tmp218_;
		_tmp217_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp218_ = _tmp217_;
		vala_ccode_function_close (_tmp218_);
	}
	_vala_code_node_unref0 (default_section);
	_vala_ccode_node_unref0 (ccond);
	_vala_ccode_node_unref0 (cquark);
	_vala_ccode_node_unref0 (cisnull);
	_vala_ccode_node_unref0 (free_call);
	_vala_ccode_node_unref0 (czero);
	_vala_ccode_node_unref0 (cinit);
	_vala_ccode_node_unref0 (ctemp);
	_vala_target_value_unref0 (temp_value);
}


static void vala_ccode_control_flow_module_real_visit_switch_statement (ValaCodeVisitor* base, ValaSwitchStatement* stmt) {
	ValaCCodeControlFlowModule * self;
	ValaSwitchStatement* _tmp0_;
	ValaExpression* _tmp1_;
	ValaExpression* _tmp2_;
	ValaDataType* _tmp3_;
	ValaDataType* _tmp4_;
	ValaDataType* _tmp5_;
	gboolean _tmp6_ = FALSE;
	ValaCCodeFunction* _tmp8_;
	ValaCCodeFunction* _tmp9_;
	ValaSwitchStatement* _tmp10_;
	ValaExpression* _tmp11_;
	ValaExpression* _tmp12_;
	ValaCCodeExpression* _tmp13_ = NULL;
	ValaCCodeExpression* _tmp14_;
	gboolean has_default;
	gboolean _tmp31_;
	ValaCCodeFunction* _tmp36_;
	ValaCCodeFunction* _tmp37_;
	self = (ValaCCodeControlFlowModule*) base;
	g_return_if_fail (stmt != NULL);
	_tmp0_ = stmt;
	_tmp1_ = vala_switch_statement_get_expression (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = vala_expression_get_value_type (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = ((ValaCCodeBaseModule*) self)->string_type;
	_tmp6_ = vala_data_type_compatible (_tmp4_, _tmp5_);
	if (_tmp6_) {
		ValaSwitchStatement* _tmp7_;
		_tmp7_ = stmt;
		vala_ccode_control_flow_module_visit_string_switch_statement (self, _tmp7_);
		return;
	}
	_tmp8_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp9_ = _tmp8_;
	_tmp10_ = stmt;
	_tmp11_ = vala_switch_statement_get_expression (_tmp10_);
	_tmp12_ = _tmp11_;
	_tmp13_ = vala_ccode_base_module_get_cvalue ((ValaCCodeBaseModule*) self, _tmp12_);
	_tmp14_ = _tmp13_;
	vala_ccode_function_open_switch (_tmp9_, _tmp14_);
	_vala_ccode_node_unref0 (_tmp14_);
	has_default = FALSE;
	{
		ValaSwitchStatement* _tmp15_;
		ValaList* _tmp16_ = NULL;
		ValaList* _section_list;
		ValaList* _tmp17_;
		gint _tmp18_;
		gint _tmp19_;
		gint _section_size;
		gint _section_index;
		_tmp15_ = stmt;
		_tmp16_ = vala_switch_statement_get_sections (_tmp15_);
		_section_list = _tmp16_;
		_tmp17_ = _section_list;
		_tmp18_ = vala_collection_get_size ((ValaCollection*) _tmp17_);
		_tmp19_ = _tmp18_;
		_section_size = _tmp19_;
		_section_index = -1;
		while (TRUE) {
			gint _tmp20_;
			gint _tmp21_;
			gint _tmp22_;
			ValaList* _tmp23_;
			gint _tmp24_;
			gpointer _tmp25_ = NULL;
			ValaSwitchSection* section;
			ValaSwitchSection* _tmp26_;
			gboolean _tmp27_ = FALSE;
			ValaSwitchSection* _tmp30_;
			_tmp20_ = _section_index;
			_section_index = _tmp20_ + 1;
			_tmp21_ = _section_index;
			_tmp22_ = _section_size;
			if (!(_tmp21_ < _tmp22_)) {
				break;
			}
			_tmp23_ = _section_list;
			_tmp24_ = _section_index;
			_tmp25_ = vala_list_get (_tmp23_, _tmp24_);
			section = (ValaSwitchSection*) _tmp25_;
			_tmp26_ = section;
			_tmp27_ = vala_switch_section_has_default_label (_tmp26_);
			if (_tmp27_) {
				ValaCCodeFunction* _tmp28_;
				ValaCCodeFunction* _tmp29_;
				_tmp28_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
				_tmp29_ = _tmp28_;
				vala_ccode_function_add_default (_tmp29_);
				has_default = TRUE;
			}
			_tmp30_ = section;
			vala_code_node_emit ((ValaCodeNode*) _tmp30_, (ValaCodeGenerator*) self);
			_vala_code_node_unref0 (section);
		}
		_vala_iterable_unref0 (_section_list);
	}
	_tmp31_ = has_default;
	if (!_tmp31_) {
		ValaCCodeFunction* _tmp32_;
		ValaCCodeFunction* _tmp33_;
		ValaCCodeFunction* _tmp34_;
		ValaCCodeFunction* _tmp35_;
		_tmp32_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp33_ = _tmp32_;
		vala_ccode_function_add_default (_tmp33_);
		_tmp34_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp35_ = _tmp34_;
		vala_ccode_function_add_break (_tmp35_);
	}
	_tmp36_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp37_ = _tmp36_;
	vala_ccode_function_close (_tmp37_);
}


static void vala_ccode_control_flow_module_real_visit_switch_label (ValaCodeVisitor* base, ValaSwitchLabel* label) {
	ValaCCodeControlFlowModule * self;
	ValaSwitchLabel* _tmp0_;
	ValaSwitchSection* _tmp1_;
	ValaSwitchSection* _tmp2_;
	ValaCodeNode* _tmp3_;
	ValaCodeNode* _tmp4_;
	ValaExpression* _tmp5_;
	ValaExpression* _tmp6_;
	ValaDataType* _tmp7_;
	ValaDataType* _tmp8_;
	ValaDataType* _tmp9_;
	gboolean _tmp10_ = FALSE;
	ValaSwitchLabel* _tmp11_;
	ValaExpression* _tmp12_;
	ValaExpression* _tmp13_;
	self = (ValaCCodeControlFlowModule*) base;
	g_return_if_fail (label != NULL);
	_tmp0_ = label;
	_tmp1_ = vala_switch_label_get_section (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = vala_code_node_get_parent_node ((ValaCodeNode*) _tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = vala_switch_statement_get_expression (G_TYPE_CHECK_INSTANCE_CAST (_tmp4_, VALA_TYPE_SWITCH_STATEMENT, ValaSwitchStatement));
	_tmp6_ = _tmp5_;
	_tmp7_ = vala_expression_get_value_type (_tmp6_);
	_tmp8_ = _tmp7_;
	_tmp9_ = ((ValaCCodeBaseModule*) self)->string_type;
	_tmp10_ = vala_data_type_compatible (_tmp8_, _tmp9_);
	if (_tmp10_) {
		return;
	}
	_tmp11_ = label;
	_tmp12_ = vala_switch_label_get_expression (_tmp11_);
	_tmp13_ = _tmp12_;
	if (_tmp13_ != NULL) {
		ValaSwitchLabel* _tmp14_;
		ValaExpression* _tmp15_;
		ValaExpression* _tmp16_;
		ValaSwitchLabel* _tmp17_;
		ValaExpression* _tmp18_;
		ValaExpression* _tmp19_;
		ValaCCodeFunction* _tmp20_;
		ValaCCodeFunction* _tmp21_;
		ValaSwitchLabel* _tmp22_;
		ValaExpression* _tmp23_;
		ValaExpression* _tmp24_;
		ValaCCodeExpression* _tmp25_ = NULL;
		ValaCCodeExpression* _tmp26_;
		_tmp14_ = label;
		_tmp15_ = vala_switch_label_get_expression (_tmp14_);
		_tmp16_ = _tmp15_;
		vala_code_node_emit ((ValaCodeNode*) _tmp16_, (ValaCodeGenerator*) self);
		_tmp17_ = label;
		_tmp18_ = vala_switch_label_get_expression (_tmp17_);
		_tmp19_ = _tmp18_;
		vala_code_visitor_visit_end_full_expression ((ValaCodeVisitor*) self, _tmp19_);
		_tmp20_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp21_ = _tmp20_;
		_tmp22_ = label;
		_tmp23_ = vala_switch_label_get_expression (_tmp22_);
		_tmp24_ = _tmp23_;
		_tmp25_ = vala_ccode_base_module_get_cvalue ((ValaCCodeBaseModule*) self, _tmp24_);
		_tmp26_ = _tmp25_;
		vala_ccode_function_add_case (_tmp21_, _tmp26_);
		_vala_ccode_node_unref0 (_tmp26_);
	}
}


static void vala_ccode_control_flow_module_real_visit_loop (ValaCodeVisitor* base, ValaLoop* stmt) {
	ValaCCodeControlFlowModule * self;
	ValaCCodeFunction* _tmp0_;
	ValaCCodeFunction* _tmp1_;
	ValaCCodeConstant* _tmp2_;
	ValaCCodeConstant* _tmp3_;
	ValaLoop* _tmp4_;
	ValaBlock* _tmp5_;
	ValaBlock* _tmp6_;
	ValaCCodeFunction* _tmp7_;
	ValaCCodeFunction* _tmp8_;
	self = (ValaCCodeControlFlowModule*) base;
	g_return_if_fail (stmt != NULL);
	_tmp0_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = vala_ccode_constant_new ("TRUE");
	_tmp3_ = _tmp2_;
	vala_ccode_function_open_while (_tmp1_, (ValaCCodeExpression*) _tmp3_);
	_vala_ccode_node_unref0 (_tmp3_);
	_tmp4_ = stmt;
	_tmp5_ = vala_loop_get_body (_tmp4_);
	_tmp6_ = _tmp5_;
	vala_code_node_emit ((ValaCodeNode*) _tmp6_, (ValaCodeGenerator*) self);
	_tmp7_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp8_ = _tmp7_;
	vala_ccode_function_close (_tmp8_);
}


static void vala_ccode_control_flow_module_real_visit_foreach_statement (ValaCodeVisitor* base, ValaForeachStatement* stmt) {
	ValaCCodeControlFlowModule * self;
	ValaCCodeFunction* _tmp0_;
	ValaCCodeFunction* _tmp1_;
	ValaForeachStatement* _tmp2_;
	ValaLocalVariable* _tmp3_;
	ValaLocalVariable* _tmp4_;
	ValaLocalVariable* _tmp5_;
	ValaLocalVariable* collection_backup;
	ValaLocalVariable* _tmp6_;
	ValaDataType* _tmp7_;
	ValaDataType* _tmp8_;
	ValaDataType* _tmp9_;
	ValaDataType* collection_type;
	ValaDataType* _tmp10_;
	ValaArrayType* _tmp11_;
	ValaArrayType* array_type;
	ValaArrayType* _tmp12_;
	ValaLocalVariable* _tmp15_;
	ValaCCodeFunction* _tmp16_;
	ValaCCodeFunction* _tmp17_;
	ValaLocalVariable* _tmp18_;
	gchar* _tmp19_ = NULL;
	gchar* _tmp20_;
	ValaCCodeExpression* _tmp21_ = NULL;
	ValaCCodeExpression* _tmp22_;
	ValaForeachStatement* _tmp23_;
	ValaExpression* _tmp24_;
	ValaExpression* _tmp25_;
	ValaCCodeExpression* _tmp26_ = NULL;
	ValaCCodeExpression* _tmp27_;
	gboolean _tmp28_ = FALSE;
	ValaForeachStatement* _tmp29_;
	gboolean _tmp30_;
	gboolean _tmp31_;
	gboolean _tmp37_;
	ValaForeachStatement* _tmp41_;
	ValaExpression* _tmp42_;
	ValaExpression* _tmp43_;
	ValaDataType* _tmp44_;
	ValaDataType* _tmp45_;
	ValaCCodeFunction* _tmp429_;
	ValaCCodeFunction* _tmp430_;
	self = (ValaCCodeControlFlowModule*) base;
	g_return_if_fail (stmt != NULL);
	_tmp0_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp1_ = _tmp0_;
	vala_ccode_function_open_block (_tmp1_);
	_tmp2_ = stmt;
	_tmp3_ = vala_foreach_statement_get_collection_variable (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = _vala_code_node_ref0 (_tmp4_);
	collection_backup = _tmp5_;
	_tmp6_ = collection_backup;
	_tmp7_ = vala_variable_get_variable_type ((ValaVariable*) _tmp6_);
	_tmp8_ = _tmp7_;
	_tmp9_ = _vala_code_node_ref0 (_tmp8_);
	collection_type = _tmp9_;
	_tmp10_ = collection_type;
	_tmp11_ = _vala_code_node_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp10_, VALA_TYPE_ARRAY_TYPE) ? ((ValaArrayType*) _tmp10_) : NULL);
	array_type = _tmp11_;
	_tmp12_ = array_type;
	if (_tmp12_ != NULL) {
		ValaArrayType* _tmp13_;
		ValaArrayType* _tmp14_;
		_tmp13_ = array_type;
		vala_array_type_set_inline_allocated (_tmp13_, FALSE);
		_tmp14_ = array_type;
		vala_array_type_set_fixed_length (_tmp14_, FALSE);
	}
	_tmp15_ = collection_backup;
	vala_code_visitor_visit_local_variable ((ValaCodeVisitor*) self, _tmp15_);
	_tmp16_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp17_ = _tmp16_;
	_tmp18_ = collection_backup;
	_tmp19_ = vala_ccode_base_module_get_local_cname ((ValaCCodeBaseModule*) self, _tmp18_);
	_tmp20_ = _tmp19_;
	_tmp21_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp20_);
	_tmp22_ = _tmp21_;
	_tmp23_ = stmt;
	_tmp24_ = vala_foreach_statement_get_collection (_tmp23_);
	_tmp25_ = _tmp24_;
	_tmp26_ = vala_ccode_base_module_get_cvalue ((ValaCCodeBaseModule*) self, _tmp25_);
	_tmp27_ = _tmp26_;
	vala_ccode_function_add_assignment (_tmp17_, _tmp22_, _tmp27_);
	_vala_ccode_node_unref0 (_tmp27_);
	_vala_ccode_node_unref0 (_tmp22_);
	_g_free0 (_tmp20_);
	_tmp29_ = stmt;
	_tmp30_ = vala_code_node_get_tree_can_fail ((ValaCodeNode*) _tmp29_);
	_tmp31_ = _tmp30_;
	if (_tmp31_) {
		ValaForeachStatement* _tmp32_;
		ValaExpression* _tmp33_;
		ValaExpression* _tmp34_;
		gboolean _tmp35_;
		gboolean _tmp36_;
		_tmp32_ = stmt;
		_tmp33_ = vala_foreach_statement_get_collection (_tmp32_);
		_tmp34_ = _tmp33_;
		_tmp35_ = vala_code_node_get_tree_can_fail ((ValaCodeNode*) _tmp34_);
		_tmp36_ = _tmp35_;
		_tmp28_ = _tmp36_;
	} else {
		_tmp28_ = FALSE;
	}
	_tmp37_ = _tmp28_;
	if (_tmp37_) {
		ValaForeachStatement* _tmp38_;
		ValaExpression* _tmp39_;
		ValaExpression* _tmp40_;
		_tmp38_ = stmt;
		_tmp39_ = vala_foreach_statement_get_collection (_tmp38_);
		_tmp40_ = _tmp39_;
		vala_ccode_base_module_add_simple_check ((ValaCCodeBaseModule*) self, (ValaCodeNode*) _tmp40_, FALSE);
	}
	_tmp41_ = stmt;
	_tmp42_ = vala_foreach_statement_get_collection (_tmp41_);
	_tmp43_ = _tmp42_;
	_tmp44_ = vala_expression_get_value_type (_tmp43_);
	_tmp45_ = _tmp44_;
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp45_, VALA_TYPE_ARRAY_TYPE)) {
		ValaForeachStatement* _tmp46_;
		ValaExpression* _tmp47_;
		ValaExpression* _tmp48_;
		ValaDataType* _tmp49_;
		ValaDataType* _tmp50_;
		ValaArrayType* _tmp51_;
		ValaForeachStatement* _tmp52_;
		ValaExpression* _tmp53_;
		ValaExpression* _tmp54_;
		ValaCCodeExpression* _tmp55_ = NULL;
		ValaCCodeExpression* array_len;
		ValaCCodeFunction* _tmp56_;
		ValaCCodeFunction* _tmp57_;
		ValaLocalVariable* _tmp58_;
		gchar* _tmp59_ = NULL;
		gchar* _tmp60_;
		gchar* _tmp61_ = NULL;
		gchar* _tmp62_;
		ValaCCodeExpression* _tmp63_ = NULL;
		ValaCCodeExpression* _tmp64_;
		ValaCCodeExpression* _tmp65_;
		ValaDataType* _tmp66_;
		ValaDataType* _tmp67_ = NULL;
		ValaDataType* _tmp68_;
		ValaForeachStatement* _tmp69_;
		const gchar* _tmp70_;
		const gchar* _tmp71_;
		gchar* _tmp72_;
		gchar* _tmp73_;
		ValaLocalVariable* _tmp74_;
		ValaLocalVariable* _tmp75_;
		ValaLocalVariable* iterator_variable;
		ValaLocalVariable* _tmp76_;
		ValaLocalVariable* _tmp77_;
		gchar* _tmp78_ = NULL;
		gchar* it_name;
		const gchar* _tmp79_;
		ValaCCodeExpression* _tmp80_ = NULL;
		ValaCCodeExpression* _tmp81_;
		ValaCCodeExpression* _tmp82_;
		ValaCCodeBinaryExpression* _tmp83_;
		ValaCCodeBinaryExpression* _tmp84_;
		ValaCCodeBinaryExpression* ccond;
		ValaCCodeFunction* _tmp85_;
		ValaCCodeFunction* _tmp86_;
		const gchar* _tmp87_;
		ValaCCodeExpression* _tmp88_ = NULL;
		ValaCCodeExpression* _tmp89_;
		ValaCCodeConstant* _tmp90_;
		ValaCCodeConstant* _tmp91_;
		ValaCCodeAssignment* _tmp92_;
		ValaCCodeAssignment* _tmp93_;
		ValaCCodeBinaryExpression* _tmp94_;
		const gchar* _tmp95_;
		ValaCCodeExpression* _tmp96_ = NULL;
		ValaCCodeExpression* _tmp97_;
		const gchar* _tmp98_;
		ValaCCodeExpression* _tmp99_ = NULL;
		ValaCCodeExpression* _tmp100_;
		ValaCCodeConstant* _tmp101_;
		ValaCCodeConstant* _tmp102_;
		ValaCCodeBinaryExpression* _tmp103_;
		ValaCCodeBinaryExpression* _tmp104_;
		ValaCCodeAssignment* _tmp105_;
		ValaCCodeAssignment* _tmp106_;
		ValaLocalVariable* _tmp107_;
		gchar* _tmp108_ = NULL;
		gchar* _tmp109_;
		ValaCCodeExpression* _tmp110_ = NULL;
		ValaCCodeExpression* _tmp111_;
		const gchar* _tmp112_;
		ValaCCodeExpression* _tmp113_ = NULL;
		ValaCCodeExpression* _tmp114_;
		ValaCCodeElementAccess* _tmp115_;
		ValaCCodeExpression* _tmp116_;
		ValaCCodeExpression* element_expr;
		ValaArrayType* _tmp117_;
		ValaDataType* _tmp118_;
		ValaDataType* _tmp119_;
		ValaDataType* _tmp120_ = NULL;
		ValaDataType* element_type;
		ValaDataType* _tmp121_;
		ValaDataType* _tmp122_;
		ValaCCodeExpression* _tmp123_;
		ValaGLibValue* _tmp124_;
		ValaGLibValue* _tmp125_;
		ValaForeachStatement* _tmp126_;
		ValaDataType* _tmp127_;
		ValaDataType* _tmp128_;
		ValaForeachStatement* _tmp129_;
		ValaTargetValue* _tmp130_ = NULL;
		ValaTargetValue* _tmp131_;
		ValaCCodeExpression* _tmp132_ = NULL;
		ValaForeachStatement* _tmp133_;
		ValaLocalVariable* _tmp134_;
		ValaLocalVariable* _tmp135_;
		ValaCCodeFunction* _tmp136_;
		ValaCCodeFunction* _tmp137_;
		ValaForeachStatement* _tmp138_;
		ValaLocalVariable* _tmp139_;
		ValaLocalVariable* _tmp140_;
		gchar* _tmp141_ = NULL;
		gchar* _tmp142_;
		ValaCCodeExpression* _tmp143_ = NULL;
		ValaCCodeExpression* _tmp144_;
		ValaCCodeExpression* _tmp145_;
		ValaForeachStatement* _tmp146_;
		ValaDataType* _tmp147_;
		ValaDataType* _tmp148_;
		ValaForeachStatement* _tmp174_;
		ValaBlock* _tmp175_;
		ValaBlock* _tmp176_;
		ValaCCodeFunction* _tmp177_;
		ValaCCodeFunction* _tmp178_;
		_tmp46_ = stmt;
		_tmp47_ = vala_foreach_statement_get_collection (_tmp46_);
		_tmp48_ = _tmp47_;
		_tmp49_ = vala_expression_get_value_type (_tmp48_);
		_tmp50_ = _tmp49_;
		_tmp51_ = _vala_code_node_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp50_, VALA_TYPE_ARRAY_TYPE, ValaArrayType));
		_vala_code_node_unref0 (array_type);
		array_type = _tmp51_;
		_tmp52_ = stmt;
		_tmp53_ = vala_foreach_statement_get_collection (_tmp52_);
		_tmp54_ = _tmp53_;
		_tmp55_ = vala_ccode_base_module_get_array_length_cexpression ((ValaCCodeBaseModule*) self, _tmp54_, -1);
		array_len = _tmp55_;
		_tmp56_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp57_ = _tmp56_;
		_tmp58_ = collection_backup;
		_tmp59_ = vala_ccode_base_module_get_local_cname ((ValaCCodeBaseModule*) self, _tmp58_);
		_tmp60_ = _tmp59_;
		_tmp61_ = vala_ccode_base_module_get_array_length_cname ((ValaCCodeBaseModule*) self, _tmp60_, 1);
		_tmp62_ = _tmp61_;
		_tmp63_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp62_);
		_tmp64_ = _tmp63_;
		_tmp65_ = array_len;
		vala_ccode_function_add_assignment (_tmp57_, _tmp64_, _tmp65_);
		_vala_ccode_node_unref0 (_tmp64_);
		_g_free0 (_tmp62_);
		_g_free0 (_tmp60_);
		_tmp66_ = ((ValaCCodeBaseModule*) self)->int_type;
		_tmp67_ = vala_data_type_copy (_tmp66_);
		_tmp68_ = _tmp67_;
		_tmp69_ = stmt;
		_tmp70_ = vala_foreach_statement_get_variable_name (_tmp69_);
		_tmp71_ = _tmp70_;
		_tmp72_ = g_strconcat (_tmp71_, "_it", NULL);
		_tmp73_ = _tmp72_;
		_tmp74_ = vala_local_variable_new (_tmp68_, _tmp73_, NULL, NULL);
		_tmp75_ = _tmp74_;
		_g_free0 (_tmp73_);
		_vala_code_node_unref0 (_tmp68_);
		iterator_variable = _tmp75_;
		_tmp76_ = iterator_variable;
		vala_code_visitor_visit_local_variable ((ValaCodeVisitor*) self, _tmp76_);
		_tmp77_ = iterator_variable;
		_tmp78_ = vala_ccode_base_module_get_local_cname ((ValaCCodeBaseModule*) self, _tmp77_);
		it_name = _tmp78_;
		_tmp79_ = it_name;
		_tmp80_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp79_);
		_tmp81_ = _tmp80_;
		_tmp82_ = array_len;
		_tmp83_ = vala_ccode_binary_expression_new (VALA_CCODE_BINARY_OPERATOR_LESS_THAN, _tmp81_, _tmp82_);
		_tmp84_ = _tmp83_;
		_vala_ccode_node_unref0 (_tmp81_);
		ccond = _tmp84_;
		_tmp85_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp86_ = _tmp85_;
		_tmp87_ = it_name;
		_tmp88_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp87_);
		_tmp89_ = _tmp88_;
		_tmp90_ = vala_ccode_constant_new ("0");
		_tmp91_ = _tmp90_;
		_tmp92_ = vala_ccode_assignment_new (_tmp89_, (ValaCCodeExpression*) _tmp91_, VALA_CCODE_ASSIGNMENT_OPERATOR_SIMPLE);
		_tmp93_ = _tmp92_;
		_tmp94_ = ccond;
		_tmp95_ = it_name;
		_tmp96_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp95_);
		_tmp97_ = _tmp96_;
		_tmp98_ = it_name;
		_tmp99_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp98_);
		_tmp100_ = _tmp99_;
		_tmp101_ = vala_ccode_constant_new ("1");
		_tmp102_ = _tmp101_;
		_tmp103_ = vala_ccode_binary_expression_new (VALA_CCODE_BINARY_OPERATOR_PLUS, _tmp100_, (ValaCCodeExpression*) _tmp102_);
		_tmp104_ = _tmp103_;
		_tmp105_ = vala_ccode_assignment_new (_tmp97_, (ValaCCodeExpression*) _tmp104_, VALA_CCODE_ASSIGNMENT_OPERATOR_SIMPLE);
		_tmp106_ = _tmp105_;
		vala_ccode_function_open_for (_tmp86_, (ValaCCodeExpression*) _tmp93_, (ValaCCodeExpression*) _tmp94_, (ValaCCodeExpression*) _tmp106_);
		_vala_ccode_node_unref0 (_tmp106_);
		_vala_ccode_node_unref0 (_tmp104_);
		_vala_ccode_node_unref0 (_tmp102_);
		_vala_ccode_node_unref0 (_tmp100_);
		_vala_ccode_node_unref0 (_tmp97_);
		_vala_ccode_node_unref0 (_tmp93_);
		_vala_ccode_node_unref0 (_tmp91_);
		_vala_ccode_node_unref0 (_tmp89_);
		_tmp107_ = collection_backup;
		_tmp108_ = vala_ccode_base_module_get_local_cname ((ValaCCodeBaseModule*) self, _tmp107_);
		_tmp109_ = _tmp108_;
		_tmp110_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp109_);
		_tmp111_ = _tmp110_;
		_tmp112_ = it_name;
		_tmp113_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp112_);
		_tmp114_ = _tmp113_;
		_tmp115_ = vala_ccode_element_access_new (_tmp111_, _tmp114_);
		_tmp116_ = (ValaCCodeExpression*) _tmp115_;
		_vala_ccode_node_unref0 (_tmp114_);
		_vala_ccode_node_unref0 (_tmp111_);
		_g_free0 (_tmp109_);
		element_expr = _tmp116_;
		_tmp117_ = array_type;
		_tmp118_ = vala_array_type_get_element_type (_tmp117_);
		_tmp119_ = _tmp118_;
		_tmp120_ = vala_data_type_copy (_tmp119_);
		element_type = _tmp120_;
		_tmp121_ = element_type;
		vala_data_type_set_value_owned (_tmp121_, FALSE);
		_tmp122_ = element_type;
		_tmp123_ = element_expr;
		_tmp124_ = vala_glib_value_new (_tmp122_, _tmp123_, TRUE);
		_tmp125_ = _tmp124_;
		_tmp126_ = stmt;
		_tmp127_ = vala_foreach_statement_get_type_reference (_tmp126_);
		_tmp128_ = _tmp127_;
		_tmp129_ = stmt;
		_tmp130_ = vala_ccode_base_module_transform_value ((ValaCCodeBaseModule*) self, (ValaTargetValue*) _tmp125_, _tmp128_, (ValaCodeNode*) _tmp129_);
		_tmp131_ = _tmp130_;
		_tmp132_ = vala_ccode_base_module_get_cvalue_ ((ValaCCodeBaseModule*) self, _tmp131_);
		_vala_ccode_node_unref0 (element_expr);
		element_expr = _tmp132_;
		_vala_target_value_unref0 (_tmp131_);
		_vala_target_value_unref0 (_tmp125_);
		_tmp133_ = stmt;
		_tmp134_ = vala_foreach_statement_get_element_variable (_tmp133_);
		_tmp135_ = _tmp134_;
		vala_code_visitor_visit_local_variable ((ValaCodeVisitor*) self, _tmp135_);
		_tmp136_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp137_ = _tmp136_;
		_tmp138_ = stmt;
		_tmp139_ = vala_foreach_statement_get_element_variable (_tmp138_);
		_tmp140_ = _tmp139_;
		_tmp141_ = vala_ccode_base_module_get_local_cname ((ValaCCodeBaseModule*) self, _tmp140_);
		_tmp142_ = _tmp141_;
		_tmp143_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp142_);
		_tmp144_ = _tmp143_;
		_tmp145_ = element_expr;
		vala_ccode_function_add_assignment (_tmp137_, _tmp144_, _tmp145_);
		_vala_ccode_node_unref0 (_tmp144_);
		_g_free0 (_tmp142_);
		_tmp146_ = stmt;
		_tmp147_ = vala_foreach_statement_get_type_reference (_tmp146_);
		_tmp148_ = _tmp147_;
		if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp148_, VALA_TYPE_ARRAY_TYPE)) {
			ValaForeachStatement* _tmp149_;
			ValaDataType* _tmp150_;
			ValaDataType* _tmp151_;
			ValaArrayType* _tmp152_;
			ValaArrayType* inner_array_type;
			_tmp149_ = stmt;
			_tmp150_ = vala_foreach_statement_get_type_reference (_tmp149_);
			_tmp151_ = _tmp150_;
			_tmp152_ = _vala_code_node_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp151_, VALA_TYPE_ARRAY_TYPE, ValaArrayType));
			inner_array_type = _tmp152_;
			{
				gint dim;
				dim = 1;
				{
					gboolean _tmp153_;
					_tmp153_ = TRUE;
					while (TRUE) {
						gboolean _tmp154_;
						gint _tmp156_;
						ValaArrayType* _tmp157_;
						gint _tmp158_;
						gint _tmp159_;
						ValaCCodeFunction* _tmp160_;
						ValaCCodeFunction* _tmp161_;
						ValaForeachStatement* _tmp162_;
						ValaLocalVariable* _tmp163_;
						ValaLocalVariable* _tmp164_;
						gchar* _tmp165_ = NULL;
						gchar* _tmp166_;
						gint _tmp167_;
						gchar* _tmp168_ = NULL;
						gchar* _tmp169_;
						ValaCCodeExpression* _tmp170_ = NULL;
						ValaCCodeExpression* _tmp171_;
						ValaCCodeConstant* _tmp172_;
						ValaCCodeConstant* _tmp173_;
						_tmp154_ = _tmp153_;
						if (!_tmp154_) {
							gint _tmp155_;
							_tmp155_ = dim;
							dim = _tmp155_ + 1;
						}
						_tmp153_ = FALSE;
						_tmp156_ = dim;
						_tmp157_ = inner_array_type;
						_tmp158_ = vala_array_type_get_rank (_tmp157_);
						_tmp159_ = _tmp158_;
						if (!(_tmp156_ <= _tmp159_)) {
							break;
						}
						_tmp160_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
						_tmp161_ = _tmp160_;
						_tmp162_ = stmt;
						_tmp163_ = vala_foreach_statement_get_element_variable (_tmp162_);
						_tmp164_ = _tmp163_;
						_tmp165_ = vala_ccode_base_module_get_local_cname ((ValaCCodeBaseModule*) self, _tmp164_);
						_tmp166_ = _tmp165_;
						_tmp167_ = dim;
						_tmp168_ = vala_ccode_base_module_get_array_length_cname ((ValaCCodeBaseModule*) self, _tmp166_, _tmp167_);
						_tmp169_ = _tmp168_;
						_tmp170_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp169_);
						_tmp171_ = _tmp170_;
						_tmp172_ = vala_ccode_constant_new ("-1");
						_tmp173_ = _tmp172_;
						vala_ccode_function_add_assignment (_tmp161_, _tmp171_, (ValaCCodeExpression*) _tmp173_);
						_vala_ccode_node_unref0 (_tmp173_);
						_vala_ccode_node_unref0 (_tmp171_);
						_g_free0 (_tmp169_);
						_g_free0 (_tmp166_);
					}
				}
			}
			_vala_code_node_unref0 (inner_array_type);
		}
		_tmp174_ = stmt;
		_tmp175_ = vala_foreach_statement_get_body (_tmp174_);
		_tmp176_ = _tmp175_;
		vala_code_node_emit ((ValaCodeNode*) _tmp176_, (ValaCodeGenerator*) self);
		_tmp177_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp178_ = _tmp177_;
		vala_ccode_function_close (_tmp178_);
		_vala_code_node_unref0 (element_type);
		_vala_ccode_node_unref0 (element_expr);
		_vala_ccode_node_unref0 (ccond);
		_g_free0 (it_name);
		_vala_code_node_unref0 (iterator_variable);
		_vala_ccode_node_unref0 (array_len);
	} else {
		gboolean _tmp179_ = FALSE;
		ValaForeachStatement* _tmp180_;
		ValaExpression* _tmp181_;
		ValaExpression* _tmp182_;
		ValaDataType* _tmp183_;
		ValaDataType* _tmp184_;
		ValaClass* _tmp185_;
		ValaObjectType* _tmp186_;
		ValaObjectType* _tmp187_;
		gboolean _tmp188_ = FALSE;
		gboolean _tmp189_;
		gboolean _tmp199_;
		_tmp180_ = stmt;
		_tmp181_ = vala_foreach_statement_get_collection (_tmp180_);
		_tmp182_ = _tmp181_;
		_tmp183_ = vala_expression_get_value_type (_tmp182_);
		_tmp184_ = _tmp183_;
		_tmp185_ = ((ValaCCodeBaseModule*) self)->glist_type;
		_tmp186_ = vala_object_type_new ((ValaObjectTypeSymbol*) _tmp185_);
		_tmp187_ = _tmp186_;
		_tmp188_ = vala_data_type_compatible (_tmp184_, (ValaDataType*) _tmp187_);
		_tmp189_ = _tmp188_;
		_vala_code_node_unref0 (_tmp187_);
		if (_tmp189_) {
			_tmp179_ = TRUE;
		} else {
			ValaForeachStatement* _tmp190_;
			ValaExpression* _tmp191_;
			ValaExpression* _tmp192_;
			ValaDataType* _tmp193_;
			ValaDataType* _tmp194_;
			ValaClass* _tmp195_;
			ValaObjectType* _tmp196_;
			ValaObjectType* _tmp197_;
			gboolean _tmp198_ = FALSE;
			_tmp190_ = stmt;
			_tmp191_ = vala_foreach_statement_get_collection (_tmp190_);
			_tmp192_ = _tmp191_;
			_tmp193_ = vala_expression_get_value_type (_tmp192_);
			_tmp194_ = _tmp193_;
			_tmp195_ = ((ValaCCodeBaseModule*) self)->gslist_type;
			_tmp196_ = vala_object_type_new ((ValaObjectTypeSymbol*) _tmp195_);
			_tmp197_ = _tmp196_;
			_tmp198_ = vala_data_type_compatible (_tmp194_, (ValaDataType*) _tmp197_);
			_tmp179_ = _tmp198_;
			_vala_code_node_unref0 (_tmp197_);
		}
		_tmp199_ = _tmp179_;
		if (_tmp199_) {
			ValaDataType* _tmp200_;
			ValaDataType* _tmp201_ = NULL;
			ValaDataType* _tmp202_;
			ValaForeachStatement* _tmp203_;
			const gchar* _tmp204_;
			const gchar* _tmp205_;
			gchar* _tmp206_;
			gchar* _tmp207_;
			ValaLocalVariable* _tmp208_;
			ValaLocalVariable* _tmp209_;
			ValaLocalVariable* iterator_variable;
			ValaLocalVariable* _tmp210_;
			ValaLocalVariable* _tmp211_;
			gchar* _tmp212_ = NULL;
			gchar* it_name;
			const gchar* _tmp213_;
			ValaCCodeExpression* _tmp214_ = NULL;
			ValaCCodeExpression* _tmp215_;
			ValaCCodeConstant* _tmp216_;
			ValaCCodeConstant* _tmp217_;
			ValaCCodeBinaryExpression* _tmp218_;
			ValaCCodeBinaryExpression* _tmp219_;
			ValaCCodeBinaryExpression* ccond;
			ValaCCodeFunction* _tmp220_;
			ValaCCodeFunction* _tmp221_;
			const gchar* _tmp222_;
			ValaCCodeExpression* _tmp223_ = NULL;
			ValaCCodeExpression* _tmp224_;
			ValaLocalVariable* _tmp225_;
			gchar* _tmp226_ = NULL;
			gchar* _tmp227_;
			ValaCCodeExpression* _tmp228_ = NULL;
			ValaCCodeExpression* _tmp229_;
			ValaCCodeAssignment* _tmp230_;
			ValaCCodeAssignment* _tmp231_;
			ValaCCodeBinaryExpression* _tmp232_;
			const gchar* _tmp233_;
			ValaCCodeExpression* _tmp234_ = NULL;
			ValaCCodeExpression* _tmp235_;
			const gchar* _tmp236_;
			ValaCCodeExpression* _tmp237_ = NULL;
			ValaCCodeExpression* _tmp238_;
			ValaCCodeMemberAccess* _tmp239_;
			ValaCCodeMemberAccess* _tmp240_;
			ValaCCodeAssignment* _tmp241_;
			ValaCCodeAssignment* _tmp242_;
			const gchar* _tmp243_;
			ValaCCodeExpression* _tmp244_ = NULL;
			ValaCCodeExpression* _tmp245_;
			ValaCCodeMemberAccess* _tmp246_;
			ValaCCodeExpression* _tmp247_;
			ValaCCodeExpression* element_expr;
			ValaDataType* _tmp248_;
			ValaList* _tmp249_ = NULL;
			ValaList* _tmp250_;
			gint _tmp251_;
			gint _tmp252_;
			gboolean _tmp253_;
			ValaDataType* _tmp258_;
			ValaList* _tmp259_ = NULL;
			ValaList* _tmp260_;
			gpointer _tmp261_ = NULL;
			ValaDataType* _tmp262_;
			ValaDataType* _tmp263_ = NULL;
			ValaDataType* _tmp264_;
			ValaDataType* element_data_type;
			ValaDataType* _tmp265_;
			ValaCCodeExpression* _tmp266_;
			ValaDataType* _tmp267_;
			ValaCCodeExpression* _tmp268_ = NULL;
			ValaDataType* _tmp269_;
			ValaCCodeExpression* _tmp270_;
			ValaGLibValue* _tmp271_;
			ValaGLibValue* _tmp272_;
			ValaForeachStatement* _tmp273_;
			ValaDataType* _tmp274_;
			ValaDataType* _tmp275_;
			ValaForeachStatement* _tmp276_;
			ValaTargetValue* _tmp277_ = NULL;
			ValaTargetValue* _tmp278_;
			ValaCCodeExpression* _tmp279_ = NULL;
			ValaForeachStatement* _tmp280_;
			ValaLocalVariable* _tmp281_;
			ValaLocalVariable* _tmp282_;
			ValaCCodeFunction* _tmp283_;
			ValaCCodeFunction* _tmp284_;
			ValaForeachStatement* _tmp285_;
			ValaLocalVariable* _tmp286_;
			ValaLocalVariable* _tmp287_;
			gchar* _tmp288_ = NULL;
			gchar* _tmp289_;
			ValaCCodeExpression* _tmp290_ = NULL;
			ValaCCodeExpression* _tmp291_;
			ValaCCodeExpression* _tmp292_;
			ValaForeachStatement* _tmp293_;
			ValaBlock* _tmp294_;
			ValaBlock* _tmp295_;
			ValaCCodeFunction* _tmp296_;
			ValaCCodeFunction* _tmp297_;
			_tmp200_ = collection_type;
			_tmp201_ = vala_data_type_copy (_tmp200_);
			_tmp202_ = _tmp201_;
			_tmp203_ = stmt;
			_tmp204_ = vala_foreach_statement_get_variable_name (_tmp203_);
			_tmp205_ = _tmp204_;
			_tmp206_ = g_strconcat (_tmp205_, "_it", NULL);
			_tmp207_ = _tmp206_;
			_tmp208_ = vala_local_variable_new (_tmp202_, _tmp207_, NULL, NULL);
			_tmp209_ = _tmp208_;
			_g_free0 (_tmp207_);
			_vala_code_node_unref0 (_tmp202_);
			iterator_variable = _tmp209_;
			_tmp210_ = iterator_variable;
			vala_code_visitor_visit_local_variable ((ValaCodeVisitor*) self, _tmp210_);
			_tmp211_ = iterator_variable;
			_tmp212_ = vala_ccode_base_module_get_local_cname ((ValaCCodeBaseModule*) self, _tmp211_);
			it_name = _tmp212_;
			_tmp213_ = it_name;
			_tmp214_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp213_);
			_tmp215_ = _tmp214_;
			_tmp216_ = vala_ccode_constant_new ("NULL");
			_tmp217_ = _tmp216_;
			_tmp218_ = vala_ccode_binary_expression_new (VALA_CCODE_BINARY_OPERATOR_INEQUALITY, _tmp215_, (ValaCCodeExpression*) _tmp217_);
			_tmp219_ = _tmp218_;
			_vala_ccode_node_unref0 (_tmp217_);
			_vala_ccode_node_unref0 (_tmp215_);
			ccond = _tmp219_;
			_tmp220_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
			_tmp221_ = _tmp220_;
			_tmp222_ = it_name;
			_tmp223_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp222_);
			_tmp224_ = _tmp223_;
			_tmp225_ = collection_backup;
			_tmp226_ = vala_ccode_base_module_get_local_cname ((ValaCCodeBaseModule*) self, _tmp225_);
			_tmp227_ = _tmp226_;
			_tmp228_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp227_);
			_tmp229_ = _tmp228_;
			_tmp230_ = vala_ccode_assignment_new (_tmp224_, _tmp229_, VALA_CCODE_ASSIGNMENT_OPERATOR_SIMPLE);
			_tmp231_ = _tmp230_;
			_tmp232_ = ccond;
			_tmp233_ = it_name;
			_tmp234_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp233_);
			_tmp235_ = _tmp234_;
			_tmp236_ = it_name;
			_tmp237_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp236_);
			_tmp238_ = _tmp237_;
			_tmp239_ = vala_ccode_member_access_new_pointer (_tmp238_, "next");
			_tmp240_ = _tmp239_;
			_tmp241_ = vala_ccode_assignment_new (_tmp235_, (ValaCCodeExpression*) _tmp240_, VALA_CCODE_ASSIGNMENT_OPERATOR_SIMPLE);
			_tmp242_ = _tmp241_;
			vala_ccode_function_open_for (_tmp221_, (ValaCCodeExpression*) _tmp231_, (ValaCCodeExpression*) _tmp232_, (ValaCCodeExpression*) _tmp242_);
			_vala_ccode_node_unref0 (_tmp242_);
			_vala_ccode_node_unref0 (_tmp240_);
			_vala_ccode_node_unref0 (_tmp238_);
			_vala_ccode_node_unref0 (_tmp235_);
			_vala_ccode_node_unref0 (_tmp231_);
			_vala_ccode_node_unref0 (_tmp229_);
			_g_free0 (_tmp227_);
			_vala_ccode_node_unref0 (_tmp224_);
			_tmp243_ = it_name;
			_tmp244_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp243_);
			_tmp245_ = _tmp244_;
			_tmp246_ = vala_ccode_member_access_new_pointer (_tmp245_, "data");
			_tmp247_ = (ValaCCodeExpression*) _tmp246_;
			_vala_ccode_node_unref0 (_tmp245_);
			element_expr = _tmp247_;
			_tmp248_ = collection_type;
			_tmp249_ = vala_data_type_get_type_arguments (_tmp248_);
			_tmp250_ = _tmp249_;
			_tmp251_ = vala_collection_get_size ((ValaCollection*) _tmp250_);
			_tmp252_ = _tmp251_;
			_tmp253_ = _tmp252_ != 1;
			_vala_iterable_unref0 (_tmp250_);
			if (_tmp253_) {
				ValaForeachStatement* _tmp254_;
				ValaSourceReference* _tmp255_;
				ValaSourceReference* _tmp256_;
				ValaForeachStatement* _tmp257_;
				_tmp254_ = stmt;
				_tmp255_ = vala_code_node_get_source_reference ((ValaCodeNode*) _tmp254_);
				_tmp256_ = _tmp255_;
				vala_report_error (_tmp256_, "internal error: missing generic type argument");
				_tmp257_ = stmt;
				vala_code_node_set_error ((ValaCodeNode*) _tmp257_, TRUE);
				_vala_ccode_node_unref0 (element_expr);
				_vala_ccode_node_unref0 (ccond);
				_g_free0 (it_name);
				_vala_code_node_unref0 (iterator_variable);
				_vala_code_node_unref0 (array_type);
				_vala_code_node_unref0 (collection_type);
				_vala_code_node_unref0 (collection_backup);
				return;
			}
			_tmp258_ = collection_type;
			_tmp259_ = vala_data_type_get_type_arguments (_tmp258_);
			_tmp260_ = _tmp259_;
			_tmp261_ = vala_list_get (_tmp260_, 0);
			_tmp262_ = (ValaDataType*) _tmp261_;
			_tmp263_ = vala_data_type_copy (_tmp262_);
			_tmp264_ = _tmp263_;
			_vala_code_node_unref0 (_tmp262_);
			_vala_iterable_unref0 (_tmp260_);
			element_data_type = _tmp264_;
			_tmp265_ = element_data_type;
			vala_data_type_set_value_owned (_tmp265_, FALSE);
			_tmp266_ = element_expr;
			_tmp267_ = element_data_type;
			_tmp268_ = vala_ccode_base_module_convert_from_generic_pointer ((ValaCCodeBaseModule*) self, _tmp266_, _tmp267_);
			_vala_ccode_node_unref0 (element_expr);
			element_expr = _tmp268_;
			_tmp269_ = element_data_type;
			_tmp270_ = element_expr;
			_tmp271_ = vala_glib_value_new (_tmp269_, _tmp270_, FALSE);
			_tmp272_ = _tmp271_;
			_tmp273_ = stmt;
			_tmp274_ = vala_foreach_statement_get_type_reference (_tmp273_);
			_tmp275_ = _tmp274_;
			_tmp276_ = stmt;
			_tmp277_ = vala_ccode_base_module_transform_value ((ValaCCodeBaseModule*) self, (ValaTargetValue*) _tmp272_, _tmp275_, (ValaCodeNode*) _tmp276_);
			_tmp278_ = _tmp277_;
			_tmp279_ = vala_ccode_base_module_get_cvalue_ ((ValaCCodeBaseModule*) self, _tmp278_);
			_vala_ccode_node_unref0 (element_expr);
			element_expr = _tmp279_;
			_vala_target_value_unref0 (_tmp278_);
			_vala_target_value_unref0 (_tmp272_);
			_tmp280_ = stmt;
			_tmp281_ = vala_foreach_statement_get_element_variable (_tmp280_);
			_tmp282_ = _tmp281_;
			vala_code_visitor_visit_local_variable ((ValaCodeVisitor*) self, _tmp282_);
			_tmp283_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
			_tmp284_ = _tmp283_;
			_tmp285_ = stmt;
			_tmp286_ = vala_foreach_statement_get_element_variable (_tmp285_);
			_tmp287_ = _tmp286_;
			_tmp288_ = vala_ccode_base_module_get_local_cname ((ValaCCodeBaseModule*) self, _tmp287_);
			_tmp289_ = _tmp288_;
			_tmp290_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp289_);
			_tmp291_ = _tmp290_;
			_tmp292_ = element_expr;
			vala_ccode_function_add_assignment (_tmp284_, _tmp291_, _tmp292_);
			_vala_ccode_node_unref0 (_tmp291_);
			_g_free0 (_tmp289_);
			_tmp293_ = stmt;
			_tmp294_ = vala_foreach_statement_get_body (_tmp293_);
			_tmp295_ = _tmp294_;
			vala_code_node_emit ((ValaCodeNode*) _tmp295_, (ValaCodeGenerator*) self);
			_tmp296_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
			_tmp297_ = _tmp296_;
			vala_ccode_function_close (_tmp297_);
			_vala_code_node_unref0 (element_data_type);
			_vala_ccode_node_unref0 (element_expr);
			_vala_ccode_node_unref0 (ccond);
			_g_free0 (it_name);
			_vala_code_node_unref0 (iterator_variable);
		} else {
			ValaForeachStatement* _tmp298_;
			ValaExpression* _tmp299_;
			ValaExpression* _tmp300_;
			ValaDataType* _tmp301_;
			ValaDataType* _tmp302_;
			ValaClass* _tmp303_;
			ValaObjectType* _tmp304_;
			ValaObjectType* _tmp305_;
			gboolean _tmp306_ = FALSE;
			gboolean _tmp307_;
			_tmp298_ = stmt;
			_tmp299_ = vala_foreach_statement_get_collection (_tmp298_);
			_tmp300_ = _tmp299_;
			_tmp301_ = vala_expression_get_value_type (_tmp300_);
			_tmp302_ = _tmp301_;
			_tmp303_ = ((ValaCCodeBaseModule*) self)->gvaluearray_type;
			_tmp304_ = vala_object_type_new ((ValaObjectTypeSymbol*) _tmp303_);
			_tmp305_ = _tmp304_;
			_tmp306_ = vala_data_type_compatible (_tmp302_, (ValaDataType*) _tmp305_);
			_tmp307_ = _tmp306_;
			_vala_code_node_unref0 (_tmp305_);
			if (_tmp307_) {
				ValaDataType* _tmp308_;
				ValaDataType* _tmp309_ = NULL;
				ValaDataType* _tmp310_;
				ValaForeachStatement* _tmp311_;
				const gchar* _tmp312_;
				const gchar* _tmp313_;
				gchar* _tmp314_ = NULL;
				gchar* _tmp315_;
				ValaLocalVariable* _tmp316_;
				ValaLocalVariable* _tmp317_;
				ValaLocalVariable* iterator_variable;
				ValaLocalVariable* _tmp318_;
				ValaLocalVariable* _tmp319_;
				gchar* _tmp320_ = NULL;
				gchar* _tmp321_;
				gchar* _tmp322_ = NULL;
				gchar* _tmp323_;
				gchar* arr_index;
				const gchar* _tmp324_;
				ValaCCodeExpression* _tmp325_ = NULL;
				ValaCCodeExpression* _tmp326_;
				ValaLocalVariable* _tmp327_;
				gchar* _tmp328_ = NULL;
				gchar* _tmp329_;
				ValaCCodeExpression* _tmp330_ = NULL;
				ValaCCodeExpression* _tmp331_;
				ValaCCodeMemberAccess* _tmp332_;
				ValaCCodeMemberAccess* _tmp333_;
				ValaCCodeBinaryExpression* _tmp334_;
				ValaCCodeBinaryExpression* _tmp335_;
				ValaCCodeBinaryExpression* ccond;
				ValaCCodeFunction* _tmp336_;
				ValaCCodeFunction* _tmp337_;
				const gchar* _tmp338_;
				ValaCCodeExpression* _tmp339_ = NULL;
				ValaCCodeExpression* _tmp340_;
				ValaCCodeConstant* _tmp341_;
				ValaCCodeConstant* _tmp342_;
				ValaCCodeAssignment* _tmp343_;
				ValaCCodeAssignment* _tmp344_;
				ValaCCodeBinaryExpression* _tmp345_;
				const gchar* _tmp346_;
				ValaCCodeExpression* _tmp347_ = NULL;
				ValaCCodeExpression* _tmp348_;
				const gchar* _tmp349_;
				ValaCCodeExpression* _tmp350_ = NULL;
				ValaCCodeExpression* _tmp351_;
				ValaCCodeConstant* _tmp352_;
				ValaCCodeConstant* _tmp353_;
				ValaCCodeBinaryExpression* _tmp354_;
				ValaCCodeBinaryExpression* _tmp355_;
				ValaCCodeAssignment* _tmp356_;
				ValaCCodeAssignment* _tmp357_;
				ValaCCodeIdentifier* _tmp358_;
				ValaCCodeIdentifier* _tmp359_;
				ValaCCodeFunctionCall* _tmp360_;
				ValaCCodeFunctionCall* _tmp361_;
				ValaCCodeFunctionCall* get_item;
				ValaCCodeFunctionCall* _tmp362_;
				ValaLocalVariable* _tmp363_;
				gchar* _tmp364_ = NULL;
				gchar* _tmp365_;
				ValaCCodeExpression* _tmp366_ = NULL;
				ValaCCodeExpression* _tmp367_;
				ValaCCodeFunctionCall* _tmp368_;
				const gchar* _tmp369_;
				ValaCCodeExpression* _tmp370_ = NULL;
				ValaCCodeExpression* _tmp371_;
				ValaCCodeFunctionCall* _tmp372_;
				ValaCCodeUnaryExpression* _tmp373_;
				ValaCCodeExpression* element_expr;
				ValaForeachStatement* _tmp374_;
				ValaDataType* _tmp375_;
				ValaDataType* _tmp376_;
				gboolean _tmp377_;
				gboolean _tmp378_;
				ValaForeachStatement* _tmp391_;
				ValaLocalVariable* _tmp392_;
				ValaLocalVariable* _tmp393_;
				ValaCCodeFunction* _tmp394_;
				ValaCCodeFunction* _tmp395_;
				ValaForeachStatement* _tmp396_;
				ValaLocalVariable* _tmp397_;
				ValaLocalVariable* _tmp398_;
				gchar* _tmp399_ = NULL;
				gchar* _tmp400_;
				ValaCCodeExpression* _tmp401_ = NULL;
				ValaCCodeExpression* _tmp402_;
				ValaCCodeExpression* _tmp403_;
				ValaForeachStatement* _tmp404_;
				ValaBlock* _tmp405_;
				ValaBlock* _tmp406_;
				ValaCCodeFunction* _tmp407_;
				ValaCCodeFunction* _tmp408_;
				_tmp308_ = ((ValaCCodeBaseModule*) self)->uint_type;
				_tmp309_ = vala_data_type_copy (_tmp308_);
				_tmp310_ = _tmp309_;
				_tmp311_ = stmt;
				_tmp312_ = vala_foreach_statement_get_variable_name (_tmp311_);
				_tmp313_ = _tmp312_;
				_tmp314_ = g_strdup_printf ("%s_index", _tmp313_);
				_tmp315_ = _tmp314_;
				_tmp316_ = vala_local_variable_new (_tmp310_, _tmp315_, NULL, NULL);
				_tmp317_ = _tmp316_;
				_g_free0 (_tmp315_);
				_vala_code_node_unref0 (_tmp310_);
				iterator_variable = _tmp317_;
				_tmp318_ = iterator_variable;
				vala_code_visitor_visit_local_variable ((ValaCodeVisitor*) self, _tmp318_);
				_tmp319_ = iterator_variable;
				_tmp320_ = vala_ccode_base_module_get_local_cname ((ValaCCodeBaseModule*) self, _tmp319_);
				_tmp321_ = _tmp320_;
				_tmp322_ = vala_ccode_base_module_get_variable_cname ((ValaCCodeBaseModule*) self, _tmp321_);
				_tmp323_ = _tmp322_;
				_g_free0 (_tmp321_);
				arr_index = _tmp323_;
				_tmp324_ = arr_index;
				_tmp325_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp324_);
				_tmp326_ = _tmp325_;
				_tmp327_ = collection_backup;
				_tmp328_ = vala_ccode_base_module_get_local_cname ((ValaCCodeBaseModule*) self, _tmp327_);
				_tmp329_ = _tmp328_;
				_tmp330_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp329_);
				_tmp331_ = _tmp330_;
				_tmp332_ = vala_ccode_member_access_new_pointer (_tmp331_, "n_values");
				_tmp333_ = _tmp332_;
				_tmp334_ = vala_ccode_binary_expression_new (VALA_CCODE_BINARY_OPERATOR_LESS_THAN, _tmp326_, (ValaCCodeExpression*) _tmp333_);
				_tmp335_ = _tmp334_;
				_vala_ccode_node_unref0 (_tmp333_);
				_vala_ccode_node_unref0 (_tmp331_);
				_g_free0 (_tmp329_);
				_vala_ccode_node_unref0 (_tmp326_);
				ccond = _tmp335_;
				_tmp336_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
				_tmp337_ = _tmp336_;
				_tmp338_ = arr_index;
				_tmp339_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp338_);
				_tmp340_ = _tmp339_;
				_tmp341_ = vala_ccode_constant_new ("0");
				_tmp342_ = _tmp341_;
				_tmp343_ = vala_ccode_assignment_new (_tmp340_, (ValaCCodeExpression*) _tmp342_, VALA_CCODE_ASSIGNMENT_OPERATOR_SIMPLE);
				_tmp344_ = _tmp343_;
				_tmp345_ = ccond;
				_tmp346_ = arr_index;
				_tmp347_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp346_);
				_tmp348_ = _tmp347_;
				_tmp349_ = arr_index;
				_tmp350_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp349_);
				_tmp351_ = _tmp350_;
				_tmp352_ = vala_ccode_constant_new ("1");
				_tmp353_ = _tmp352_;
				_tmp354_ = vala_ccode_binary_expression_new (VALA_CCODE_BINARY_OPERATOR_PLUS, _tmp351_, (ValaCCodeExpression*) _tmp353_);
				_tmp355_ = _tmp354_;
				_tmp356_ = vala_ccode_assignment_new (_tmp348_, (ValaCCodeExpression*) _tmp355_, VALA_CCODE_ASSIGNMENT_OPERATOR_SIMPLE);
				_tmp357_ = _tmp356_;
				vala_ccode_function_open_for (_tmp337_, (ValaCCodeExpression*) _tmp344_, (ValaCCodeExpression*) _tmp345_, (ValaCCodeExpression*) _tmp357_);
				_vala_ccode_node_unref0 (_tmp357_);
				_vala_ccode_node_unref0 (_tmp355_);
				_vala_ccode_node_unref0 (_tmp353_);
				_vala_ccode_node_unref0 (_tmp351_);
				_vala_ccode_node_unref0 (_tmp348_);
				_vala_ccode_node_unref0 (_tmp344_);
				_vala_ccode_node_unref0 (_tmp342_);
				_vala_ccode_node_unref0 (_tmp340_);
				_tmp358_ = vala_ccode_identifier_new ("g_value_array_get_nth");
				_tmp359_ = _tmp358_;
				_tmp360_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp359_);
				_tmp361_ = _tmp360_;
				_vala_ccode_node_unref0 (_tmp359_);
				get_item = _tmp361_;
				_tmp362_ = get_item;
				_tmp363_ = collection_backup;
				_tmp364_ = vala_ccode_base_module_get_local_cname ((ValaCCodeBaseModule*) self, _tmp363_);
				_tmp365_ = _tmp364_;
				_tmp366_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp365_);
				_tmp367_ = _tmp366_;
				vala_ccode_function_call_add_argument (_tmp362_, _tmp367_);
				_vala_ccode_node_unref0 (_tmp367_);
				_g_free0 (_tmp365_);
				_tmp368_ = get_item;
				_tmp369_ = arr_index;
				_tmp370_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp369_);
				_tmp371_ = _tmp370_;
				vala_ccode_function_call_add_argument (_tmp368_, _tmp371_);
				_vala_ccode_node_unref0 (_tmp371_);
				_tmp372_ = get_item;
				_tmp373_ = vala_ccode_unary_expression_new (VALA_CCODE_UNARY_OPERATOR_POINTER_INDIRECTION, (ValaCCodeExpression*) _tmp372_);
				element_expr = (ValaCCodeExpression*) _tmp373_;
				_tmp374_ = stmt;
				_tmp375_ = vala_foreach_statement_get_type_reference (_tmp374_);
				_tmp376_ = _tmp375_;
				_tmp377_ = vala_data_type_get_value_owned (_tmp376_);
				_tmp378_ = _tmp377_;
				if (_tmp378_) {
					ValaForeachStatement* _tmp379_;
					ValaDataType* _tmp380_;
					ValaDataType* _tmp381_;
					ValaCCodeExpression* _tmp382_;
					ValaGLibValue* _tmp383_;
					ValaGLibValue* _tmp384_;
					ValaStruct* _tmp385_;
					ValaStructValueType* _tmp386_;
					ValaStructValueType* _tmp387_;
					ValaTargetValue* _tmp388_ = NULL;
					ValaTargetValue* _tmp389_;
					ValaCCodeExpression* _tmp390_ = NULL;
					_tmp379_ = stmt;
					_tmp380_ = vala_foreach_statement_get_type_reference (_tmp379_);
					_tmp381_ = _tmp380_;
					_tmp382_ = element_expr;
					_tmp383_ = vala_glib_value_new (_tmp381_, _tmp382_, FALSE);
					_tmp384_ = _tmp383_;
					_tmp385_ = ((ValaCCodeBaseModule*) self)->gvalue_type;
					_tmp386_ = vala_struct_value_type_new (_tmp385_);
					_tmp387_ = _tmp386_;
					_tmp388_ = vala_ccode_base_module_copy_value ((ValaCCodeBaseModule*) self, (ValaTargetValue*) _tmp384_, (ValaCodeNode*) _tmp387_);
					_tmp389_ = _tmp388_;
					_tmp390_ = vala_ccode_base_module_get_cvalue_ ((ValaCCodeBaseModule*) self, _tmp389_);
					_vala_ccode_node_unref0 (element_expr);
					element_expr = _tmp390_;
					_vala_target_value_unref0 (_tmp389_);
					_vala_code_node_unref0 (_tmp387_);
					_vala_target_value_unref0 (_tmp384_);
				}
				_tmp391_ = stmt;
				_tmp392_ = vala_foreach_statement_get_element_variable (_tmp391_);
				_tmp393_ = _tmp392_;
				vala_code_visitor_visit_local_variable ((ValaCodeVisitor*) self, _tmp393_);
				_tmp394_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
				_tmp395_ = _tmp394_;
				_tmp396_ = stmt;
				_tmp397_ = vala_foreach_statement_get_element_variable (_tmp396_);
				_tmp398_ = _tmp397_;
				_tmp399_ = vala_ccode_base_module_get_local_cname ((ValaCCodeBaseModule*) self, _tmp398_);
				_tmp400_ = _tmp399_;
				_tmp401_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp400_);
				_tmp402_ = _tmp401_;
				_tmp403_ = element_expr;
				vala_ccode_function_add_assignment (_tmp395_, _tmp402_, _tmp403_);
				_vala_ccode_node_unref0 (_tmp402_);
				_g_free0 (_tmp400_);
				_tmp404_ = stmt;
				_tmp405_ = vala_foreach_statement_get_body (_tmp404_);
				_tmp406_ = _tmp405_;
				vala_code_node_emit ((ValaCodeNode*) _tmp406_, (ValaCodeGenerator*) self);
				_tmp407_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
				_tmp408_ = _tmp407_;
				vala_ccode_function_close (_tmp408_);
				_vala_ccode_node_unref0 (element_expr);
				_vala_ccode_node_unref0 (get_item);
				_vala_ccode_node_unref0 (ccond);
				_g_free0 (arr_index);
				_vala_code_node_unref0 (iterator_variable);
			}
		}
	}
	{
		ValaForeachStatement* _tmp409_;
		ValaList* _tmp410_ = NULL;
		ValaList* _local_list;
		ValaList* _tmp411_;
		gint _tmp412_;
		gint _tmp413_;
		gint _local_size;
		gint _local_index;
		_tmp409_ = stmt;
		_tmp410_ = vala_block_get_local_variables ((ValaBlock*) _tmp409_);
		_local_list = _tmp410_;
		_tmp411_ = _local_list;
		_tmp412_ = vala_collection_get_size ((ValaCollection*) _tmp411_);
		_tmp413_ = _tmp412_;
		_local_size = _tmp413_;
		_local_index = -1;
		while (TRUE) {
			gint _tmp414_;
			gint _tmp415_;
			gint _tmp416_;
			ValaList* _tmp417_;
			gint _tmp418_;
			gpointer _tmp419_ = NULL;
			ValaLocalVariable* local;
			ValaLocalVariable* _tmp420_;
			ValaDataType* _tmp421_;
			ValaDataType* _tmp422_;
			gboolean _tmp423_ = FALSE;
			_tmp414_ = _local_index;
			_local_index = _tmp414_ + 1;
			_tmp415_ = _local_index;
			_tmp416_ = _local_size;
			if (!(_tmp415_ < _tmp416_)) {
				break;
			}
			_tmp417_ = _local_list;
			_tmp418_ = _local_index;
			_tmp419_ = vala_list_get (_tmp417_, _tmp418_);
			local = (ValaLocalVariable*) _tmp419_;
			_tmp420_ = local;
			_tmp421_ = vala_variable_get_variable_type ((ValaVariable*) _tmp420_);
			_tmp422_ = _tmp421_;
			_tmp423_ = vala_ccode_base_module_requires_destroy ((ValaCCodeBaseModule*) self, _tmp422_);
			if (_tmp423_) {
				ValaCCodeFunction* _tmp424_;
				ValaCCodeFunction* _tmp425_;
				ValaLocalVariable* _tmp426_;
				ValaCCodeExpression* _tmp427_ = NULL;
				ValaCCodeExpression* _tmp428_;
				_tmp424_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
				_tmp425_ = _tmp424_;
				_tmp426_ = local;
				_tmp427_ = vala_ccode_base_module_destroy_local ((ValaCCodeBaseModule*) self, _tmp426_);
				_tmp428_ = _tmp427_;
				vala_ccode_function_add_expression (_tmp425_, _tmp428_);
				_vala_ccode_node_unref0 (_tmp428_);
			}
			_vala_code_node_unref0 (local);
		}
		_vala_iterable_unref0 (_local_list);
	}
	_tmp429_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp430_ = _tmp429_;
	vala_ccode_function_close (_tmp430_);
	_vala_code_node_unref0 (array_type);
	_vala_code_node_unref0 (collection_type);
	_vala_code_node_unref0 (collection_backup);
}


static void vala_ccode_control_flow_module_real_visit_break_statement (ValaCodeVisitor* base, ValaBreakStatement* stmt) {
	ValaCCodeControlFlowModule * self;
	ValaSymbol* _tmp0_;
	ValaSymbol* _tmp1_;
	ValaCCodeFunction* _tmp2_;
	ValaCCodeFunction* _tmp3_;
	self = (ValaCCodeControlFlowModule*) base;
	g_return_if_fail (stmt != NULL);
	_tmp0_ = vala_ccode_base_module_get_current_symbol ((ValaCCodeBaseModule*) self);
	_tmp1_ = _tmp0_;
	vala_ccode_base_module_append_local_free ((ValaCCodeBaseModule*) self, _tmp1_, TRUE, NULL);
	_tmp2_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp3_ = _tmp2_;
	vala_ccode_function_add_break (_tmp3_);
}


static void vala_ccode_control_flow_module_real_visit_continue_statement (ValaCodeVisitor* base, ValaContinueStatement* stmt) {
	ValaCCodeControlFlowModule * self;
	ValaSymbol* _tmp0_;
	ValaSymbol* _tmp1_;
	ValaCCodeFunction* _tmp2_;
	ValaCCodeFunction* _tmp3_;
	self = (ValaCCodeControlFlowModule*) base;
	g_return_if_fail (stmt != NULL);
	_tmp0_ = vala_ccode_base_module_get_current_symbol ((ValaCCodeBaseModule*) self);
	_tmp1_ = _tmp0_;
	vala_ccode_base_module_append_local_free ((ValaCCodeBaseModule*) self, _tmp1_, TRUE, NULL);
	_tmp2_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp3_ = _tmp2_;
	vala_ccode_function_add_continue (_tmp3_);
}


ValaCCodeControlFlowModule* vala_ccode_control_flow_module_construct (GType object_type) {
	ValaCCodeControlFlowModule* self = NULL;
	self = (ValaCCodeControlFlowModule*) vala_ccode_method_module_construct (object_type);
	return self;
}


static void vala_ccode_control_flow_module_class_init (ValaCCodeControlFlowModuleClass * klass) {
	vala_ccode_control_flow_module_parent_class = g_type_class_peek_parent (klass);
	VALA_CODE_VISITOR_CLASS (klass)->visit_if_statement = vala_ccode_control_flow_module_real_visit_if_statement;
	VALA_CODE_VISITOR_CLASS (klass)->visit_switch_statement = vala_ccode_control_flow_module_real_visit_switch_statement;
	VALA_CODE_VISITOR_CLASS (klass)->visit_switch_label = vala_ccode_control_flow_module_real_visit_switch_label;
	VALA_CODE_VISITOR_CLASS (klass)->visit_loop = vala_ccode_control_flow_module_real_visit_loop;
	VALA_CODE_VISITOR_CLASS (klass)->visit_foreach_statement = vala_ccode_control_flow_module_real_visit_foreach_statement;
	VALA_CODE_VISITOR_CLASS (klass)->visit_break_statement = vala_ccode_control_flow_module_real_visit_break_statement;
	VALA_CODE_VISITOR_CLASS (klass)->visit_continue_statement = vala_ccode_control_flow_module_real_visit_continue_statement;
}


static void vala_ccode_control_flow_module_instance_init (ValaCCodeControlFlowModule * self) {
}


GType vala_ccode_control_flow_module_get_type (void) {
	static volatile gsize vala_ccode_control_flow_module_type_id__volatile = 0;
	if (g_once_init_enter (&vala_ccode_control_flow_module_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ValaCCodeControlFlowModuleClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vala_ccode_control_flow_module_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ValaCCodeControlFlowModule), 0, (GInstanceInitFunc) vala_ccode_control_flow_module_instance_init, NULL };
		GType vala_ccode_control_flow_module_type_id;
		vala_ccode_control_flow_module_type_id = g_type_register_static (VALA_TYPE_CCODE_METHOD_MODULE, "ValaCCodeControlFlowModule", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&vala_ccode_control_flow_module_type_id__volatile, vala_ccode_control_flow_module_type_id);
	}
	return vala_ccode_control_flow_module_type_id__volatile;
}



