/* valagdbusmodule.c generated by valac, the Vala compiler
 * generated from valagdbusmodule.vala, do not modify */

/* valagdbusmodule.vala
 *
 * Copyright (C) 2010-2012  Jürg Billeter
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.

 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.

 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 * Author:
 * 	Jürg Billeter <j@bitron.ch>
 */

#include <glib.h>
#include <glib-object.h>
#include <vala.h>
#include <valaccode.h>
#include <valagee.h>
#include <stdlib.h>
#include <string.h>


#define VALA_TYPE_CCODE_BASE_MODULE (vala_ccode_base_module_get_type ())
#define VALA_CCODE_BASE_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_BASE_MODULE, ValaCCodeBaseModule))
#define VALA_CCODE_BASE_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_BASE_MODULE, ValaCCodeBaseModuleClass))
#define VALA_IS_CCODE_BASE_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_BASE_MODULE))
#define VALA_IS_CCODE_BASE_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_BASE_MODULE))
#define VALA_CCODE_BASE_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_BASE_MODULE, ValaCCodeBaseModuleClass))

typedef struct _ValaCCodeBaseModule ValaCCodeBaseModule;
typedef struct _ValaCCodeBaseModuleClass ValaCCodeBaseModuleClass;
typedef struct _ValaCCodeBaseModulePrivate ValaCCodeBaseModulePrivate;

#define VALA_CCODE_BASE_MODULE_TYPE_EMIT_CONTEXT (vala_ccode_base_module_emit_context_get_type ())
#define VALA_CCODE_BASE_MODULE_EMIT_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_CCODE_BASE_MODULE_TYPE_EMIT_CONTEXT, ValaCCodeBaseModuleEmitContext))
#define VALA_CCODE_BASE_MODULE_EMIT_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_CCODE_BASE_MODULE_TYPE_EMIT_CONTEXT, ValaCCodeBaseModuleEmitContextClass))
#define VALA_CCODE_BASE_MODULE_IS_EMIT_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_CCODE_BASE_MODULE_TYPE_EMIT_CONTEXT))
#define VALA_CCODE_BASE_MODULE_IS_EMIT_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_CCODE_BASE_MODULE_TYPE_EMIT_CONTEXT))
#define VALA_CCODE_BASE_MODULE_EMIT_CONTEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_CCODE_BASE_MODULE_TYPE_EMIT_CONTEXT, ValaCCodeBaseModuleEmitContextClass))

typedef struct _ValaCCodeBaseModuleEmitContext ValaCCodeBaseModuleEmitContext;
typedef struct _ValaCCodeBaseModuleEmitContextClass ValaCCodeBaseModuleEmitContextClass;

#define VALA_TYPE_CCODE_STRUCT_MODULE (vala_ccode_struct_module_get_type ())
#define VALA_CCODE_STRUCT_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_STRUCT_MODULE, ValaCCodeStructModule))
#define VALA_CCODE_STRUCT_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_STRUCT_MODULE, ValaCCodeStructModuleClass))
#define VALA_IS_CCODE_STRUCT_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_STRUCT_MODULE))
#define VALA_IS_CCODE_STRUCT_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_STRUCT_MODULE))
#define VALA_CCODE_STRUCT_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_STRUCT_MODULE, ValaCCodeStructModuleClass))

typedef struct _ValaCCodeStructModule ValaCCodeStructModule;
typedef struct _ValaCCodeStructModuleClass ValaCCodeStructModuleClass;
typedef struct _ValaCCodeStructModulePrivate ValaCCodeStructModulePrivate;

#define VALA_TYPE_CCODE_METHOD_MODULE (vala_ccode_method_module_get_type ())
#define VALA_CCODE_METHOD_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_METHOD_MODULE, ValaCCodeMethodModule))
#define VALA_CCODE_METHOD_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_METHOD_MODULE, ValaCCodeMethodModuleClass))
#define VALA_IS_CCODE_METHOD_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_METHOD_MODULE))
#define VALA_IS_CCODE_METHOD_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_METHOD_MODULE))
#define VALA_CCODE_METHOD_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_METHOD_MODULE, ValaCCodeMethodModuleClass))

typedef struct _ValaCCodeMethodModule ValaCCodeMethodModule;
typedef struct _ValaCCodeMethodModuleClass ValaCCodeMethodModuleClass;
typedef struct _ValaCCodeMethodModulePrivate ValaCCodeMethodModulePrivate;

#define VALA_TYPE_CCODE_CONTROL_FLOW_MODULE (vala_ccode_control_flow_module_get_type ())
#define VALA_CCODE_CONTROL_FLOW_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_CONTROL_FLOW_MODULE, ValaCCodeControlFlowModule))
#define VALA_CCODE_CONTROL_FLOW_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_CONTROL_FLOW_MODULE, ValaCCodeControlFlowModuleClass))
#define VALA_IS_CCODE_CONTROL_FLOW_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_CONTROL_FLOW_MODULE))
#define VALA_IS_CCODE_CONTROL_FLOW_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_CONTROL_FLOW_MODULE))
#define VALA_CCODE_CONTROL_FLOW_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_CONTROL_FLOW_MODULE, ValaCCodeControlFlowModuleClass))

typedef struct _ValaCCodeControlFlowModule ValaCCodeControlFlowModule;
typedef struct _ValaCCodeControlFlowModuleClass ValaCCodeControlFlowModuleClass;
typedef struct _ValaCCodeControlFlowModulePrivate ValaCCodeControlFlowModulePrivate;

#define VALA_TYPE_CCODE_MEMBER_ACCESS_MODULE (vala_ccode_member_access_module_get_type ())
#define VALA_CCODE_MEMBER_ACCESS_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_MEMBER_ACCESS_MODULE, ValaCCodeMemberAccessModule))
#define VALA_CCODE_MEMBER_ACCESS_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_MEMBER_ACCESS_MODULE, ValaCCodeMemberAccessModuleClass))
#define VALA_IS_CCODE_MEMBER_ACCESS_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_MEMBER_ACCESS_MODULE))
#define VALA_IS_CCODE_MEMBER_ACCESS_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_MEMBER_ACCESS_MODULE))
#define VALA_CCODE_MEMBER_ACCESS_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_MEMBER_ACCESS_MODULE, ValaCCodeMemberAccessModuleClass))

typedef struct _ValaCCodeMemberAccessModule ValaCCodeMemberAccessModule;
typedef struct _ValaCCodeMemberAccessModuleClass ValaCCodeMemberAccessModuleClass;
typedef struct _ValaCCodeMemberAccessModulePrivate ValaCCodeMemberAccessModulePrivate;

#define VALA_TYPE_CCODE_ASSIGNMENT_MODULE (vala_ccode_assignment_module_get_type ())
#define VALA_CCODE_ASSIGNMENT_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_ASSIGNMENT_MODULE, ValaCCodeAssignmentModule))
#define VALA_CCODE_ASSIGNMENT_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_ASSIGNMENT_MODULE, ValaCCodeAssignmentModuleClass))
#define VALA_IS_CCODE_ASSIGNMENT_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_ASSIGNMENT_MODULE))
#define VALA_IS_CCODE_ASSIGNMENT_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_ASSIGNMENT_MODULE))
#define VALA_CCODE_ASSIGNMENT_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_ASSIGNMENT_MODULE, ValaCCodeAssignmentModuleClass))

typedef struct _ValaCCodeAssignmentModule ValaCCodeAssignmentModule;
typedef struct _ValaCCodeAssignmentModuleClass ValaCCodeAssignmentModuleClass;
typedef struct _ValaCCodeAssignmentModulePrivate ValaCCodeAssignmentModulePrivate;

#define VALA_TYPE_CCODE_METHOD_CALL_MODULE (vala_ccode_method_call_module_get_type ())
#define VALA_CCODE_METHOD_CALL_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_METHOD_CALL_MODULE, ValaCCodeMethodCallModule))
#define VALA_CCODE_METHOD_CALL_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_METHOD_CALL_MODULE, ValaCCodeMethodCallModuleClass))
#define VALA_IS_CCODE_METHOD_CALL_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_METHOD_CALL_MODULE))
#define VALA_IS_CCODE_METHOD_CALL_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_METHOD_CALL_MODULE))
#define VALA_CCODE_METHOD_CALL_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_METHOD_CALL_MODULE, ValaCCodeMethodCallModuleClass))

typedef struct _ValaCCodeMethodCallModule ValaCCodeMethodCallModule;
typedef struct _ValaCCodeMethodCallModuleClass ValaCCodeMethodCallModuleClass;
typedef struct _ValaCCodeMethodCallModulePrivate ValaCCodeMethodCallModulePrivate;

#define VALA_TYPE_CCODE_ARRAY_MODULE (vala_ccode_array_module_get_type ())
#define VALA_CCODE_ARRAY_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_ARRAY_MODULE, ValaCCodeArrayModule))
#define VALA_CCODE_ARRAY_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_ARRAY_MODULE, ValaCCodeArrayModuleClass))
#define VALA_IS_CCODE_ARRAY_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_ARRAY_MODULE))
#define VALA_IS_CCODE_ARRAY_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_ARRAY_MODULE))
#define VALA_CCODE_ARRAY_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_ARRAY_MODULE, ValaCCodeArrayModuleClass))

typedef struct _ValaCCodeArrayModule ValaCCodeArrayModule;
typedef struct _ValaCCodeArrayModuleClass ValaCCodeArrayModuleClass;
typedef struct _ValaCCodeArrayModulePrivate ValaCCodeArrayModulePrivate;

#define VALA_TYPE_CCODE_DELEGATE_MODULE (vala_ccode_delegate_module_get_type ())
#define VALA_CCODE_DELEGATE_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_DELEGATE_MODULE, ValaCCodeDelegateModule))
#define VALA_CCODE_DELEGATE_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_DELEGATE_MODULE, ValaCCodeDelegateModuleClass))
#define VALA_IS_CCODE_DELEGATE_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_DELEGATE_MODULE))
#define VALA_IS_CCODE_DELEGATE_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_DELEGATE_MODULE))
#define VALA_CCODE_DELEGATE_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_DELEGATE_MODULE, ValaCCodeDelegateModuleClass))

typedef struct _ValaCCodeDelegateModule ValaCCodeDelegateModule;
typedef struct _ValaCCodeDelegateModuleClass ValaCCodeDelegateModuleClass;
typedef struct _ValaCCodeDelegateModulePrivate ValaCCodeDelegateModulePrivate;

#define VALA_TYPE_GERROR_MODULE (vala_gerror_module_get_type ())
#define VALA_GERROR_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_GERROR_MODULE, ValaGErrorModule))
#define VALA_GERROR_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_GERROR_MODULE, ValaGErrorModuleClass))
#define VALA_IS_GERROR_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_GERROR_MODULE))
#define VALA_IS_GERROR_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_GERROR_MODULE))
#define VALA_GERROR_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_GERROR_MODULE, ValaGErrorModuleClass))

typedef struct _ValaGErrorModule ValaGErrorModule;
typedef struct _ValaGErrorModuleClass ValaGErrorModuleClass;
typedef struct _ValaGErrorModulePrivate ValaGErrorModulePrivate;

#define VALA_TYPE_GTYPE_MODULE (vala_gtype_module_get_type ())
#define VALA_GTYPE_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_GTYPE_MODULE, ValaGTypeModule))
#define VALA_GTYPE_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_GTYPE_MODULE, ValaGTypeModuleClass))
#define VALA_IS_GTYPE_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_GTYPE_MODULE))
#define VALA_IS_GTYPE_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_GTYPE_MODULE))
#define VALA_GTYPE_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_GTYPE_MODULE, ValaGTypeModuleClass))

typedef struct _ValaGTypeModule ValaGTypeModule;
typedef struct _ValaGTypeModuleClass ValaGTypeModuleClass;
typedef struct _ValaGTypeModulePrivate ValaGTypeModulePrivate;

#define VALA_TYPE_GOBJECT_MODULE (vala_gobject_module_get_type ())
#define VALA_GOBJECT_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_GOBJECT_MODULE, ValaGObjectModule))
#define VALA_GOBJECT_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_GOBJECT_MODULE, ValaGObjectModuleClass))
#define VALA_IS_GOBJECT_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_GOBJECT_MODULE))
#define VALA_IS_GOBJECT_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_GOBJECT_MODULE))
#define VALA_GOBJECT_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_GOBJECT_MODULE, ValaGObjectModuleClass))

typedef struct _ValaGObjectModule ValaGObjectModule;
typedef struct _ValaGObjectModuleClass ValaGObjectModuleClass;
typedef struct _ValaGObjectModulePrivate ValaGObjectModulePrivate;

#define VALA_TYPE_GSIGNAL_MODULE (vala_gsignal_module_get_type ())
#define VALA_GSIGNAL_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_GSIGNAL_MODULE, ValaGSignalModule))
#define VALA_GSIGNAL_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_GSIGNAL_MODULE, ValaGSignalModuleClass))
#define VALA_IS_GSIGNAL_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_GSIGNAL_MODULE))
#define VALA_IS_GSIGNAL_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_GSIGNAL_MODULE))
#define VALA_GSIGNAL_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_GSIGNAL_MODULE, ValaGSignalModuleClass))

typedef struct _ValaGSignalModule ValaGSignalModule;
typedef struct _ValaGSignalModuleClass ValaGSignalModuleClass;
typedef struct _ValaGSignalModulePrivate ValaGSignalModulePrivate;

#define VALA_TYPE_GASYNC_MODULE (vala_gasync_module_get_type ())
#define VALA_GASYNC_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_GASYNC_MODULE, ValaGAsyncModule))
#define VALA_GASYNC_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_GASYNC_MODULE, ValaGAsyncModuleClass))
#define VALA_IS_GASYNC_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_GASYNC_MODULE))
#define VALA_IS_GASYNC_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_GASYNC_MODULE))
#define VALA_GASYNC_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_GASYNC_MODULE, ValaGAsyncModuleClass))

typedef struct _ValaGAsyncModule ValaGAsyncModule;
typedef struct _ValaGAsyncModuleClass ValaGAsyncModuleClass;
typedef struct _ValaGAsyncModulePrivate ValaGAsyncModulePrivate;

#define VALA_TYPE_GVARIANT_MODULE (vala_gvariant_module_get_type ())
#define VALA_GVARIANT_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_GVARIANT_MODULE, ValaGVariantModule))
#define VALA_GVARIANT_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_GVARIANT_MODULE, ValaGVariantModuleClass))
#define VALA_IS_GVARIANT_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_GVARIANT_MODULE))
#define VALA_IS_GVARIANT_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_GVARIANT_MODULE))
#define VALA_GVARIANT_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_GVARIANT_MODULE, ValaGVariantModuleClass))

typedef struct _ValaGVariantModule ValaGVariantModule;
typedef struct _ValaGVariantModuleClass ValaGVariantModuleClass;
typedef struct _ValaGVariantModulePrivate ValaGVariantModulePrivate;

#define VALA_TYPE_GD_BUS_MODULE (vala_gd_bus_module_get_type ())
#define VALA_GD_BUS_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_GD_BUS_MODULE, ValaGDBusModule))
#define VALA_GD_BUS_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_GD_BUS_MODULE, ValaGDBusModuleClass))
#define VALA_IS_GD_BUS_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_GD_BUS_MODULE))
#define VALA_IS_GD_BUS_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_GD_BUS_MODULE))
#define VALA_GD_BUS_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_GD_BUS_MODULE, ValaGDBusModuleClass))

typedef struct _ValaGDBusModule ValaGDBusModule;
typedef struct _ValaGDBusModuleClass ValaGDBusModuleClass;
typedef struct _ValaGDBusModulePrivate ValaGDBusModulePrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _vala_ccode_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_ccode_node_unref (var), NULL)))
#define _vala_code_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_node_unref (var), NULL)))
#define _vala_iterable_unref0(var) ((var == NULL) ? NULL : (var = (vala_iterable_unref (var), NULL)))

struct _ValaCCodeBaseModule {
	ValaCodeGenerator parent_instance;
	ValaCCodeBaseModulePrivate * priv;
	ValaSymbol* root_symbol;
	ValaCCodeBaseModuleEmitContext* emit_context;
	ValaCCodeLineDirective* current_line;
	ValaCCodeFile* header_file;
	ValaCCodeFile* internal_header_file;
	ValaCCodeFile* cfile;
	ValaCCodeBaseModuleEmitContext* class_init_context;
	ValaCCodeBaseModuleEmitContext* base_init_context;
	ValaCCodeBaseModuleEmitContext* class_finalize_context;
	ValaCCodeBaseModuleEmitContext* base_finalize_context;
	ValaCCodeBaseModuleEmitContext* instance_init_context;
	ValaCCodeBaseModuleEmitContext* instance_finalize_context;
	ValaCCodeStruct* param_spec_struct;
	ValaCCodeStruct* closure_struct;
	ValaCCodeEnum* prop_enum;
	ValaSet* user_marshal_set;
	ValaSet* predefined_marshal_set;
	gint next_regex_id;
	gint next_coroutine_state;
	ValaDataType* void_type;
	ValaDataType* bool_type;
	ValaDataType* char_type;
	ValaDataType* uchar_type;
	ValaDataType* unichar_type;
	ValaDataType* short_type;
	ValaDataType* ushort_type;
	ValaDataType* int_type;
	ValaDataType* uint_type;
	ValaDataType* long_type;
	ValaDataType* ulong_type;
	ValaDataType* int8_type;
	ValaDataType* uint8_type;
	ValaDataType* int16_type;
	ValaDataType* uint16_type;
	ValaDataType* int32_type;
	ValaDataType* uint32_type;
	ValaDataType* int64_type;
	ValaDataType* uint64_type;
	ValaDataType* string_type;
	ValaDataType* regex_type;
	ValaDataType* float_type;
	ValaDataType* double_type;
	ValaTypeSymbol* gtype_type;
	ValaTypeSymbol* gobject_type;
	ValaErrorType* gerror_type;
	ValaClass* glist_type;
	ValaClass* gslist_type;
	ValaClass* gnode_type;
	ValaClass* gqueue_type;
	ValaClass* gvaluearray_type;
	ValaTypeSymbol* gstringbuilder_type;
	ValaTypeSymbol* garray_type;
	ValaTypeSymbol* gbytearray_type;
	ValaTypeSymbol* gptrarray_type;
	ValaTypeSymbol* gthreadpool_type;
	ValaDataType* gdestroynotify_type;
	ValaDataType* gquark_type;
	ValaStruct* gvalue_type;
	ValaClass* gvariant_type;
	ValaStruct* mutex_type;
	ValaStruct* gmutex_type;
	ValaStruct* grecmutex_type;
	ValaStruct* grwlock_type;
	ValaStruct* gcond_type;
	ValaClass* gsource_type;
	ValaTypeSymbol* type_module_type;
	ValaTypeSymbol* dbus_proxy_type;
	gboolean in_plugin;
	gchar* module_init_param_name;
	gboolean gvaluecollector_h_needed;
	gboolean requires_assert;
	gboolean requires_array_free;
	gboolean requires_array_move;
	gboolean requires_array_length;
	gboolean requires_clear_mutex;
	ValaSet* wrappers;
};

struct _ValaCCodeBaseModuleClass {
	ValaCodeGeneratorClass parent_class;
	void (*append_vala_array_free) (ValaCCodeBaseModule* self);
	void (*append_vala_array_move) (ValaCCodeBaseModule* self);
	void (*append_vala_array_length) (ValaCCodeBaseModule* self);
	gboolean (*generate_enum_declaration) (ValaCCodeBaseModule* self, ValaEnum* en, ValaCCodeFile* decl_space);
	void (*generate_class_struct_declaration) (ValaCCodeBaseModule* self, ValaClass* cl, ValaCCodeFile* decl_space);
	void (*generate_struct_declaration) (ValaCCodeBaseModule* self, ValaStruct* st, ValaCCodeFile* decl_space);
	void (*generate_delegate_declaration) (ValaCCodeBaseModule* self, ValaDelegate* d, ValaCCodeFile* decl_space);
	void (*generate_cparameters) (ValaCCodeBaseModule* self, ValaMethod* m, ValaCCodeFile* decl_space, ValaMap* cparam_map, ValaCCodeFunction* func, ValaCCodeFunctionDeclarator* vdeclarator, ValaMap* carg_map, ValaCCodeFunctionCall* vcall, gint direction);
	ValaCCodeExpression* (*get_dup_func_expression) (ValaCCodeBaseModule* self, ValaDataType* type, ValaSourceReference* source_reference, gboolean is_chainup);
	gchar* (*append_struct_array_free) (ValaCCodeBaseModule* self, ValaStruct* st);
	ValaCCodeExpression* (*destroy_value) (ValaCCodeBaseModule* self, ValaTargetValue* value, gboolean is_macro_definition);
	void (*append_scope_free) (ValaCCodeBaseModule* self, ValaSymbol* sym, ValaCodeNode* stop_at);
	ValaTargetValue* (*get_local_cvalue) (ValaCCodeBaseModule* self, ValaLocalVariable* local);
	ValaTargetValue* (*get_parameter_cvalue) (ValaCCodeBaseModule* self, ValaParameter* param);
	ValaTargetValue* (*get_field_cvalue) (ValaCCodeBaseModule* self, ValaField* field, ValaTargetValue* instance);
	ValaTargetValue* (*load_variable) (ValaCCodeBaseModule* self, ValaVariable* variable, ValaTargetValue* value);
	ValaTargetValue* (*load_this_parameter) (ValaCCodeBaseModule* self, ValaTypeSymbol* sym);
	void (*store_value) (ValaCCodeBaseModule* self, ValaTargetValue* lvalue, ValaTargetValue* value);
	gchar* (*get_delegate_target_cname) (ValaCCodeBaseModule* self, const gchar* delegate_cname);
	ValaCCodeExpression* (*get_delegate_target_cexpression) (ValaCCodeBaseModule* self, ValaExpression* delegate_expr, ValaCCodeExpression** delegate_target_destroy_notify);
	ValaCCodeExpression* (*get_delegate_target_cvalue) (ValaCCodeBaseModule* self, ValaTargetValue* value);
	ValaCCodeExpression* (*get_delegate_target_destroy_notify_cvalue) (ValaCCodeBaseModule* self, ValaTargetValue* value);
	gchar* (*get_delegate_target_destroy_notify_cname) (ValaCCodeBaseModule* self, const gchar* delegate_cname);
	ValaTargetValue* (*copy_value) (ValaCCodeBaseModule* self, ValaTargetValue* value, ValaCodeNode* node);
	void (*generate_class_declaration) (ValaCCodeBaseModule* self, ValaClass* cl, ValaCCodeFile* decl_space);
	void (*generate_interface_declaration) (ValaCCodeBaseModule* self, ValaInterface* iface, ValaCCodeFile* decl_space);
	void (*generate_method_declaration) (ValaCCodeBaseModule* self, ValaMethod* m, ValaCCodeFile* decl_space);
	void (*generate_error_domain_declaration) (ValaCCodeBaseModule* self, ValaErrorDomain* edomain, ValaCCodeFile* decl_space);
	ValaCCodeExpression* (*deserialize_expression) (ValaCCodeBaseModule* self, ValaDataType* type, ValaCCodeExpression* variant_expr, ValaCCodeExpression* expr, ValaCCodeExpression* error_expr, gboolean* may_fail);
	ValaCCodeExpression* (*serialize_expression) (ValaCCodeBaseModule* self, ValaDataType* type, ValaCCodeExpression* expr);
	ValaCCodeExpression* (*get_implicit_cast_expression) (ValaCCodeBaseModule* self, ValaCCodeExpression* source_cexpr, ValaDataType* expression_type, ValaDataType* target_type, ValaCodeNode* node);
	void (*create_type_check_statement) (ValaCCodeBaseModule* self, ValaCodeNode* method_node, ValaDataType* ret_type, ValaTypeSymbol* t, gboolean non_null, const gchar* var_name);
	gboolean (*is_gobject_property) (ValaCCodeBaseModule* self, ValaProperty* prop);
	void (*generate_dynamic_method_wrapper) (ValaCCodeBaseModule* self, ValaDynamicMethod* method);
	gboolean (*method_has_wrapper) (ValaCCodeBaseModule* self, ValaMethod* method);
	ValaCCodeFunctionCall* (*get_param_spec) (ValaCCodeBaseModule* self, ValaProperty* prop);
	ValaCCodeFunctionCall* (*get_signal_creation) (ValaCCodeBaseModule* self, ValaSignal* sig, ValaTypeSymbol* type);
	void (*register_dbus_info) (ValaCCodeBaseModule* self, ValaCCodeBlock* block, ValaObjectTypeSymbol* bindable);
	gchar* (*get_dynamic_property_getter_cname) (ValaCCodeBaseModule* self, ValaDynamicProperty* node);
	gchar* (*get_dynamic_property_setter_cname) (ValaCCodeBaseModule* self, ValaDynamicProperty* node);
	gchar* (*get_dynamic_signal_cname) (ValaCCodeBaseModule* self, ValaDynamicSignal* node);
	gchar* (*get_dynamic_signal_connect_wrapper_name) (ValaCCodeBaseModule* self, ValaDynamicSignal* node);
	gchar* (*get_dynamic_signal_connect_after_wrapper_name) (ValaCCodeBaseModule* self, ValaDynamicSignal* node);
	gchar* (*get_dynamic_signal_disconnect_wrapper_name) (ValaCCodeBaseModule* self, ValaDynamicSignal* node);
	gchar* (*get_array_length_cname) (ValaCCodeBaseModule* self, const gchar* array_cname, gint dim);
	gchar* (*get_parameter_array_length_cname) (ValaCCodeBaseModule* self, ValaParameter* param, gint dim);
	ValaCCodeExpression* (*get_array_length_cexpression) (ValaCCodeBaseModule* self, ValaExpression* array_expr, gint dim);
	ValaCCodeExpression* (*get_array_length_cvalue) (ValaCCodeBaseModule* self, ValaTargetValue* value, gint dim);
	gchar* (*get_array_size_cname) (ValaCCodeBaseModule* self, const gchar* array_cname);
	void (*add_simple_check) (ValaCCodeBaseModule* self, ValaCodeNode* node, gboolean always_fails);
	gchar* (*generate_ready_function) (ValaCCodeBaseModule* self, ValaMethod* m);
};

struct _ValaCCodeStructModule {
	ValaCCodeBaseModule parent_instance;
	ValaCCodeStructModulePrivate * priv;
};

struct _ValaCCodeStructModuleClass {
	ValaCCodeBaseModuleClass parent_class;
};

struct _ValaCCodeMethodModule {
	ValaCCodeStructModule parent_instance;
	ValaCCodeMethodModulePrivate * priv;
};

struct _ValaCCodeMethodModuleClass {
	ValaCCodeStructModuleClass parent_class;
	void (*generate_method_result_declaration) (ValaCCodeMethodModule* self, ValaMethod* m, ValaCCodeFile* decl_space, ValaCCodeFunction* cfunc, ValaMap* cparam_map, ValaMap* carg_map);
	ValaCCodeParameter* (*generate_parameter) (ValaCCodeMethodModule* self, ValaParameter* param, ValaCCodeFile* decl_space, ValaMap* cparam_map, ValaMap* carg_map);
};

struct _ValaCCodeControlFlowModule {
	ValaCCodeMethodModule parent_instance;
	ValaCCodeControlFlowModulePrivate * priv;
};

struct _ValaCCodeControlFlowModuleClass {
	ValaCCodeMethodModuleClass parent_class;
};

struct _ValaCCodeMemberAccessModule {
	ValaCCodeControlFlowModule parent_instance;
	ValaCCodeMemberAccessModulePrivate * priv;
};

struct _ValaCCodeMemberAccessModuleClass {
	ValaCCodeControlFlowModuleClass parent_class;
};

struct _ValaCCodeAssignmentModule {
	ValaCCodeMemberAccessModule parent_instance;
	ValaCCodeAssignmentModulePrivate * priv;
};

struct _ValaCCodeAssignmentModuleClass {
	ValaCCodeMemberAccessModuleClass parent_class;
};

struct _ValaCCodeMethodCallModule {
	ValaCCodeAssignmentModule parent_instance;
	ValaCCodeMethodCallModulePrivate * priv;
};

struct _ValaCCodeMethodCallModuleClass {
	ValaCCodeAssignmentModuleClass parent_class;
};

struct _ValaCCodeArrayModule {
	ValaCCodeMethodCallModule parent_instance;
	ValaCCodeArrayModulePrivate * priv;
};

struct _ValaCCodeArrayModuleClass {
	ValaCCodeMethodCallModuleClass parent_class;
};

struct _ValaCCodeDelegateModule {
	ValaCCodeArrayModule parent_instance;
	ValaCCodeDelegateModulePrivate * priv;
};

struct _ValaCCodeDelegateModuleClass {
	ValaCCodeArrayModuleClass parent_class;
};

struct _ValaGErrorModule {
	ValaCCodeDelegateModule parent_instance;
	ValaGErrorModulePrivate * priv;
};

struct _ValaGErrorModuleClass {
	ValaCCodeDelegateModuleClass parent_class;
	void (*return_with_exception) (ValaGErrorModule* self, ValaCCodeExpression* error_expr);
};

struct _ValaGTypeModule {
	ValaGErrorModule parent_instance;
	ValaGTypeModulePrivate * priv;
};

struct _ValaGTypeModuleClass {
	ValaGErrorModuleClass parent_class;
	void (*generate_virtual_method_declaration) (ValaGTypeModule* self, ValaMethod* m, ValaCCodeFile* decl_space, ValaCCodeStruct* type_struct);
	void (*generate_class_init) (ValaGTypeModule* self, ValaClass* cl);
};

struct _ValaGObjectModule {
	ValaGTypeModule parent_instance;
	ValaGObjectModulePrivate * priv;
};

struct _ValaGObjectModuleClass {
	ValaGTypeModuleClass parent_class;
};

struct _ValaGSignalModule {
	ValaGObjectModule parent_instance;
	ValaGSignalModulePrivate * priv;
};

struct _ValaGSignalModuleClass {
	ValaGObjectModuleClass parent_class;
};

struct _ValaGAsyncModule {
	ValaGSignalModule parent_instance;
	ValaGAsyncModulePrivate * priv;
};

struct _ValaGAsyncModuleClass {
	ValaGSignalModuleClass parent_class;
};

struct _ValaGVariantModule {
	ValaGAsyncModule parent_instance;
	ValaGVariantModulePrivate * priv;
};

struct _ValaGVariantModuleClass {
	ValaGAsyncModuleClass parent_class;
};

struct _ValaGDBusModule {
	ValaGVariantModule parent_instance;
	ValaGDBusModulePrivate * priv;
};

struct _ValaGDBusModuleClass {
	ValaGVariantModuleClass parent_class;
};


static gpointer vala_gd_bus_module_parent_class = NULL;

GType vala_ccode_base_module_get_type (void) G_GNUC_CONST;
gpointer vala_ccode_base_module_emit_context_ref (gpointer instance);
void vala_ccode_base_module_emit_context_unref (gpointer instance);
GParamSpec* vala_ccode_base_module_param_spec_emit_context (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void vala_ccode_base_module_value_set_emit_context (GValue* value, gpointer v_object);
void vala_ccode_base_module_value_take_emit_context (GValue* value, gpointer v_object);
gpointer vala_ccode_base_module_value_get_emit_context (const GValue* value);
GType vala_ccode_base_module_emit_context_get_type (void) G_GNUC_CONST;
GType vala_ccode_struct_module_get_type (void) G_GNUC_CONST;
GType vala_ccode_method_module_get_type (void) G_GNUC_CONST;
GType vala_ccode_control_flow_module_get_type (void) G_GNUC_CONST;
GType vala_ccode_member_access_module_get_type (void) G_GNUC_CONST;
GType vala_ccode_assignment_module_get_type (void) G_GNUC_CONST;
GType vala_ccode_method_call_module_get_type (void) G_GNUC_CONST;
GType vala_ccode_array_module_get_type (void) G_GNUC_CONST;
GType vala_ccode_delegate_module_get_type (void) G_GNUC_CONST;
GType vala_gerror_module_get_type (void) G_GNUC_CONST;
GType vala_gtype_module_get_type (void) G_GNUC_CONST;
GType vala_gobject_module_get_type (void) G_GNUC_CONST;
GType vala_gsignal_module_get_type (void) G_GNUC_CONST;
GType vala_gasync_module_get_type (void) G_GNUC_CONST;
GType vala_gvariant_module_get_type (void) G_GNUC_CONST;
GType vala_gd_bus_module_get_type (void) G_GNUC_CONST;
enum  {
	VALA_GD_BUS_MODULE_DUMMY_PROPERTY
};
gchar* vala_gd_bus_module_get_dbus_name (ValaTypeSymbol* symbol);
gchar* vala_gd_bus_module_get_dbus_name_for_member (ValaSymbol* symbol);
gboolean vala_gd_bus_module_is_dbus_no_reply (ValaMethod* m);
static void vala_gd_bus_module_real_visit_error_domain (ValaCodeVisitor* base, ValaErrorDomain* edomain);
void vala_ccode_base_module_generate_error_domain_declaration (ValaCCodeBaseModule* self, ValaErrorDomain* edomain, ValaCCodeFile* decl_space);
gchar* vala_ccode_base_module_get_ccode_name (ValaCodeNode* node);
gchar* vala_ccode_base_module_get_ccode_lower_case_name (ValaCodeNode* node, const gchar* infix);
gchar* vala_ccode_base_module_get_ccode_lower_case_prefix (ValaSymbol* sym);
void vala_ccode_base_module_push_function (ValaCCodeBaseModule* self, ValaCCodeFunction* func);
ValaCCodeFunction* vala_ccode_base_module_get_ccode (ValaCCodeBaseModule* self);
void vala_ccode_base_module_pop_function (ValaCCodeBaseModule* self);
static gboolean vala_gd_bus_module_is_file_descriptor (ValaGDBusModule* self, ValaDataType* type);
gboolean vala_gd_bus_module_dbus_method_uses_file_descriptor (ValaGDBusModule* self, ValaMethod* method);
static ValaCCodeExpression* vala_gd_bus_module_get_file_descriptor (ValaGDBusModule* self, ValaDataType* type, ValaCCodeExpression* expr);
void vala_gd_bus_module_send_dbus_value (ValaGDBusModule* self, ValaDataType* type, ValaCCodeExpression* builder_expr, ValaCCodeExpression* expr, ValaSymbol* sym);
void vala_gvariant_module_write_expression (ValaGVariantModule* self, ValaDataType* type, ValaCCodeExpression* builder_expr, ValaCCodeExpression* expr, ValaSymbol* sym);
static ValaCCodeExpression* vala_gd_bus_module_create_from_file_descriptor (ValaGDBusModule* self, ValaDataType* type, ValaCCodeExpression* expr);
void vala_gd_bus_module_receive_dbus_value (ValaGDBusModule* self, ValaDataType* type, ValaCCodeExpression* message_expr, ValaCCodeExpression* iter_expr, ValaCCodeExpression* target_expr, ValaSymbol* sym, ValaCCodeExpression* error_expr, gboolean* may_fail);
void vala_gvariant_module_read_expression (ValaGVariantModule* self, ValaDataType* type, ValaCCodeExpression* iter_expr, ValaCCodeExpression* target_expr, ValaSymbol* sym, ValaCCodeExpression* error_expr, gboolean* may_fail);
ValaGDBusModule* vala_gd_bus_module_new (void);
ValaGDBusModule* vala_gd_bus_module_construct (GType object_type);
ValaGVariantModule* vala_gvariant_module_new (void);
ValaGVariantModule* vala_gvariant_module_construct (GType object_type);


gchar* vala_gd_bus_module_get_dbus_name (ValaTypeSymbol* symbol) {
	gchar* result = NULL;
	ValaTypeSymbol* _tmp0_;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (symbol != NULL, NULL);
	_tmp0_ = symbol;
	_tmp1_ = vala_code_node_get_attribute_string ((ValaCodeNode*) _tmp0_, "DBus", "name");
	result = _tmp1_;
	return result;
}


gchar* vala_gd_bus_module_get_dbus_name_for_member (ValaSymbol* symbol) {
	gchar* result = NULL;
	ValaSymbol* _tmp0_;
	gchar* _tmp1_ = NULL;
	gchar* dbus_name;
	const gchar* _tmp2_;
	ValaSymbol* _tmp3_;
	const gchar* _tmp4_;
	const gchar* _tmp5_;
	gchar* _tmp6_ = NULL;
	g_return_val_if_fail (symbol != NULL, NULL);
	_tmp0_ = symbol;
	_tmp1_ = vala_code_node_get_attribute_string ((ValaCodeNode*) _tmp0_, "DBus", "name");
	dbus_name = _tmp1_;
	_tmp2_ = dbus_name;
	if (_tmp2_ != NULL) {
		result = dbus_name;
		return result;
	}
	_tmp3_ = symbol;
	_tmp4_ = vala_symbol_get_name (_tmp3_);
	_tmp5_ = _tmp4_;
	_tmp6_ = vala_symbol_lower_case_to_camel_case (_tmp5_);
	result = _tmp6_;
	_g_free0 (dbus_name);
	return result;
}


gboolean vala_gd_bus_module_is_dbus_no_reply (ValaMethod* m) {
	gboolean result = FALSE;
	ValaMethod* _tmp0_;
	gboolean _tmp1_ = FALSE;
	g_return_val_if_fail (m != NULL, FALSE);
	_tmp0_ = m;
	_tmp1_ = vala_code_node_get_attribute_bool ((ValaCodeNode*) _tmp0_, "DBus", "no_reply", FALSE);
	result = _tmp1_;
	return result;
}


static void vala_gd_bus_module_real_visit_error_domain (ValaCodeVisitor* base, ValaErrorDomain* edomain) {
	ValaGDBusModule * self;
	ValaErrorDomain* _tmp0_;
	gchar* _tmp1_ = NULL;
	gchar* edomain_dbus_name;
	const gchar* _tmp2_;
	ValaCCodeFile* _tmp4_;
	ValaErrorDomain* _tmp5_;
	ValaCCodeFile* _tmp6_;
	ValaErrorDomain* _tmp7_;
	gboolean _tmp8_ = FALSE;
	ValaErrorDomain* _tmp11_;
	gboolean _tmp12_ = FALSE;
	ValaCCodeInitializerList* _tmp15_;
	ValaCCodeInitializerList* error_entries;
	ValaCCodeDeclaration* _tmp52_;
	ValaCCodeDeclaration* _cdecl_;
	ValaCCodeDeclaration* _tmp53_;
	ValaErrorDomain* _tmp54_;
	gchar* _tmp55_ = NULL;
	gchar* _tmp56_;
	gchar* _tmp57_;
	gchar* _tmp58_;
	ValaCCodeInitializerList* _tmp59_;
	ValaCCodeVariableDeclarator* _tmp60_;
	ValaCCodeVariableDeclarator* _tmp61_;
	ValaCCodeDeclaration* _tmp62_;
	ValaCCodeFile* _tmp63_;
	ValaCCodeDeclaration* _tmp64_;
	ValaErrorDomain* _tmp65_;
	gchar* _tmp66_ = NULL;
	gchar* _tmp67_;
	gchar* _tmp68_;
	gchar* _tmp69_;
	gchar* quark_fun_name;
	const gchar* _tmp70_;
	ValaDataType* _tmp71_;
	ValaTypeSymbol* _tmp72_;
	ValaTypeSymbol* _tmp73_;
	gchar* _tmp74_ = NULL;
	gchar* _tmp75_;
	ValaCCodeFunction* _tmp76_;
	ValaCCodeFunction* _tmp77_;
	ValaCCodeFunction* cquark_fun;
	ValaCCodeFunction* _tmp78_;
	ValaErrorDomain* _tmp79_;
	gchar* _tmp80_ = NULL;
	gchar* _tmp81_;
	gchar* _tmp82_ = NULL;
	gchar* _tmp83_;
	gchar* quark_name;
	ValaCCodeFunction* _tmp84_;
	ValaCCodeFunction* _tmp85_;
	const gchar* _tmp86_;
	ValaCCodeConstant* _tmp87_;
	ValaCCodeConstant* _tmp88_;
	ValaCCodeVariableDeclarator* _tmp89_;
	ValaCCodeVariableDeclarator* _tmp90_;
	ValaCCodeIdentifier* _tmp91_;
	ValaCCodeIdentifier* _tmp92_;
	ValaCCodeFunctionCall* _tmp93_;
	ValaCCodeFunctionCall* _tmp94_;
	ValaCCodeFunctionCall* register_call;
	ValaCCodeFunctionCall* _tmp95_;
	ValaErrorDomain* _tmp96_;
	gchar* _tmp97_ = NULL;
	gchar* _tmp98_;
	gchar* _tmp99_;
	gchar* _tmp100_;
	gchar* _tmp101_;
	gchar* _tmp102_;
	ValaCCodeConstant* _tmp103_;
	ValaCCodeConstant* _tmp104_;
	ValaCCodeFunctionCall* _tmp105_;
	const gchar* _tmp106_;
	ValaCCodeIdentifier* _tmp107_;
	ValaCCodeIdentifier* _tmp108_;
	ValaCCodeUnaryExpression* _tmp109_;
	ValaCCodeUnaryExpression* _tmp110_;
	ValaCCodeFunctionCall* _tmp111_;
	ValaErrorDomain* _tmp112_;
	gchar* _tmp113_ = NULL;
	gchar* _tmp114_;
	gchar* _tmp115_;
	gchar* _tmp116_;
	ValaCCodeIdentifier* _tmp117_;
	ValaCCodeIdentifier* _tmp118_;
	ValaCCodeIdentifier* _tmp119_;
	ValaCCodeIdentifier* _tmp120_;
	ValaCCodeFunctionCall* _tmp121_;
	ValaCCodeFunctionCall* _tmp122_;
	ValaCCodeFunctionCall* nentries;
	ValaCCodeFunctionCall* _tmp123_;
	ValaErrorDomain* _tmp124_;
	gchar* _tmp125_ = NULL;
	gchar* _tmp126_;
	gchar* _tmp127_;
	gchar* _tmp128_;
	ValaCCodeIdentifier* _tmp129_;
	ValaCCodeIdentifier* _tmp130_;
	ValaCCodeFunctionCall* _tmp131_;
	ValaCCodeFunctionCall* _tmp132_;
	ValaCCodeFunction* _tmp133_;
	ValaCCodeFunction* _tmp134_;
	ValaCCodeFunctionCall* _tmp135_;
	ValaCCodeFunction* _tmp136_;
	ValaCCodeFunction* _tmp137_;
	const gchar* _tmp138_;
	ValaCCodeIdentifier* _tmp139_;
	ValaCCodeIdentifier* _tmp140_;
	ValaCCodeCastExpression* _tmp141_;
	ValaCCodeCastExpression* _tmp142_;
	ValaCCodeFile* _tmp143_;
	ValaCCodeFunction* _tmp144_;
	self = (ValaGDBusModule*) base;
	g_return_if_fail (edomain != NULL);
	_tmp0_ = edomain;
	_tmp1_ = vala_gd_bus_module_get_dbus_name ((ValaTypeSymbol*) _tmp0_);
	edomain_dbus_name = _tmp1_;
	_tmp2_ = edomain_dbus_name;
	if (_tmp2_ == NULL) {
		ValaErrorDomain* _tmp3_;
		_tmp3_ = edomain;
		VALA_CODE_VISITOR_CLASS (vala_gd_bus_module_parent_class)->visit_error_domain ((ValaCodeVisitor*) G_TYPE_CHECK_INSTANCE_CAST (self, VALA_TYPE_GVARIANT_MODULE, ValaGVariantModule), _tmp3_);
		_g_free0 (edomain_dbus_name);
		return;
	}
	_tmp4_ = ((ValaCCodeBaseModule*) self)->cfile;
	vala_ccode_file_add_include (_tmp4_, "gio/gio.h", FALSE);
	_tmp5_ = edomain;
	_tmp6_ = ((ValaCCodeBaseModule*) self)->cfile;
	vala_ccode_base_module_generate_error_domain_declaration ((ValaCCodeBaseModule*) self, _tmp5_, _tmp6_);
	_tmp7_ = edomain;
	_tmp8_ = vala_symbol_is_internal_symbol ((ValaSymbol*) _tmp7_);
	if (!_tmp8_) {
		ValaErrorDomain* _tmp9_;
		ValaCCodeFile* _tmp10_;
		_tmp9_ = edomain;
		_tmp10_ = ((ValaCCodeBaseModule*) self)->header_file;
		vala_ccode_base_module_generate_error_domain_declaration ((ValaCCodeBaseModule*) self, _tmp9_, _tmp10_);
	}
	_tmp11_ = edomain;
	_tmp12_ = vala_symbol_is_private_symbol ((ValaSymbol*) _tmp11_);
	if (!_tmp12_) {
		ValaErrorDomain* _tmp13_;
		ValaCCodeFile* _tmp14_;
		_tmp13_ = edomain;
		_tmp14_ = ((ValaCCodeBaseModule*) self)->internal_header_file;
		vala_ccode_base_module_generate_error_domain_declaration ((ValaCCodeBaseModule*) self, _tmp13_, _tmp14_);
	}
	_tmp15_ = vala_ccode_initializer_list_new ();
	error_entries = _tmp15_;
	{
		ValaErrorDomain* _tmp16_;
		ValaList* _tmp17_ = NULL;
		ValaList* _ecode_list;
		ValaList* _tmp18_;
		gint _tmp19_;
		gint _tmp20_;
		gint _ecode_size;
		gint _ecode_index;
		_tmp16_ = edomain;
		_tmp17_ = vala_error_domain_get_codes (_tmp16_);
		_ecode_list = _tmp17_;
		_tmp18_ = _ecode_list;
		_tmp19_ = vala_collection_get_size ((ValaCollection*) _tmp18_);
		_tmp20_ = _tmp19_;
		_ecode_size = _tmp20_;
		_ecode_index = -1;
		while (TRUE) {
			gint _tmp21_;
			gint _tmp22_;
			gint _tmp23_;
			ValaList* _tmp24_;
			gint _tmp25_;
			gpointer _tmp26_ = NULL;
			ValaErrorCode* ecode;
			ValaErrorCode* _tmp27_;
			gchar* _tmp28_ = NULL;
			gchar* ecode_dbus_name;
			const gchar* _tmp29_;
			ValaCCodeInitializerList* _tmp36_;
			ValaCCodeInitializerList* error_entry;
			ValaCCodeInitializerList* _tmp37_;
			ValaErrorCode* _tmp38_;
			gchar* _tmp39_ = NULL;
			gchar* _tmp40_;
			ValaCCodeIdentifier* _tmp41_;
			ValaCCodeIdentifier* _tmp42_;
			ValaCCodeInitializerList* _tmp43_;
			const gchar* _tmp44_;
			const gchar* _tmp45_;
			gchar* _tmp46_ = NULL;
			gchar* _tmp47_;
			ValaCCodeConstant* _tmp48_;
			ValaCCodeConstant* _tmp49_;
			ValaCCodeInitializerList* _tmp50_;
			ValaCCodeInitializerList* _tmp51_;
			_tmp21_ = _ecode_index;
			_ecode_index = _tmp21_ + 1;
			_tmp22_ = _ecode_index;
			_tmp23_ = _ecode_size;
			if (!(_tmp22_ < _tmp23_)) {
				break;
			}
			_tmp24_ = _ecode_list;
			_tmp25_ = _ecode_index;
			_tmp26_ = vala_list_get (_tmp24_, _tmp25_);
			ecode = (ValaErrorCode*) _tmp26_;
			_tmp27_ = ecode;
			_tmp28_ = vala_gd_bus_module_get_dbus_name ((ValaTypeSymbol*) _tmp27_);
			ecode_dbus_name = _tmp28_;
			_tmp29_ = ecode_dbus_name;
			if (_tmp29_ == NULL) {
				ValaErrorCode* _tmp30_;
				const gchar* _tmp31_;
				const gchar* _tmp32_;
				gchar* _tmp33_ = NULL;
				gchar* _tmp34_;
				gchar* _tmp35_ = NULL;
				_tmp30_ = ecode;
				_tmp31_ = vala_symbol_get_name ((ValaSymbol*) _tmp30_);
				_tmp32_ = _tmp31_;
				_tmp33_ = g_utf8_strdown (_tmp32_, (gssize) (-1));
				_tmp34_ = _tmp33_;
				_tmp35_ = vala_symbol_lower_case_to_camel_case (_tmp34_);
				_g_free0 (ecode_dbus_name);
				ecode_dbus_name = _tmp35_;
				_g_free0 (_tmp34_);
			}
			_tmp36_ = vala_ccode_initializer_list_new ();
			error_entry = _tmp36_;
			_tmp37_ = error_entry;
			_tmp38_ = ecode;
			_tmp39_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp38_);
			_tmp40_ = _tmp39_;
			_tmp41_ = vala_ccode_identifier_new (_tmp40_);
			_tmp42_ = _tmp41_;
			vala_ccode_initializer_list_append (_tmp37_, (ValaCCodeExpression*) _tmp42_);
			_vala_ccode_node_unref0 (_tmp42_);
			_g_free0 (_tmp40_);
			_tmp43_ = error_entry;
			_tmp44_ = edomain_dbus_name;
			_tmp45_ = ecode_dbus_name;
			_tmp46_ = g_strdup_printf ("\"%s.%s\"", _tmp44_, _tmp45_);
			_tmp47_ = _tmp46_;
			_tmp48_ = vala_ccode_constant_new (_tmp47_);
			_tmp49_ = _tmp48_;
			vala_ccode_initializer_list_append (_tmp43_, (ValaCCodeExpression*) _tmp49_);
			_vala_ccode_node_unref0 (_tmp49_);
			_g_free0 (_tmp47_);
			_tmp50_ = error_entries;
			_tmp51_ = error_entry;
			vala_ccode_initializer_list_append (_tmp50_, (ValaCCodeExpression*) _tmp51_);
			_vala_ccode_node_unref0 (error_entry);
			_g_free0 (ecode_dbus_name);
			_vala_code_node_unref0 (ecode);
		}
		_vala_iterable_unref0 (_ecode_list);
	}
	_tmp52_ = vala_ccode_declaration_new ("const GDBusErrorEntry");
	_cdecl_ = _tmp52_;
	_tmp53_ = _cdecl_;
	_tmp54_ = edomain;
	_tmp55_ = vala_ccode_base_module_get_ccode_lower_case_name ((ValaCodeNode*) _tmp54_, NULL);
	_tmp56_ = _tmp55_;
	_tmp57_ = g_strconcat (_tmp56_, "_entries[]", NULL);
	_tmp58_ = _tmp57_;
	_tmp59_ = error_entries;
	_tmp60_ = vala_ccode_variable_declarator_new (_tmp58_, (ValaCCodeExpression*) _tmp59_, NULL);
	_tmp61_ = _tmp60_;
	vala_ccode_declaration_add_declarator (_tmp53_, (ValaCCodeDeclarator*) _tmp61_);
	_vala_ccode_node_unref0 (_tmp61_);
	_g_free0 (_tmp58_);
	_g_free0 (_tmp56_);
	_tmp62_ = _cdecl_;
	vala_ccode_declaration_set_modifiers (_tmp62_, VALA_CCODE_MODIFIERS_STATIC);
	_tmp63_ = ((ValaCCodeBaseModule*) self)->cfile;
	_tmp64_ = _cdecl_;
	vala_ccode_file_add_constant_declaration (_tmp63_, (ValaCCodeNode*) _tmp64_);
	_tmp65_ = edomain;
	_tmp66_ = vala_ccode_base_module_get_ccode_lower_case_prefix ((ValaSymbol*) _tmp65_);
	_tmp67_ = _tmp66_;
	_tmp68_ = g_strconcat (_tmp67_, "quark", NULL);
	_tmp69_ = _tmp68_;
	_g_free0 (_tmp67_);
	quark_fun_name = _tmp69_;
	_tmp70_ = quark_fun_name;
	_tmp71_ = ((ValaCCodeBaseModule*) self)->gquark_type;
	_tmp72_ = vala_data_type_get_data_type (_tmp71_);
	_tmp73_ = _tmp72_;
	_tmp74_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp73_);
	_tmp75_ = _tmp74_;
	_tmp76_ = vala_ccode_function_new (_tmp70_, _tmp75_);
	_tmp77_ = _tmp76_;
	_g_free0 (_tmp75_);
	cquark_fun = _tmp77_;
	_tmp78_ = cquark_fun;
	vala_ccode_base_module_push_function ((ValaCCodeBaseModule*) self, _tmp78_);
	_tmp79_ = edomain;
	_tmp80_ = vala_ccode_base_module_get_ccode_lower_case_prefix ((ValaSymbol*) _tmp79_);
	_tmp81_ = _tmp80_;
	_tmp82_ = g_strdup_printf ("%squark_volatile", _tmp81_);
	_tmp83_ = _tmp82_;
	_g_free0 (_tmp81_);
	quark_name = _tmp83_;
	_tmp84_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp85_ = _tmp84_;
	_tmp86_ = quark_name;
	_tmp87_ = vala_ccode_constant_new ("0");
	_tmp88_ = _tmp87_;
	_tmp89_ = vala_ccode_variable_declarator_new (_tmp86_, (ValaCCodeExpression*) _tmp88_, NULL);
	_tmp90_ = _tmp89_;
	vala_ccode_function_add_declaration (_tmp85_, "gsize", (ValaCCodeDeclarator*) _tmp90_, VALA_CCODE_MODIFIERS_STATIC | VALA_CCODE_MODIFIERS_VOLATILE);
	_vala_ccode_node_unref0 (_tmp90_);
	_vala_ccode_node_unref0 (_tmp88_);
	_tmp91_ = vala_ccode_identifier_new ("g_dbus_error_register_error_domain");
	_tmp92_ = _tmp91_;
	_tmp93_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp92_);
	_tmp94_ = _tmp93_;
	_vala_ccode_node_unref0 (_tmp92_);
	register_call = _tmp94_;
	_tmp95_ = register_call;
	_tmp96_ = edomain;
	_tmp97_ = vala_ccode_base_module_get_ccode_lower_case_name ((ValaCodeNode*) _tmp96_, NULL);
	_tmp98_ = _tmp97_;
	_tmp99_ = g_strconcat ("\"", _tmp98_, NULL);
	_tmp100_ = _tmp99_;
	_tmp101_ = g_strconcat (_tmp100_, "-quark\"", NULL);
	_tmp102_ = _tmp101_;
	_tmp103_ = vala_ccode_constant_new (_tmp102_);
	_tmp104_ = _tmp103_;
	vala_ccode_function_call_add_argument (_tmp95_, (ValaCCodeExpression*) _tmp104_);
	_vala_ccode_node_unref0 (_tmp104_);
	_g_free0 (_tmp102_);
	_g_free0 (_tmp100_);
	_g_free0 (_tmp98_);
	_tmp105_ = register_call;
	_tmp106_ = quark_name;
	_tmp107_ = vala_ccode_identifier_new (_tmp106_);
	_tmp108_ = _tmp107_;
	_tmp109_ = vala_ccode_unary_expression_new (VALA_CCODE_UNARY_OPERATOR_ADDRESS_OF, (ValaCCodeExpression*) _tmp108_);
	_tmp110_ = _tmp109_;
	vala_ccode_function_call_add_argument (_tmp105_, (ValaCCodeExpression*) _tmp110_);
	_vala_ccode_node_unref0 (_tmp110_);
	_vala_ccode_node_unref0 (_tmp108_);
	_tmp111_ = register_call;
	_tmp112_ = edomain;
	_tmp113_ = vala_ccode_base_module_get_ccode_lower_case_name ((ValaCodeNode*) _tmp112_, NULL);
	_tmp114_ = _tmp113_;
	_tmp115_ = g_strconcat (_tmp114_, "_entries", NULL);
	_tmp116_ = _tmp115_;
	_tmp117_ = vala_ccode_identifier_new (_tmp116_);
	_tmp118_ = _tmp117_;
	vala_ccode_function_call_add_argument (_tmp111_, (ValaCCodeExpression*) _tmp118_);
	_vala_ccode_node_unref0 (_tmp118_);
	_g_free0 (_tmp116_);
	_g_free0 (_tmp114_);
	_tmp119_ = vala_ccode_identifier_new ("G_N_ELEMENTS");
	_tmp120_ = _tmp119_;
	_tmp121_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp120_);
	_tmp122_ = _tmp121_;
	_vala_ccode_node_unref0 (_tmp120_);
	nentries = _tmp122_;
	_tmp123_ = nentries;
	_tmp124_ = edomain;
	_tmp125_ = vala_ccode_base_module_get_ccode_lower_case_name ((ValaCodeNode*) _tmp124_, NULL);
	_tmp126_ = _tmp125_;
	_tmp127_ = g_strconcat (_tmp126_, "_entries", NULL);
	_tmp128_ = _tmp127_;
	_tmp129_ = vala_ccode_identifier_new (_tmp128_);
	_tmp130_ = _tmp129_;
	vala_ccode_function_call_add_argument (_tmp123_, (ValaCCodeExpression*) _tmp130_);
	_vala_ccode_node_unref0 (_tmp130_);
	_g_free0 (_tmp128_);
	_g_free0 (_tmp126_);
	_tmp131_ = register_call;
	_tmp132_ = nentries;
	vala_ccode_function_call_add_argument (_tmp131_, (ValaCCodeExpression*) _tmp132_);
	_tmp133_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp134_ = _tmp133_;
	_tmp135_ = register_call;
	vala_ccode_function_add_expression (_tmp134_, (ValaCCodeExpression*) _tmp135_);
	_tmp136_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp137_ = _tmp136_;
	_tmp138_ = quark_name;
	_tmp139_ = vala_ccode_identifier_new (_tmp138_);
	_tmp140_ = _tmp139_;
	_tmp141_ = vala_ccode_cast_expression_new ((ValaCCodeExpression*) _tmp140_, "GQuark");
	_tmp142_ = _tmp141_;
	vala_ccode_function_add_return (_tmp137_, (ValaCCodeExpression*) _tmp142_);
	_vala_ccode_node_unref0 (_tmp142_);
	_vala_ccode_node_unref0 (_tmp140_);
	vala_ccode_base_module_pop_function ((ValaCCodeBaseModule*) self);
	_tmp143_ = ((ValaCCodeBaseModule*) self)->cfile;
	_tmp144_ = cquark_fun;
	vala_ccode_file_add_function (_tmp143_, _tmp144_);
	_vala_ccode_node_unref0 (nentries);
	_vala_ccode_node_unref0 (register_call);
	_g_free0 (quark_name);
	_vala_ccode_node_unref0 (cquark_fun);
	_g_free0 (quark_fun_name);
	_vala_ccode_node_unref0 (_cdecl_);
	_vala_ccode_node_unref0 (error_entries);
	_g_free0 (edomain_dbus_name);
}


static gboolean vala_gd_bus_module_is_file_descriptor (ValaGDBusModule* self, ValaDataType* type) {
	gboolean result = FALSE;
	ValaDataType* _tmp0_;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (type != NULL, FALSE);
	_tmp0_ = type;
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp0_, VALA_TYPE_OBJECT_TYPE)) {
		gboolean _tmp1_ = FALSE;
		gboolean _tmp2_ = FALSE;
		gboolean _tmp3_ = FALSE;
		ValaDataType* _tmp4_;
		ValaTypeSymbol* _tmp5_;
		ValaTypeSymbol* _tmp6_;
		gchar* _tmp7_ = NULL;
		gchar* _tmp8_;
		gboolean _tmp9_;
		gboolean _tmp15_;
		gboolean _tmp21_;
		gboolean _tmp27_;
		_tmp4_ = type;
		_tmp5_ = vala_data_type_get_data_type (_tmp4_);
		_tmp6_ = _tmp5_;
		_tmp7_ = vala_symbol_get_full_name ((ValaSymbol*) _tmp6_);
		_tmp8_ = _tmp7_;
		_tmp9_ = g_strcmp0 (_tmp8_, "GLib.UnixInputStream") == 0;
		_g_free0 (_tmp8_);
		if (_tmp9_) {
			_tmp3_ = TRUE;
		} else {
			ValaDataType* _tmp10_;
			ValaTypeSymbol* _tmp11_;
			ValaTypeSymbol* _tmp12_;
			gchar* _tmp13_ = NULL;
			gchar* _tmp14_;
			_tmp10_ = type;
			_tmp11_ = vala_data_type_get_data_type (_tmp10_);
			_tmp12_ = _tmp11_;
			_tmp13_ = vala_symbol_get_full_name ((ValaSymbol*) _tmp12_);
			_tmp14_ = _tmp13_;
			_tmp3_ = g_strcmp0 (_tmp14_, "GLib.UnixOutputStream") == 0;
			_g_free0 (_tmp14_);
		}
		_tmp15_ = _tmp3_;
		if (_tmp15_) {
			_tmp2_ = TRUE;
		} else {
			ValaDataType* _tmp16_;
			ValaTypeSymbol* _tmp17_;
			ValaTypeSymbol* _tmp18_;
			gchar* _tmp19_ = NULL;
			gchar* _tmp20_;
			_tmp16_ = type;
			_tmp17_ = vala_data_type_get_data_type (_tmp16_);
			_tmp18_ = _tmp17_;
			_tmp19_ = vala_symbol_get_full_name ((ValaSymbol*) _tmp18_);
			_tmp20_ = _tmp19_;
			_tmp2_ = g_strcmp0 (_tmp20_, "GLib.Socket") == 0;
			_g_free0 (_tmp20_);
		}
		_tmp21_ = _tmp2_;
		if (_tmp21_) {
			_tmp1_ = TRUE;
		} else {
			ValaDataType* _tmp22_;
			ValaTypeSymbol* _tmp23_;
			ValaTypeSymbol* _tmp24_;
			gchar* _tmp25_ = NULL;
			gchar* _tmp26_;
			_tmp22_ = type;
			_tmp23_ = vala_data_type_get_data_type (_tmp22_);
			_tmp24_ = _tmp23_;
			_tmp25_ = vala_symbol_get_full_name ((ValaSymbol*) _tmp24_);
			_tmp26_ = _tmp25_;
			_tmp1_ = g_strcmp0 (_tmp26_, "GLib.FileDescriptorBased") == 0;
			_g_free0 (_tmp26_);
		}
		_tmp27_ = _tmp1_;
		if (_tmp27_) {
			result = TRUE;
			return result;
		}
	}
	result = FALSE;
	return result;
}


gboolean vala_gd_bus_module_dbus_method_uses_file_descriptor (ValaGDBusModule* self, ValaMethod* method) {
	gboolean result = FALSE;
	ValaMethod* _tmp15_;
	ValaDataType* _tmp16_;
	ValaDataType* _tmp17_;
	gboolean _tmp18_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (method != NULL, FALSE);
	{
		ValaMethod* _tmp0_;
		ValaList* _tmp1_ = NULL;
		ValaList* _param_list;
		ValaList* _tmp2_;
		gint _tmp3_;
		gint _tmp4_;
		gint _param_size;
		gint _param_index;
		_tmp0_ = method;
		_tmp1_ = vala_method_get_parameters (_tmp0_);
		_param_list = _tmp1_;
		_tmp2_ = _param_list;
		_tmp3_ = vala_collection_get_size ((ValaCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_param_size = _tmp4_;
		_param_index = -1;
		while (TRUE) {
			gint _tmp5_;
			gint _tmp6_;
			gint _tmp7_;
			ValaList* _tmp8_;
			gint _tmp9_;
			gpointer _tmp10_ = NULL;
			ValaParameter* param;
			ValaParameter* _tmp11_;
			ValaDataType* _tmp12_;
			ValaDataType* _tmp13_;
			gboolean _tmp14_ = FALSE;
			_tmp5_ = _param_index;
			_param_index = _tmp5_ + 1;
			_tmp6_ = _param_index;
			_tmp7_ = _param_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _param_list;
			_tmp9_ = _param_index;
			_tmp10_ = vala_list_get (_tmp8_, _tmp9_);
			param = (ValaParameter*) _tmp10_;
			_tmp11_ = param;
			_tmp12_ = vala_variable_get_variable_type ((ValaVariable*) _tmp11_);
			_tmp13_ = _tmp12_;
			_tmp14_ = vala_gd_bus_module_is_file_descriptor (self, _tmp13_);
			if (_tmp14_) {
				result = TRUE;
				_vala_code_node_unref0 (param);
				_vala_iterable_unref0 (_param_list);
				return result;
			}
			_vala_code_node_unref0 (param);
		}
		_vala_iterable_unref0 (_param_list);
	}
	_tmp15_ = method;
	_tmp16_ = vala_method_get_return_type (_tmp15_);
	_tmp17_ = _tmp16_;
	_tmp18_ = vala_gd_bus_module_is_file_descriptor (self, _tmp17_);
	if (_tmp18_) {
		result = TRUE;
		return result;
	}
	result = FALSE;
	return result;
}


static ValaCCodeExpression* vala_gd_bus_module_get_file_descriptor (ValaGDBusModule* self, ValaDataType* type, ValaCCodeExpression* expr) {
	ValaCCodeExpression* result = NULL;
	ValaDataType* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (type != NULL, NULL);
	g_return_val_if_fail (expr != NULL, NULL);
	_tmp0_ = type;
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp0_, VALA_TYPE_OBJECT_TYPE)) {
		ValaDataType* _tmp1_;
		ValaTypeSymbol* _tmp2_;
		ValaTypeSymbol* _tmp3_;
		gchar* _tmp4_ = NULL;
		gchar* _tmp5_;
		gboolean _tmp6_;
		_tmp1_ = type;
		_tmp2_ = vala_data_type_get_data_type (_tmp1_);
		_tmp3_ = _tmp2_;
		_tmp4_ = vala_symbol_get_full_name ((ValaSymbol*) _tmp3_);
		_tmp5_ = _tmp4_;
		_tmp6_ = g_strcmp0 (_tmp5_, "GLib.UnixInputStream") == 0;
		_g_free0 (_tmp5_);
		if (_tmp6_) {
			ValaCCodeIdentifier* _tmp7_;
			ValaCCodeIdentifier* _tmp8_;
			ValaCCodeFunctionCall* _tmp9_;
			ValaCCodeFunctionCall* _tmp10_;
			ValaCCodeFunctionCall* _result_;
			ValaCCodeFunctionCall* _tmp11_;
			ValaCCodeExpression* _tmp12_;
			_tmp7_ = vala_ccode_identifier_new ("g_unix_input_stream_get_fd");
			_tmp8_ = _tmp7_;
			_tmp9_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp8_);
			_tmp10_ = _tmp9_;
			_vala_ccode_node_unref0 (_tmp8_);
			_result_ = _tmp10_;
			_tmp11_ = _result_;
			_tmp12_ = expr;
			vala_ccode_function_call_add_argument (_tmp11_, _tmp12_);
			result = (ValaCCodeExpression*) _result_;
			return result;
		} else {
			ValaDataType* _tmp13_;
			ValaTypeSymbol* _tmp14_;
			ValaTypeSymbol* _tmp15_;
			gchar* _tmp16_ = NULL;
			gchar* _tmp17_;
			gboolean _tmp18_;
			_tmp13_ = type;
			_tmp14_ = vala_data_type_get_data_type (_tmp13_);
			_tmp15_ = _tmp14_;
			_tmp16_ = vala_symbol_get_full_name ((ValaSymbol*) _tmp15_);
			_tmp17_ = _tmp16_;
			_tmp18_ = g_strcmp0 (_tmp17_, "GLib.UnixOutputStream") == 0;
			_g_free0 (_tmp17_);
			if (_tmp18_) {
				ValaCCodeIdentifier* _tmp19_;
				ValaCCodeIdentifier* _tmp20_;
				ValaCCodeFunctionCall* _tmp21_;
				ValaCCodeFunctionCall* _tmp22_;
				ValaCCodeFunctionCall* _result_;
				ValaCCodeFunctionCall* _tmp23_;
				ValaCCodeExpression* _tmp24_;
				_tmp19_ = vala_ccode_identifier_new ("g_unix_output_stream_get_fd");
				_tmp20_ = _tmp19_;
				_tmp21_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp20_);
				_tmp22_ = _tmp21_;
				_vala_ccode_node_unref0 (_tmp20_);
				_result_ = _tmp22_;
				_tmp23_ = _result_;
				_tmp24_ = expr;
				vala_ccode_function_call_add_argument (_tmp23_, _tmp24_);
				result = (ValaCCodeExpression*) _result_;
				return result;
			} else {
				ValaDataType* _tmp25_;
				ValaTypeSymbol* _tmp26_;
				ValaTypeSymbol* _tmp27_;
				gchar* _tmp28_ = NULL;
				gchar* _tmp29_;
				gboolean _tmp30_;
				_tmp25_ = type;
				_tmp26_ = vala_data_type_get_data_type (_tmp25_);
				_tmp27_ = _tmp26_;
				_tmp28_ = vala_symbol_get_full_name ((ValaSymbol*) _tmp27_);
				_tmp29_ = _tmp28_;
				_tmp30_ = g_strcmp0 (_tmp29_, "GLib.Socket") == 0;
				_g_free0 (_tmp29_);
				if (_tmp30_) {
					ValaCCodeIdentifier* _tmp31_;
					ValaCCodeIdentifier* _tmp32_;
					ValaCCodeFunctionCall* _tmp33_;
					ValaCCodeFunctionCall* _tmp34_;
					ValaCCodeFunctionCall* _result_;
					ValaCCodeFunctionCall* _tmp35_;
					ValaCCodeExpression* _tmp36_;
					_tmp31_ = vala_ccode_identifier_new ("g_socket_get_fd");
					_tmp32_ = _tmp31_;
					_tmp33_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp32_);
					_tmp34_ = _tmp33_;
					_vala_ccode_node_unref0 (_tmp32_);
					_result_ = _tmp34_;
					_tmp35_ = _result_;
					_tmp36_ = expr;
					vala_ccode_function_call_add_argument (_tmp35_, _tmp36_);
					result = (ValaCCodeExpression*) _result_;
					return result;
				} else {
					ValaDataType* _tmp37_;
					ValaTypeSymbol* _tmp38_;
					ValaTypeSymbol* _tmp39_;
					gchar* _tmp40_ = NULL;
					gchar* _tmp41_;
					gboolean _tmp42_;
					_tmp37_ = type;
					_tmp38_ = vala_data_type_get_data_type (_tmp37_);
					_tmp39_ = _tmp38_;
					_tmp40_ = vala_symbol_get_full_name ((ValaSymbol*) _tmp39_);
					_tmp41_ = _tmp40_;
					_tmp42_ = g_strcmp0 (_tmp41_, "GLib.FileDescriptorBased") == 0;
					_g_free0 (_tmp41_);
					if (_tmp42_) {
						ValaCCodeIdentifier* _tmp43_;
						ValaCCodeIdentifier* _tmp44_;
						ValaCCodeFunctionCall* _tmp45_;
						ValaCCodeFunctionCall* _tmp46_;
						ValaCCodeFunctionCall* _result_;
						ValaCCodeFunctionCall* _tmp47_;
						ValaCCodeExpression* _tmp48_;
						_tmp43_ = vala_ccode_identifier_new ("g_file_descriptor_based_get_fd");
						_tmp44_ = _tmp43_;
						_tmp45_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp44_);
						_tmp46_ = _tmp45_;
						_vala_ccode_node_unref0 (_tmp44_);
						_result_ = _tmp46_;
						_tmp47_ = _result_;
						_tmp48_ = expr;
						vala_ccode_function_call_add_argument (_tmp47_, _tmp48_);
						result = (ValaCCodeExpression*) _result_;
						return result;
					}
				}
			}
		}
	}
	result = NULL;
	return result;
}


void vala_gd_bus_module_send_dbus_value (ValaGDBusModule* self, ValaDataType* type, ValaCCodeExpression* builder_expr, ValaCCodeExpression* expr, ValaSymbol* sym) {
	ValaDataType* _tmp0_;
	ValaCCodeExpression* _tmp1_;
	ValaCCodeExpression* _tmp2_ = NULL;
	ValaCCodeExpression* fd;
	ValaCCodeExpression* _tmp3_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (type != NULL);
	g_return_if_fail (builder_expr != NULL);
	g_return_if_fail (expr != NULL);
	_tmp0_ = type;
	_tmp1_ = expr;
	_tmp2_ = vala_gd_bus_module_get_file_descriptor (self, _tmp0_, _tmp1_);
	fd = _tmp2_;
	_tmp3_ = fd;
	if (_tmp3_ != NULL) {
		ValaCCodeIdentifier* _tmp4_;
		ValaCCodeIdentifier* _tmp5_;
		ValaCCodeFunctionCall* _tmp6_;
		ValaCCodeFunctionCall* _tmp7_;
		ValaCCodeFunctionCall* fd_append;
		ValaCCodeFunctionCall* _tmp8_;
		ValaCCodeIdentifier* _tmp9_;
		ValaCCodeIdentifier* _tmp10_;
		ValaCCodeFunctionCall* _tmp11_;
		ValaCCodeExpression* _tmp12_;
		ValaCCodeFunctionCall* _tmp13_;
		ValaCCodeConstant* _tmp14_;
		ValaCCodeConstant* _tmp15_;
		ValaCCodeIdentifier* _tmp16_;
		ValaCCodeIdentifier* _tmp17_;
		ValaCCodeFunctionCall* _tmp18_;
		ValaCCodeFunctionCall* _tmp19_;
		ValaCCodeFunctionCall* builder_add;
		ValaCCodeFunctionCall* _tmp20_;
		ValaCCodeExpression* _tmp21_;
		ValaCCodeUnaryExpression* _tmp22_;
		ValaCCodeUnaryExpression* _tmp23_;
		ValaCCodeFunctionCall* _tmp24_;
		ValaCCodeConstant* _tmp25_;
		ValaCCodeConstant* _tmp26_;
		ValaCCodeFunctionCall* _tmp27_;
		ValaCCodeFunctionCall* _tmp28_;
		ValaCCodeFunction* _tmp29_;
		ValaCCodeFunction* _tmp30_;
		ValaCCodeFunctionCall* _tmp31_;
		_tmp4_ = vala_ccode_identifier_new ("g_unix_fd_list_append");
		_tmp5_ = _tmp4_;
		_tmp6_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp5_);
		_tmp7_ = _tmp6_;
		_vala_ccode_node_unref0 (_tmp5_);
		fd_append = _tmp7_;
		_tmp8_ = fd_append;
		_tmp9_ = vala_ccode_identifier_new ("_fd_list");
		_tmp10_ = _tmp9_;
		vala_ccode_function_call_add_argument (_tmp8_, (ValaCCodeExpression*) _tmp10_);
		_vala_ccode_node_unref0 (_tmp10_);
		_tmp11_ = fd_append;
		_tmp12_ = fd;
		vala_ccode_function_call_add_argument (_tmp11_, _tmp12_);
		_tmp13_ = fd_append;
		_tmp14_ = vala_ccode_constant_new ("NULL");
		_tmp15_ = _tmp14_;
		vala_ccode_function_call_add_argument (_tmp13_, (ValaCCodeExpression*) _tmp15_);
		_vala_ccode_node_unref0 (_tmp15_);
		_tmp16_ = vala_ccode_identifier_new ("g_variant_builder_add");
		_tmp17_ = _tmp16_;
		_tmp18_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp17_);
		_tmp19_ = _tmp18_;
		_vala_ccode_node_unref0 (_tmp17_);
		builder_add = _tmp19_;
		_tmp20_ = builder_add;
		_tmp21_ = builder_expr;
		_tmp22_ = vala_ccode_unary_expression_new (VALA_CCODE_UNARY_OPERATOR_ADDRESS_OF, _tmp21_);
		_tmp23_ = _tmp22_;
		vala_ccode_function_call_add_argument (_tmp20_, (ValaCCodeExpression*) _tmp23_);
		_vala_ccode_node_unref0 (_tmp23_);
		_tmp24_ = builder_add;
		_tmp25_ = vala_ccode_constant_new ("\"h\"");
		_tmp26_ = _tmp25_;
		vala_ccode_function_call_add_argument (_tmp24_, (ValaCCodeExpression*) _tmp26_);
		_vala_ccode_node_unref0 (_tmp26_);
		_tmp27_ = builder_add;
		_tmp28_ = fd_append;
		vala_ccode_function_call_add_argument (_tmp27_, (ValaCCodeExpression*) _tmp28_);
		_tmp29_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp30_ = _tmp29_;
		_tmp31_ = builder_add;
		vala_ccode_function_add_expression (_tmp30_, (ValaCCodeExpression*) _tmp31_);
		_vala_ccode_node_unref0 (builder_add);
		_vala_ccode_node_unref0 (fd_append);
	} else {
		ValaDataType* _tmp32_;
		ValaCCodeExpression* _tmp33_;
		ValaCCodeExpression* _tmp34_;
		ValaSymbol* _tmp35_;
		_tmp32_ = type;
		_tmp33_ = builder_expr;
		_tmp34_ = expr;
		_tmp35_ = sym;
		vala_gvariant_module_write_expression ((ValaGVariantModule*) self, _tmp32_, _tmp33_, _tmp34_, _tmp35_);
	}
	_vala_ccode_node_unref0 (fd);
}


static ValaCCodeExpression* vala_gd_bus_module_create_from_file_descriptor (ValaGDBusModule* self, ValaDataType* type, ValaCCodeExpression* expr) {
	ValaCCodeExpression* result = NULL;
	ValaDataType* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (type != NULL, NULL);
	g_return_val_if_fail (expr != NULL, NULL);
	_tmp0_ = type;
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp0_, VALA_TYPE_OBJECT_TYPE)) {
		ValaDataType* _tmp1_;
		ValaTypeSymbol* _tmp2_;
		ValaTypeSymbol* _tmp3_;
		gchar* _tmp4_ = NULL;
		gchar* _tmp5_;
		gboolean _tmp6_;
		_tmp1_ = type;
		_tmp2_ = vala_data_type_get_data_type (_tmp1_);
		_tmp3_ = _tmp2_;
		_tmp4_ = vala_symbol_get_full_name ((ValaSymbol*) _tmp3_);
		_tmp5_ = _tmp4_;
		_tmp6_ = g_strcmp0 (_tmp5_, "GLib.UnixInputStream") == 0;
		_g_free0 (_tmp5_);
		if (_tmp6_) {
			ValaCCodeIdentifier* _tmp7_;
			ValaCCodeIdentifier* _tmp8_;
			ValaCCodeFunctionCall* _tmp9_;
			ValaCCodeFunctionCall* _tmp10_;
			ValaCCodeFunctionCall* _result_;
			ValaCCodeFunctionCall* _tmp11_;
			ValaCCodeExpression* _tmp12_;
			ValaCCodeFunctionCall* _tmp13_;
			ValaCCodeConstant* _tmp14_;
			ValaCCodeConstant* _tmp15_;
			ValaCCodeFunctionCall* _tmp16_;
			ValaCCodeCastExpression* _tmp17_;
			_tmp7_ = vala_ccode_identifier_new ("g_unix_input_stream_new");
			_tmp8_ = _tmp7_;
			_tmp9_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp8_);
			_tmp10_ = _tmp9_;
			_vala_ccode_node_unref0 (_tmp8_);
			_result_ = _tmp10_;
			_tmp11_ = _result_;
			_tmp12_ = expr;
			vala_ccode_function_call_add_argument (_tmp11_, _tmp12_);
			_tmp13_ = _result_;
			_tmp14_ = vala_ccode_constant_new ("TRUE");
			_tmp15_ = _tmp14_;
			vala_ccode_function_call_add_argument (_tmp13_, (ValaCCodeExpression*) _tmp15_);
			_vala_ccode_node_unref0 (_tmp15_);
			_tmp16_ = _result_;
			_tmp17_ = vala_ccode_cast_expression_new ((ValaCCodeExpression*) _tmp16_, "GUnixInputStream *");
			result = (ValaCCodeExpression*) _tmp17_;
			_vala_ccode_node_unref0 (_result_);
			return result;
		} else {
			ValaDataType* _tmp18_;
			ValaTypeSymbol* _tmp19_;
			ValaTypeSymbol* _tmp20_;
			gchar* _tmp21_ = NULL;
			gchar* _tmp22_;
			gboolean _tmp23_;
			_tmp18_ = type;
			_tmp19_ = vala_data_type_get_data_type (_tmp18_);
			_tmp20_ = _tmp19_;
			_tmp21_ = vala_symbol_get_full_name ((ValaSymbol*) _tmp20_);
			_tmp22_ = _tmp21_;
			_tmp23_ = g_strcmp0 (_tmp22_, "GLib.UnixOutputStream") == 0;
			_g_free0 (_tmp22_);
			if (_tmp23_) {
				ValaCCodeIdentifier* _tmp24_;
				ValaCCodeIdentifier* _tmp25_;
				ValaCCodeFunctionCall* _tmp26_;
				ValaCCodeFunctionCall* _tmp27_;
				ValaCCodeFunctionCall* _result_;
				ValaCCodeFunctionCall* _tmp28_;
				ValaCCodeExpression* _tmp29_;
				ValaCCodeFunctionCall* _tmp30_;
				ValaCCodeConstant* _tmp31_;
				ValaCCodeConstant* _tmp32_;
				ValaCCodeFunctionCall* _tmp33_;
				ValaCCodeCastExpression* _tmp34_;
				_tmp24_ = vala_ccode_identifier_new ("g_unix_output_stream_new");
				_tmp25_ = _tmp24_;
				_tmp26_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp25_);
				_tmp27_ = _tmp26_;
				_vala_ccode_node_unref0 (_tmp25_);
				_result_ = _tmp27_;
				_tmp28_ = _result_;
				_tmp29_ = expr;
				vala_ccode_function_call_add_argument (_tmp28_, _tmp29_);
				_tmp30_ = _result_;
				_tmp31_ = vala_ccode_constant_new ("TRUE");
				_tmp32_ = _tmp31_;
				vala_ccode_function_call_add_argument (_tmp30_, (ValaCCodeExpression*) _tmp32_);
				_vala_ccode_node_unref0 (_tmp32_);
				_tmp33_ = _result_;
				_tmp34_ = vala_ccode_cast_expression_new ((ValaCCodeExpression*) _tmp33_, "GUnixOutputStream *");
				result = (ValaCCodeExpression*) _tmp34_;
				_vala_ccode_node_unref0 (_result_);
				return result;
			} else {
				ValaDataType* _tmp35_;
				ValaTypeSymbol* _tmp36_;
				ValaTypeSymbol* _tmp37_;
				gchar* _tmp38_ = NULL;
				gchar* _tmp39_;
				gboolean _tmp40_;
				_tmp35_ = type;
				_tmp36_ = vala_data_type_get_data_type (_tmp35_);
				_tmp37_ = _tmp36_;
				_tmp38_ = vala_symbol_get_full_name ((ValaSymbol*) _tmp37_);
				_tmp39_ = _tmp38_;
				_tmp40_ = g_strcmp0 (_tmp39_, "GLib.Socket") == 0;
				_g_free0 (_tmp39_);
				if (_tmp40_) {
					ValaCCodeIdentifier* _tmp41_;
					ValaCCodeIdentifier* _tmp42_;
					ValaCCodeFunctionCall* _tmp43_;
					ValaCCodeFunctionCall* _tmp44_;
					ValaCCodeFunctionCall* _result_;
					ValaCCodeFunctionCall* _tmp45_;
					ValaCCodeExpression* _tmp46_;
					ValaCCodeFunctionCall* _tmp47_;
					ValaCCodeConstant* _tmp48_;
					ValaCCodeConstant* _tmp49_;
					_tmp41_ = vala_ccode_identifier_new ("g_socket_new_from_fd");
					_tmp42_ = _tmp41_;
					_tmp43_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp42_);
					_tmp44_ = _tmp43_;
					_vala_ccode_node_unref0 (_tmp42_);
					_result_ = _tmp44_;
					_tmp45_ = _result_;
					_tmp46_ = expr;
					vala_ccode_function_call_add_argument (_tmp45_, _tmp46_);
					_tmp47_ = _result_;
					_tmp48_ = vala_ccode_constant_new ("NULL");
					_tmp49_ = _tmp48_;
					vala_ccode_function_call_add_argument (_tmp47_, (ValaCCodeExpression*) _tmp49_);
					_vala_ccode_node_unref0 (_tmp49_);
					result = (ValaCCodeExpression*) _result_;
					return result;
				}
			}
		}
	}
	result = NULL;
	return result;
}


void vala_gd_bus_module_receive_dbus_value (ValaGDBusModule* self, ValaDataType* type, ValaCCodeExpression* message_expr, ValaCCodeExpression* iter_expr, ValaCCodeExpression* target_expr, ValaSymbol* sym, ValaCCodeExpression* error_expr, gboolean* may_fail) {
	gboolean _vala_may_fail = FALSE;
	ValaCCodeIdentifier* _tmp0_;
	ValaCCodeIdentifier* _tmp1_;
	ValaCCodeFunctionCall* _tmp2_;
	ValaCCodeFunctionCall* _tmp3_;
	ValaCCodeFunctionCall* fd_list;
	ValaCCodeFunctionCall* _tmp4_;
	ValaCCodeExpression* _tmp5_;
	ValaCCodeIdentifier* _tmp6_;
	ValaCCodeIdentifier* _tmp7_;
	ValaCCodeFunctionCall* _tmp8_;
	ValaCCodeFunctionCall* _tmp9_;
	ValaCCodeFunctionCall* fd;
	ValaCCodeFunctionCall* _tmp10_;
	ValaCCodeFunctionCall* _tmp11_;
	ValaCCodeFunctionCall* _tmp12_;
	ValaCCodeIdentifier* _tmp13_;
	ValaCCodeIdentifier* _tmp14_;
	ValaCCodeFunctionCall* _tmp15_;
	ValaCCodeConstant* _tmp16_;
	ValaCCodeConstant* _tmp17_;
	ValaDataType* _tmp18_;
	ValaCCodeFunctionCall* _tmp19_;
	ValaCCodeExpression* _tmp20_ = NULL;
	ValaCCodeExpression* stream;
	ValaCCodeExpression* _tmp21_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (type != NULL);
	g_return_if_fail (message_expr != NULL);
	g_return_if_fail (iter_expr != NULL);
	g_return_if_fail (target_expr != NULL);
	_tmp0_ = vala_ccode_identifier_new ("g_dbus_message_get_unix_fd_list");
	_tmp1_ = _tmp0_;
	_tmp2_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp1_);
	_tmp3_ = _tmp2_;
	_vala_ccode_node_unref0 (_tmp1_);
	fd_list = _tmp3_;
	_tmp4_ = fd_list;
	_tmp5_ = message_expr;
	vala_ccode_function_call_add_argument (_tmp4_, _tmp5_);
	_tmp6_ = vala_ccode_identifier_new ("g_unix_fd_list_get");
	_tmp7_ = _tmp6_;
	_tmp8_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp7_);
	_tmp9_ = _tmp8_;
	_vala_ccode_node_unref0 (_tmp7_);
	fd = _tmp9_;
	_tmp10_ = fd;
	_tmp11_ = fd_list;
	vala_ccode_function_call_add_argument (_tmp10_, (ValaCCodeExpression*) _tmp11_);
	_tmp12_ = fd;
	_tmp13_ = vala_ccode_identifier_new ("_fd_index");
	_tmp14_ = _tmp13_;
	vala_ccode_function_call_add_argument (_tmp12_, (ValaCCodeExpression*) _tmp14_);
	_vala_ccode_node_unref0 (_tmp14_);
	_tmp15_ = fd;
	_tmp16_ = vala_ccode_constant_new ("NULL");
	_tmp17_ = _tmp16_;
	vala_ccode_function_call_add_argument (_tmp15_, (ValaCCodeExpression*) _tmp17_);
	_vala_ccode_node_unref0 (_tmp17_);
	_tmp18_ = type;
	_tmp19_ = fd;
	_tmp20_ = vala_gd_bus_module_create_from_file_descriptor (self, _tmp18_, (ValaCCodeExpression*) _tmp19_);
	stream = _tmp20_;
	_tmp21_ = stream;
	if (_tmp21_ != NULL) {
		ValaCCodeIdentifier* _tmp22_;
		ValaCCodeIdentifier* _tmp23_;
		ValaCCodeFunctionCall* _tmp24_;
		ValaCCodeFunctionCall* _tmp25_;
		ValaCCodeFunctionCall* get_fd;
		ValaCCodeFunctionCall* _tmp26_;
		ValaCCodeExpression* _tmp27_;
		ValaCCodeUnaryExpression* _tmp28_;
		ValaCCodeUnaryExpression* _tmp29_;
		ValaCCodeFunctionCall* _tmp30_;
		ValaCCodeConstant* _tmp31_;
		ValaCCodeConstant* _tmp32_;
		ValaCCodeFunctionCall* _tmp33_;
		ValaCCodeIdentifier* _tmp34_;
		ValaCCodeIdentifier* _tmp35_;
		ValaCCodeUnaryExpression* _tmp36_;
		ValaCCodeUnaryExpression* _tmp37_;
		ValaCCodeFunction* _tmp38_;
		ValaCCodeFunction* _tmp39_;
		ValaCCodeFunctionCall* _tmp40_;
		ValaCCodeFunction* _tmp41_;
		ValaCCodeFunction* _tmp42_;
		ValaCCodeExpression* _tmp43_;
		ValaCCodeExpression* _tmp44_;
		_tmp22_ = vala_ccode_identifier_new ("g_variant_iter_next");
		_tmp23_ = _tmp22_;
		_tmp24_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp23_);
		_tmp25_ = _tmp24_;
		_vala_ccode_node_unref0 (_tmp23_);
		get_fd = _tmp25_;
		_tmp26_ = get_fd;
		_tmp27_ = iter_expr;
		_tmp28_ = vala_ccode_unary_expression_new (VALA_CCODE_UNARY_OPERATOR_ADDRESS_OF, _tmp27_);
		_tmp29_ = _tmp28_;
		vala_ccode_function_call_add_argument (_tmp26_, (ValaCCodeExpression*) _tmp29_);
		_vala_ccode_node_unref0 (_tmp29_);
		_tmp30_ = get_fd;
		_tmp31_ = vala_ccode_constant_new ("\"h\"");
		_tmp32_ = _tmp31_;
		vala_ccode_function_call_add_argument (_tmp30_, (ValaCCodeExpression*) _tmp32_);
		_vala_ccode_node_unref0 (_tmp32_);
		_tmp33_ = get_fd;
		_tmp34_ = vala_ccode_identifier_new ("_fd_index");
		_tmp35_ = _tmp34_;
		_tmp36_ = vala_ccode_unary_expression_new (VALA_CCODE_UNARY_OPERATOR_ADDRESS_OF, (ValaCCodeExpression*) _tmp35_);
		_tmp37_ = _tmp36_;
		vala_ccode_function_call_add_argument (_tmp33_, (ValaCCodeExpression*) _tmp37_);
		_vala_ccode_node_unref0 (_tmp37_);
		_vala_ccode_node_unref0 (_tmp35_);
		_tmp38_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp39_ = _tmp38_;
		_tmp40_ = get_fd;
		vala_ccode_function_add_expression (_tmp39_, (ValaCCodeExpression*) _tmp40_);
		_tmp41_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp42_ = _tmp41_;
		_tmp43_ = target_expr;
		_tmp44_ = stream;
		vala_ccode_function_add_assignment (_tmp42_, _tmp43_, _tmp44_);
		_vala_may_fail = FALSE;
		_vala_ccode_node_unref0 (get_fd);
	} else {
		ValaDataType* _tmp45_;
		ValaCCodeExpression* _tmp46_;
		ValaCCodeExpression* _tmp47_;
		ValaSymbol* _tmp48_;
		ValaCCodeExpression* _tmp49_;
		gboolean _tmp50_ = FALSE;
		_tmp45_ = type;
		_tmp46_ = iter_expr;
		_tmp47_ = target_expr;
		_tmp48_ = sym;
		_tmp49_ = error_expr;
		vala_gvariant_module_read_expression ((ValaGVariantModule*) self, _tmp45_, _tmp46_, _tmp47_, _tmp48_, _tmp49_, &_tmp50_);
		_vala_may_fail = _tmp50_;
	}
	_vala_ccode_node_unref0 (stream);
	_vala_ccode_node_unref0 (fd);
	_vala_ccode_node_unref0 (fd_list);
	if (may_fail) {
		*may_fail = _vala_may_fail;
	}
}


ValaGDBusModule* vala_gd_bus_module_construct (GType object_type) {
	ValaGDBusModule* self = NULL;
	self = (ValaGDBusModule*) vala_gvariant_module_construct (object_type);
	return self;
}


ValaGDBusModule* vala_gd_bus_module_new (void) {
	return vala_gd_bus_module_construct (VALA_TYPE_GD_BUS_MODULE);
}


static void vala_gd_bus_module_class_init (ValaGDBusModuleClass * klass) {
	vala_gd_bus_module_parent_class = g_type_class_peek_parent (klass);
	VALA_CODE_VISITOR_CLASS (klass)->visit_error_domain = vala_gd_bus_module_real_visit_error_domain;
}


static void vala_gd_bus_module_instance_init (ValaGDBusModule * self) {
}


GType vala_gd_bus_module_get_type (void) {
	static volatile gsize vala_gd_bus_module_type_id__volatile = 0;
	if (g_once_init_enter (&vala_gd_bus_module_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ValaGDBusModuleClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vala_gd_bus_module_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ValaGDBusModule), 0, (GInstanceInitFunc) vala_gd_bus_module_instance_init, NULL };
		GType vala_gd_bus_module_type_id;
		vala_gd_bus_module_type_id = g_type_register_static (VALA_TYPE_GVARIANT_MODULE, "ValaGDBusModule", &g_define_type_info, 0);
		g_once_init_leave (&vala_gd_bus_module_type_id__volatile, vala_gd_bus_module_type_id);
	}
	return vala_gd_bus_module_type_id__volatile;
}



